# Choosing Dataset Parameters & `XGBoost` Model Hyperparameters

## Purpose: 
{TODO}

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%load_ext autoreload 
%autoreload 2

import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

import importlib
parameter_analyzer = getattr(
    importlib.import_module("dataset_and_model_parameter_chooser"), 
    "DatasetAndModelParameterAnalyzer"
)

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Load WandB Data & Check Data</h1>

In [2]:
analyzer = parameter_analyzer()

2025-04-02 15:31:22.383 | INFO     | dataset_and_model_parameter_chooser:retrieve_wandb_summary_tables:44 - dataset summary table contains 120 rows
2025-04-02 15:31:22.385 | INFO     | dataset_and_model_parameter_chooser:retrieve_wandb_summary_tables:44 - model summary table contains 7686 rows
2025-04-02 15:31:22.386 | SUCCESS  | dataset_and_model_parameter_chooser:retrieve_wandb_summary_tables:46 - FROM CACHE: Retrieved WandB summary tables

In [3]:
analyzer.run_summary_table_assertions()

2025-04-02 15:31:22.558 | INFO     | dataset_and_model_parameter_chooser:run_summary_table_assertions:87 - Running assertions on summary tables
2025-04-02 15:31:22.560 | INFO     | dataset_and_model_parameter_chooser:run_summary_table_assertions:90 - Running assertions for dataset summary table
2025-04-02 15:31:22.571 | INFO     | dataset_and_model_parameter_chooser:run_summary_table_assertions:90 - Running assertions for model summary table
2025-04-02 15:31:22.746 | SUCCESS  | dataset_and_model_parameter_chooser:run_summary_table_assertions:117 - All assertions passed

In [4]:
for type in analyzer.sweep_results: 
    type
    analyzer.sweep_results[type].head()

'dataset'

,run_id,run_name,state,sweep_name,sweep_id,model.name,dataset.name,model.n_jobs,training.seed,model.max_depth,model.reg_alpha,model.subsample,dataset.cell_line,model.eval_metric,model.n_estimators,training.criterion,model.learning_rate,training.batch_size,training.wandb.track,dataset.target_fields,training.wandb.entity,dataset.min_read_count,training.profile.plots,training.wandb.project,model.enable_categorical,training.profile.metrics,training.wandb.save_code,dataset.three_exon_combos,training.wandb.save_model,training.wandb.save_plots,training.data_split.method,model.early_stopping_rounds,training.data_split.test_set,training.data_split.train_set,training.wandb.save_artifacts,training.data_split.validate_set,dataset.features.binding_matrix.window,dataset.features.binding_matrix.exp_log,dataset.features.binding_matrix.flatten,dataset.features.binding_matrix.exp_norm,dataset.features.binding_matrix.binding_format,runtime.avg_nodes_per_tree,test_loss,test_mean_absolute_error,test_r2_score,test_rmse,train_loss,train_mean_absolute_error,train_r2_score,train_rmse,val_loss,val_mean_absolute_error,val_r2_score,val_rmse
0,1o95bl4u,glamorous-sweep-6,finished,ayans_model_params_yogi_dataset_sweep,11gitmno,XGBRegressor,RBPSEDataset,-1,42,7,0.3,1,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,320,[],yogi-dataset-sweep-feb-2025,False,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,set_defs,100,"['chr2', 'chr8', 'chr12', 'chr16', 'chr20']","['chr1', 'chr3', 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21']",False,"['chr4', 'chr6', 'chr10', 'chr14', 'chr18', 'chr22']",50,True,False,getmm,binary,69.500000,0.000166,0.1645,0.2155,0.2772,0.000047,0.1331,0.3402,0.2330,0.000181,0.1529,0.2067,0.2604
1,5j9ipstu,brisk-sweep-1,finished,ayans_model_params_yogi_dataset_sweep,11gitmno,XGBRegressor,RBPSEDataset,-1,42,7,0.3,1,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,0,[],yogi-dataset-sweep-feb-2025,False,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,set_defs,100,"['chr2', 'chr8', 'chr12', 'chr16', 'chr20']","['chr1', 'chr3', 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21']",False,"['chr4', 'chr6', 'chr10', 'chr14', 'chr18', 'chr22']",50,True,False,getmm,binary,81.634328,0.000055,0.2571,0.1746,0.3328,0.000021,0.2372,0.2062,0.3124,0.000069,0.2484,0.1676,0.3229
2,9kh7spri,sandy-sweep-4,finished,ayans_model_params_yogi_dataset_sweep,11gitmno,XGBRegressor,RBPSEDataset,-1,42,7,0.3,1,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,80,[],yogi-dataset-sweep-feb-2025,False,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,set_defs,100,"['chr2', 'chr8', 'chr12', 'chr16', 'chr20']","['chr1', 'chr3', 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21']",False,"['chr4', 'chr6', 'chr10', 'chr14', 'chr18', 'chr22']",50,True,False,getmm,binary,76.023077,0.000075,0.2013,0.1953,0.3001,0.000026,0.1799,0.2428,0.2745,0.000092,0.1920,0.1891,0.2883
3,ainnw5al,iconic-sweep-3,finished,ayans_model_params_yogi_dataset_sweep,11gitmno,XGBRegressor,RBPSEDataset,-1,42,7,0.3,1,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,[],yogi-dataset-sweep-feb-2025,False,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,set_defs,100,"['chr2', 'chr8', 'chr12', 'chr16', 'chr20']","['chr1', 'chr3', 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21']",False,"['chr4', 'chr6', 'chr10', 'chr14', 'chr18', 'chr22']",50,True,False,getmm,binary,76.436090,0.000064,0.2202,0.1897,0.3120,0.000023,0.1989,0.2338,0.2877,0.000080,0.2103,0.1848,0.3003
4,nhhpps7z,clean-sweep-7,finished,ayans_model_params_yogi_dataset_sweep,11gitmno,XGBRegressor,RBPSEDataset,-1,42,7,0.3,1,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,0,[],yogi-dataset-sweep-feb-2025,False,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,set_defs,100,"['chr2', 'chr8', 'chr12', 'chr16', 'chr20']","['chr1', 'chr3', 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21']",False,"['chr4', 'chr6', 'chr10', 'chr14', 'chr18', 'chr22']",100,True,False,getmm,binary,82.549618,0.000054,0.2590,0.1700,0.3339,0.000021,0.2395,0.2015,0.3142,0.000068,0.2506,0.1626,0.3244

'model'

,run_id,run_name,state,sweep_name,sweep_id,model.name,dataset.name,model.n_jobs,training.seed,dataset.window,model.max_depth,model.objective,model.reg_alpha,model.subsample,dataset.cell_line,model.eval_metric,model.n_estimators,training.criterion,model.learning_rate,training.batch_size,training.wandb.track,dataset.target_fields,training.wandb.entity,dataset.min_read_count,model.colsample_bytree,training.profile.plots,training.wandb.project,dataset.fold_filter.seed,dataset.fold_filter.side,training.profile.metrics,training.wandb.save_code,dataset.three_exon_combos,training.wandb.save_model,training.wandb.save_plots,training.data_split.method,model.early_stopping_rounds,dataset.fold_filter.num_folds,training.data_split.num_folds,training.wandb.save_artifacts,dataset.fold_filter.fold_index,dataset.fold_filter.group_column,training.data_split.group_column,training.data_split.validate_frac_of_train,dataset.features.binding_matrix.in_silico_kd,dataset.features.binding_matrix.binding_format,holdout_fold_mean_mean_absolute_error,holdout_fold_mean_r2_score,holdout_fold_mean_rmse,holdout_loss,holdout_mean_absolute_error,holdout_r2_score,holdout_rmse,model.reg_lambda,model.min_child_weight,model.gamma,outer_loop_holdout_loss,outer_loop_holdout_mean_absolute_error,outer_loop_holdout_r2_score,outer_loop_holdout_rmse
0,h0xal2po,swept-sweep-1,finished,1D_colsample_bytree,i5xmgmsu,XGBRegressor,RBPSEDataset,-1,100,100,7,reg:logistic,0.3,1.0,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,0.5,"['fancy_scatter', 'cumul_resid_dist', ['wandb_faux_pr_curve', {'thresh': 0.5}], ['wandb_faux_roc_curve', {'thresh': 0.5}]]",yogi-xgbregressor-hyperparameter-sweep-march-2025,17,train,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,cross_validation,100,5,5,False,1,ensembl_gene_id,ensembl_gene_id,0.1,True,binary,0.1851,0.2784,0.2837,0.08050,0.1850,0.2785,0.2837,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5ziofv4w,light-sweep-6,finished,1D_colsample_bytree,i5xmgmsu,XGBRegressor,RBPSEDataset,-1,600,100,7,reg:logistic,0.3,1.0,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,0.5,"['fancy_scatter', 'cumul_resid_dist', ['wandb_faux_pr_curve', {'thresh': 0.5}], ['wandb_faux_roc_curve', {'thresh': 0.5}]]",yogi-xgbregressor-hyperparameter-sweep-march-2025,17,train,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,cross_validation,100,5,5,False,1,ensembl_gene_id,ensembl_gene_id,0.1,True,binary,0.1851,0.2785,0.2836,0.08047,0.1851,0.2787,0.2837,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6bew7zlq,mild-sweep-3,finished,1D_colsample_bytree,i5xmgmsu,XGBRegressor,RBPSEDataset,-1,300,100,7,reg:logistic,0.3,1.0,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,0.5,"['fancy_scatter', 'cumul_resid_dist', ['wandb_faux_pr_curve', {'thresh': 0.5}], ['wandb_faux_roc_curve', {'thresh': 0.5}]]",yogi-xgbregressor-hyperparameter-sweep-march-2025,17,train,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,cross_validation,100,5,5,False,1,ensembl_gene_id,ensembl_gene_id,0.1,True,binary,0.1835,0.2839,0.2826,0.07987,0.1835,0.2841,0.2826,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,c5jihx6l,neat-sweep-9,finished,1D_colsample_bytree,i5xmgmsu,XGBRegressor,RBPSEDataset,-1,900,100,7,reg:logistic,0.3,1.0,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,0.5,"['fancy_scatter', 'cumul_resid_dist', ['wandb_faux_pr_curve', {'thresh': 0.5}], ['wandb_faux_roc_curve', {'thresh': 0.5}]]",yogi-xgbregressor-hyperparameter-sweep-march-2025,17,train,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,cross_validation,100,5,5,False,1,ensembl_gene_id,ensembl_gene_id,0.1,True,binary,0.1830,0.2798,0.2833,0.08028,0.1829,0.2804,0.2833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,cr9o6m5h,wise-sweep-8,finished,1D_colsample_bytree,i5xmgmsu,XGBRegressor,RBPSEDataset,-1,800,100,7,reg:logistic,0.3,1.0,K562,"['rmse', 'logloss']",20000,mean_squared_error,0.1,1024,True,['target_psi'],platiglab,40,0.5,"['fancy_scatter', 'cumul_resid_dist', ['wandb_faux_pr_curve', {'thresh': 0.5}], ['wandb_faux_roc_curve', {'thresh': 0.5}]]",yogi-xgbregressor-hyperparameter-sweep-march-2025,17,train,"['r2_score', 'mean_absolute_error', 'rmse']",False,all,False,False,cross_validation,100,5,5,False,1,ensembl_gene_id,ensembl_gene_id,0.1,True,binary,0.1834,0.2798,0.2834,0.08027,0.1833,0.2805,0.2833,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Overall R2 Distributions for Dataset & Model Hyperparameter Sweeps</h1>

In [ ]:
analyzer.load_aggreated_data_stats()

In [ ]:
analyzer.plot_r2_distributions()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Dataset Hyperparameter Sweep</h1>

In [ ]:
analyzer.plot_dataset_r2_per_covariate()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Model Hyperparameter Sweeps</h1>

## 1D Range Sweeps

In [ ]:
analyzer.plot_1D_range_model_hyperparameter_sweeps()

## Inner Fold Splitting Robustness

In [ ]:
analyzer.plot_inner_fold_seed_r2_results()

## 1D Plotting of Sweep Results

In [ ]:
analyzer.plot_interrelated_model_hyperparameter_results_in_1D()

## Higher Dimensional Plotting of Model Sweep Results

In [ ]:
analyzer.plot_interrelated_model_hyperparameter_results_in_higher_dimensions()

## Choosing Top 5 Models After Averaging by Seed

In [5]:
analyzer.show_top_unique_model_configs_after_averaging_by_seed()

2025-04-02 15:31:28.882 | SUCCESS  | dataset_and_model_parameter_chooser:show_top_unique_model_configs_after_averaging_by_seed:599 - Saved top model configurations to ../output/chosen_model_hyperparameters/top_model_configs_per_cell_line.json
2025-04-02 15:31:28.884 | INFO     | dataset_and_model_parameter_chooser:show_top_unique_model_configs_after_averaging_by_seed:601 - Top Model Configurations by Avg. Inner Fold Holdout R2 Score using parameters: ['model.learning_rate', 'model.max_depth', 'model.n_estimators', 'dataset.cell_line']

,model.learning_rate,model.max_depth,model.n_estimators,dataset.cell_line,avg_holdout_r2_score
0,0.05,5,1000,K562,0.281033
1,0.05,5,5000,K562,0.280978
2,0.10,5,500,K562,0.280900
3,0.05,5,750,K562,0.280822
4,0.10,5,5000,K562,0.280789
5,0.01,5,5000,K562,0.280767
6,0.01,7,5000,K562,0.280522
7,0.05,7,750,K562,0.280489
8,0.05,7,5000,K562,0.280433
9,0.05,7,500,K562,0.280422
10,0.10,3,5000,HepG2,0.289478
11,0.10,3,1000,HepG2,0.289467
12,0.05,3,5000,HepG2,0.289222
13,0.05,5,750,HepG2,0.288978
14,0.05,5,1000,HepG2,0.288956
15,0.05,5,5000,HepG2,0.288944
16,0.15,3,500,HepG2,0.288933
17,0.10,5,500,HepG2,0.288833
18,0.10,5,5000,HepG2,0.288767
19,0.01,5,5000,HepG2,0.288722

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Outer Loop Holdout R2 Scores</h1>

In [6]:
run_ids = analyzer.get_run_ids_for_outer_loop_holdout_r2_scores()
run_ids

2025-04-02 15:31:31.625 | SUCCESS  | dataset_and_model_parameter_chooser:get_run_ids_for_outer_loop_holdout_r2_scores:631 - Saved run IDs to ../output/chosen_model_hyperparameters/outer_loop_holdout_run_ids.txt

['4b4ut99v',
 '5p9fa4qj',
 '5wnccz88',
 '6pkzkiki',
 '7d3egmmo',
 '7ybjpr8x',
 'c2sete49',
 'c77y7f5c',
 'd32ys1s8',
 'ekgnwqdr',
 'eu03d3y4',
 'ewggfgac',
 'f9menbn0',
 'nkk2s4xs',
 'p5dyqu5w',
 'qyad9z9d',
 's1fnfmib',
 'snu0kslv',
 'x41h1z3w',
 'yqc355mf']

#### Run the following commands: 

* `source /scratch/jve4pt/platiglib/platiglib_venv/bin/activate`
* `python ./6_run_outer_loop_holdout_r2.py`

In [8]:
analyzer.assert_outer_loop_holdout_r2_scores()

2025-04-02 15:32:46.044 | SUCCESS  | dataset_and_model_parameter_chooser:assert_outer_loop_holdout_r2_scores:646 - Assertions for outer loop holdout R2 scores passed

In [11]:
analyzer.inner_fold_vs_outer_fold_r2_score_table()

2025-04-02 15:38:17.671 | INFO     | dataset_and_model_parameter_chooser:inner_fold_vs_outer_fold_r2_score_table:653 - Joining outer loop R2 scores with avg. R2 scores from inner folds
2025-04-02 15:38:17.675 | SUCCESS  | dataset_and_model_parameter_chooser:inner_fold_vs_outer_fold_r2_score_table:664 - Successfully joined outer loop R2 scores table with top model configurations

,model.learning_rate,model.max_depth,model.n_estimators,dataset.cell_line,avg_holdout_r2_score,outer_loop_holdout_r2_score
0,0.05,5,750,K562,0.280822,0.2713
1,0.05,5,5000,K562,0.280978,0.2713
2,0.05,7,500,K562,0.280422,0.2757
3,0.05,7,750,K562,0.280489,0.2759
4,0.05,7,5000,K562,0.280433,0.2759
5,0.10,5,500,K562,0.280900,0.2722
6,0.10,5,5000,K562,0.280789,0.2722
7,0.05,5,1000,K562,0.281033,0.2713
8,0.05,3,5000,HepG2,0.289222,0.2859
9,0.05,5,750,HepG2,0.288978,0.2880
10,0.05,5,1000,HepG2,0.288956,0.2880
11,0.05,5,5000,HepG2,0.288944,0.2880
12,0.10,3,1000,HepG2,0.289467,0.2885
13,0.10,3,5000,HepG2,0.289478,0.2885
14,0.10,5,500,HepG2,0.288833,0.2874
15,0.10,5,5000,HepG2,0.288767,0.2874
16,0.15,3,500,HepG2,0.288933,0.2847
17,0.01,5,5000,K562,0.280767,0.2712
18,0.01,7,5000,K562,0.280522,0.2716
19,0.01,5,5000,HepG2,0.288722,0.2895

In [12]:
analyzer.save_hyperparameters_for_final_modeling()

2025-04-02 15:41:05.297 | SUCCESS  | dataset_and_model_parameter_chooser:save_hyperparameters_for_final_modeling:697 - Saved final model hyperparameters to ../output/chosen_model_hyperparameters/final_model_hyperparameters.json

,model.learning_rate,model.max_depth,model.n_estimators,dataset.cell_line,holdout_r2_score,outer_loop_holdout_r2_score
0,0.05,7,5000,K562,0.2814,0.2759
1,0.05,7,500,K562,0.2813,0.2757
2,0.10,5,5000,K562,0.2804,0.2722
3,0.01,7,5000,K562,0.2812,0.2716
4,0.05,5,5000,K562,0.2802,0.2713
5,0.01,5,5000,K562,0.2801,0.2712
6,0.01,5,5000,HepG2,0.2896,0.2895
7,0.10,3,5000,HepG2,0.2906,0.2885
8,0.05,5,5000,HepG2,0.2896,0.2880
9,0.10,5,5000,HepG2,0.2907,0.2874
10,0.05,3,5000,HepG2,0.2909,0.2859
11,0.15,3,500,HepG2,0.2902,0.2847

In [ ]:
# analyzer.plot_outer_loop_fold_r2_score_results()