### This loads in the SHAP interaction table from the interaction_path.txt file path

In [1]:
# Load in packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import polars as pl

_=pl.Config.set_tbl_cols(100000)
_=pl.Config.set_tbl_rows(10000)
_=pl.Config.set_tbl_width_chars(10000)
_=pl.Config.set_fmt_str_lengths(10000)

In [2]:
path = "/project/PlatigLab/users/yogi/ENCODE-RNA-Binding-Protein-Network-Modeling/analysis/07_second_order_SHAP_analysis/2_analyze_shap_interaction_values/outputs/SHAP_cache/averages/Signed-Local-SHAP-Mean-Bound-Only.tsv"

In [3]:
table = pd.read_csv(path, sep='\t')

In [4]:
# Keep rows where either RBP1 or RBP2 equals "SAFB"
df_filtered = table[(table['RBP 1'] == 'SAFB') | (table['RBP 2'] == 'SAFB')]

In [9]:
# Sort values high-low
df_filtered = df_filtered.sort_values(by='Value - Signed-Local-SHAP-Mean-Bound-Only', ascending=False)
df_filtered.to_csv('SAFB_value_sorted.csv', index=False)

# Remove 0s
df_filtered = df_filtered[df_filtered['Value - Signed-Local-SHAP-Mean-Bound-Only'].notna() & (df_filtered['Value - Signed-Local-SHAP-Mean-Bound-Only'] != 0)]
df_filtered.to_csv('SAFB_no_zeros.csv', index=False)

# Get top values based on magnitude
df_filtered['Value - Signed-Local-SHAP-Mean-Bound-Only'] = df_filtered['Value - Signed-Local-SHAP-Mean-Bound-Only'].abs()
mag = df_filtered.sort_values(by='Value - Signed-Local-SHAP-Mean-Bound-Only', ascending=False)
mag.to_csv('SAFB_magnitude.csv', index=False)

In [9]:
interactions = table[
    ((table['RBP 1'] == 'IGF2BP1') & (table['RBP 2'] == 'PTBP1')) |
    ((table['RBP 1'] == 'PTBP1') & (table['RBP 2'] == 'IGF2BP1'))
]

In [10]:
interactions

,Cell Line,Column,Column Type,Sorted RBP Pair,RBP 1,Position 1,RBP 2,Position 2,# UBPs - Signed-Local-SHAP-Mean-Bound-Only,Value - Signed-Local-SHAP-Mean-Bound-Only,Rec-Y2H,Street et al | IP-MS,Street et al | IP/SEC-MS (Both),Rec-Y2H/Street et al. IP-MS (Union)
3507,HepG2,IGF2BP1_1-PTBP1_1-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,1,PTBP1,1,0,NaN,Same-Position,False,False,Same-Position
9933,HepG2,IGF2BP1_1-PTBP1_2-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,1,PTBP1,2,30,0.0,Different-Position,False,False,Different-Position
12221,HepG2,PTBP1_1-IGF2BP1_2-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,2,8,0.0,Different-Position,False,False,Different-Position
20958,HepG2,IGF2BP1_1-PTBP1_3-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,1,PTBP1,3,37,0.0,Different-Position,False,False,Different-Position
23246,HepG2,PTBP1_1-IGF2BP1_3-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,3,8,0.0,Different-Position,False,False,Different-Position
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500732,K562,PTBP1_4-IGF2BP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,4,IGF2BP1,6,3,0.0,Different-Position,False,False,Different-Position
514695,K562,IGF2BP1_5-PTBP1_5-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,5,PTBP1,5,30,0.0,Same-Position,False,False,Same-Position
526195,K562,IGF2BP1_5-PTBP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,5,PTBP1,6,0,NaN,Different-Position,False,False,Different-Position
529783,K562,PTBP1_5-IGF2BP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,5,IGF2BP1,6,0,NaN,Different-Position,False,False,Different-Position
543746,K562,IGF2BP1_6-PTBP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,6,PTBP1,6,4,0.0,Same-Position,False,False,Same-Position

In [12]:
interactions = interactions.sort_values(by='Value - Signed-Local-SHAP-Mean-Bound-Only', ascending=False)
interactions.to_csv('PCBP1_IGF2BP1_sorted.csv', index=False)

In [13]:
interactions

,Cell Line,Column,Column Type,Sorted RBP Pair,RBP 1,Position 1,RBP 2,Position 2,# UBPs - Signed-Local-SHAP-Mean-Bound-Only,Value - Signed-Local-SHAP-Mean-Bound-Only,Rec-Y2H,Street et al | IP-MS,Street et al | IP/SEC-MS (Both),Rec-Y2H/Street et al. IP-MS (Union)
297653,K562,PTBP1_1-IGF2BP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,6,17,0.046070,Different-Position,False,False,Different-Position
220369,K562,PTBP1_1-IGF2BP1_2-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,2,14,0.043555,Different-Position,False,False,Different-Position
413718,K562,PTBP1_3-IGF2BP1_4-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,3,IGF2BP1,4,5,0.038576,Different-Position,False,False,Different-Position
278332,K562,PTBP1_1-IGF2BP1_5-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,5,21,0.009479,Different-Position,False,False,Different-Position
34271,HepG2,PTBP1_1-IGF2BP1_4-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,1,IGF2BP1,4,2,0.000000,Different-Position,False,False,Different-Position
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255423,K562,IGF2BP1_1-PTBP1_4-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,1,PTBP1,4,0,NaN,Different-Position,False,False,Different-Position
410130,K562,IGF2BP1_3-PTBP1_4-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,3,PTBP1,4,0,NaN,Different-Position,False,False,Different-Position
448772,K562,IGF2BP1_3-PTBP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,3,PTBP1,6,0,NaN,Different-Position,False,False,Different-Position
526195,K562,IGF2BP1_5-PTBP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,IGF2BP1,5,PTBP1,6,0,NaN,Different-Position,False,False,Different-Position
529783,K562,PTBP1_5-IGF2BP1_6-interaction-shap,interaction,IGF2BP1-PTBP1,PTBP1,5,IGF2BP1,6,0,NaN,Different-Position,False,False,Different-Position

In [14]:
interactions.to_csv('PCBP1_IGF2BP1_sorted.csv', index=False)