# SHAP + Network Analysis

## Purpose: 
{TODO}

## Packages and Options

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import polars as pl 
_=pl.Config.set_tbl_cols(100000)
_=pl.Config.set_tbl_rows(10000)
_=pl.Config.set_tbl_width_chars(10000)
_=pl.Config.set_fmt_str_lengths(10000)

In [2]:
%load_ext autoreload 
%autoreload 2
    
import importlib

SHAP_analysis_class = getattr(
    importlib.import_module("1_shap_network_analyzer"), 
    "ShapNetworkInvestigator"
)

## Instantiate Class

In [3]:
investigator = SHAP_analysis_class()
investigator.hash_metadata

2025-06-12 11:56:24.715 | SUCCESS  | 1_shap_network_analyzer:make_model_metadata_from_hash:124 - FROM CACHE: loaded hash metadata file

,hash,name,gamma,n_jobs,max_depth,objective,reg_alpha,subsample,reg_lambda,eval_metric,n_estimators,learning_rate,colsample_bytree,min_child_weight,early_stopping_rounds,cell_line,seed,shap_expected_value,alpha,l1_ratio
0,e048c0490ea6f3cfa263c0d3e66e9795583c45a8a5ef2d2715dc08920c13290d,ElasticNet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HepG2,17,NaN,0.000100,1.0
1,d3b95df0842783c0abe226462e97e83be58aa11ed676401dfd640438c3ce1e94,ElasticNet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K562,17,NaN,0.000838,0.1
2,c859f2093367b69aff13a5770150b486a226578fc6f13f1aaacda1b4b145d0c6,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,0.1,1.0,"['rmse', 'logloss']",100000.0,0.05,1.00,30.0,100.0,HepG2,17,1.521426,NaN,NaN
3,3cfd52c46852f8a3afe7b35fc548682916e347a79f66b05f13dec661b727a46b,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.5,1.0,0.1,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522846,NaN,NaN
4,e94727bc02235363dfbeed3e0818618e62955e5449e3a143e3c560f5e58d0e3c,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,1.0,1.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522952,NaN,NaN
5,f784792c7eeb91135eb22d916c79bfbef091e56d2a0a8f4ac8afa92d1e9e1538,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.5,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522858,NaN,NaN
6,fdf52464ba1145bed424d92827c559d851550a0117d96a630474c08e558ac4fd,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,1.0,5.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.523033,NaN,NaN
7,8f310837d07486fd286d4ad7975dcdd0c2bdfc795d2d59b1bb38f3ecc50044ca,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.5,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610363,NaN,NaN
8,1a5a622d0e4fb1bc7aeedf84cc41f73cd02c52b204046c305a4746fe7101c069,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.0,1.0,0.1,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610020,NaN,NaN
9,f93fa76e4f7b67d2494c9ef5eadbafe3f38bb4f2cad488040116e580f0cc0de2,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.8,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610097,NaN,NaN
10,3db6261088630963f3314e4c86c2390970e14123d59b38ed980d507266bba8a6,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.0,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.609713,NaN,NaN
11,8f29591764f9e0de183047a4da90dca42b0f2847784de62970a3f20930cbe0db,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.2,1.0,0.5,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610514,NaN,NaN

<h1 style="color: teal; font-weight: bold; font-size: 48px;">View Feature Distribution of Local SHAP</h1>

In [ ]:
# investigator.plot_local_SHAP_distribution_per_feature_as_mp4()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Global SHAP Across Models and for Average Local SHAP</h1>

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs", binding_unique="All-Data")

In [ ]:
tables = investigator.plot_global_SHAP_mean_vs_variance(mode="5_dfs", binding_unique="All-Data")

for key in tables: 
    key 
    tables[key].head()

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs_average", binding_unique="All-Data")

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Local SHAP Variance Analysis</h1>

In [ ]:
investigator.plot_SHAP_CV()

In [ ]:
investigator.plot_SHAP_std()

In [ ]:
investigator.plot_local_SHAP_mean_vs_variance()

In [ ]:
decile_types = ["Bound-Only", "NOT-Bound-Only", '5_dfs_average']

for mode in decile_types: 
    mode
    investigator.calculate_local_SHAP_mean_vs_variance_deciles(mode=mode)

<h1 style="color: teal; font-weight: bold; font-size: 48px;">ElasticNet</h1>

In [ ]:
elasticnet = investigator.load_elasticnet_coefficients()

for key in elasticnet: 
    key 
    elasticnet[key]["coefficients"].head()

In [ ]:
investigator.plot_elasticnet_coefficients()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Position 3 + 4 Significance in Global SHAP/ElasticNet</h1>

In [ ]:
investigator.check_position_3_and_4_significance_for_global_SHAP_and_elasticnet()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Check Variance of Local SHAP per Unique Binding Pattern</h1>

In [ ]:
table = investigator.check_no_SHAP_variance_per_binding_pattern()

In [ ]:
table.sample(10)
table["num_unique_shap_rows"].value_counts()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Make Global SHAP Plots with Variations</h1>

# Variations: 
* Unique Binding Patterns 
* Feature is bound
* Feature is NOT bound
* Feature is NOT bound in CONTROL
* Feature is NOT bound in ROW W/ RBP KD AT ANY POSITION
* Feature is NOT bound in ROW W/ RBP KD AT SPECIFIC POSITION

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs", binding_unique="Unique-Binding")

In [ ]:
tables = investigator.plot_global_SHAP_mean_vs_variance(mode="5_dfs", binding_unique="Unique-Binding")

for key in tables: 
    key 
    tables[key].head()

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs_average", binding_unique="Unique-Binding")

In [ ]:
investigator.plot_global_SHAP_between_unique_binding_and_all_data()

In [ ]:
tables = investigator.calculate_specialized_global_SHAP(mode="Bound-Only", condition=None)
for key in tables: 
    tables[key]

In [ ]:
investigator.plot_global_SHAP(mode="Bound-Only", binding_unique="All-Data")

In [ ]:
tables = investigator.calculate_specialized_global_SHAP(mode="NOT-Bound-Only", condition=None)
for key in tables: 
    tables[key]

In [ ]:
investigator.plot_global_SHAP(mode="NOT-Bound-Only", binding_unique="All-Data")

In [ ]:
investigator.plot_specialized_vs_regular_global_SHAP()

In [ ]:
tables = investigator.calculate_specialized_global_SHAP(mode="NOT-Bound-Only", condition="CTRL")
for key in tables: 
    tables[key]

In [ ]:
investigator.plot_global_SHAP(mode="NOT-Bound-Only-CTRL", binding_unique="All-Data")

In [ ]:
tables = investigator.calculate_specialized_global_SHAP(mode="NOT-Bound-Only", condition="RBP_KD")
for key in tables: 
    tables[key]

In [ ]:
investigator.plot_global_SHAP(mode="NOT-Bound-Only-RBP_KD", binding_unique="All-Data")

In [ ]:
tables = investigator.calculate_specialized_global_SHAP(mode="NOT-Bound-Only", condition="RBP_KD_at_position")
for key in tables: 
    tables[key]

In [ ]:
investigator.plot_global_SHAP(mode="NOT-Bound-Only-RBP_KD_at_position", binding_unique="All-Data")

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Local SHAP Sign Analysis</h1>

# Includes: 


* Percentage of local SHAP that is non-zero at different cutoffs
* Percentage of local SHAP positive/negative either when feature is bound or unbound
* Understanding activation and repression through custom metric

## % Non-Zero SHAP

In [6]:
for mode in ["All-Data", "Unique-Binding"]: 
    investigator.calculate_local_SHAP_percent_non_zero(mode=mode).head()

2025-06-12 11:57:50.389 | SUCCESS  | 1_shap_network_analyzer:calculate_local_SHAP_percent_non_zero:3639 - FROM CACHE: Loading percent non-zero local SHAP for mode All-Data from ../outputs/local_SHAP_percent_non_zero/local_SHAP_percent_non_zero_all_data.tsv

  Cell Line Data Mode       Feature   Zero Cutoff  % Non Zero
0     HepG2  All-Data  AGGF1_1_shap  1.000000e-10  100.000000
1     HepG2  All-Data  AGGF1_1_shap  1.000000e-09  100.000000
2     HepG2  All-Data  AGGF1_1_shap  1.000000e-08  100.000000
3     HepG2  All-Data  AGGF1_1_shap  1.000000e-07  100.000000
4     HepG2  All-Data  AGGF1_1_shap  1.000000e-06    0.044769

2025-06-12 11:57:50.398 | SUCCESS  | 1_shap_network_analyzer:calculate_local_SHAP_percent_non_zero:3639 - FROM CACHE: Loading percent non-zero local SHAP for mode Unique-Binding from ../outputs/local_SHAP_percent_non_zero/local_SHAP_percent_non_zero_unique_binding.tsv

  Cell Line       Data Mode       Feature   Zero Cutoff  % Non Zero
0     HepG2  Unique-Binding  AGGF1_1_shap  1.000000e-10  100.000000
1     HepG2  Unique-Binding  AGGF1_1_shap  1.000000e-09  100.000000
2     HepG2  Unique-Binding  AGGF1_1_shap  1.000000e-08  100.000000
3     HepG2  Unique-Binding  AGGF1_1_shap  1.000000e-07  100.000000
4     HepG2  Unique-Binding  AGGF1_1_shap  1.000000e-06    0.074426

In [ ]:
investigator.plot_local_SHAP_percent_non_zero()

## Negative & Positive Local SHAP

In [ ]:
investigator.calculate_percent_positive_and_negative_local_SHAP_per_feature(mode = "NOT-Bound-Only", underlying_data="Unique-Binding")
investigator.calculate_percent_positive_and_negative_local_SHAP_per_feature(mode = "Bound-Only", underlying_data="Unique-Binding")

In [ ]:
investigator.plot_percent_positive_and_negative_local_SHAP_per_feature(underlying_data="Unique-Binding")

## Custom Metric for Activation and Repression Behavioral Understanding

In [10]:
for binding_mode in ["Bound-Only", "NOT-Bound-Only"]: 
    investigator.calculate_activator_repressor_behavior_score(binding_mode=binding_mode, underlying_data="Unique-Binding").head()

2025-06-12 11:58:39.727 | SUCCESS  | 1_shap_network_analyzer:calculate_activator_repressor_behavior_score:3937 - FROM CACHE: Activator/Repressor behavior score already exists for binding_mode=Bound-Only

,Data Mode,Binding Type,Cell Line,Feature,Zero Cutoff,# Non-Zeros,% Non-Zeros,Num Positive,Sum Positive,Num Negative,Sum Negative,ARBS,NARBS
0,Unique Binding,Bound Only,HepG2,AGGF1_1,0.00000,249,100.000000,0,0.0,249,-0.021096,-5.252797,-1.0
1,Unique Binding,Bound Only,HepG2,AGGF1_1,0.00001,37,14.859438,0,0.0,37,-0.021032,-0.778196,-1.0
2,Unique Binding,Bound Only,HepG2,AGGF1_1,0.00010,37,14.859438,0,0.0,37,-0.021032,-0.778196,-1.0
3,Unique Binding,Bound Only,HepG2,AGGF1_1,0.00100,9,3.614458,0,0.0,9,-0.011172,-0.100547,-1.0
4,Unique Binding,Bound Only,HepG2,AGGF1_1,0.00500,0,0.000000,0,0.0,0,0.000000,NaN,NaN

2025-06-12 11:58:39.738 | SUCCESS  | 1_shap_network_analyzer:calculate_activator_repressor_behavior_score:3937 - FROM CACHE: Activator/Repressor behavior score already exists for binding_mode=NOT-Bound-Only

,Data Mode,Binding Type,Cell Line,Feature,Zero Cutoff,# Non-Zeros,% Non-Zeros,Num Positive,Sum Positive,Num Negative,Sum Negative,ARBS,NARBS
0,Unique Binding,NOT Bound Only,HepG2,AGGF1_1,0.00000,117989,100.000000,117989,0.038784,0,0.0,4576.041542,1.0
1,Unique Binding,NOT Bound Only,HepG2,AGGF1_1,0.00001,51,0.043224,51,0.015631,0,0.0,0.797168,1.0
2,Unique Binding,NOT Bound Only,HepG2,AGGF1_1,0.00010,51,0.043224,51,0.015631,0,0.0,0.797168,1.0
3,Unique Binding,NOT Bound Only,HepG2,AGGF1_1,0.00100,0,0.000000,0,0.000000,0,0.0,NaN,NaN
4,Unique Binding,NOT Bound Only,HepG2,AGGF1_1,0.00500,0,0.000000,0,0.000000,0,0.0,NaN,NaN

In [ ]:
investigator.plot_activator_repressor_behavior_score(underlying_data = "Unique-Binding")

<h1 style="color: red; font-weight: bold; font-size: 60px;">INCOMPLETE</h1>

<h1 style="color: teal; font-weight: bold; font-size: 48px;">SHAP for Zero Binding Rows</h1>

Looks at: 

* Heatmap of `NOT Bound` "`Global SHAP`" for rows of: 
    * Control
    * The KD of the RBP for that feature
    * That feature having in-silico knockdown 

<br>


* Heatmap of % of zero binding events that have "0" `Local SHAP`

<br>

In [ ]:
investigator.shap_for_zero_binding_features_by_condition()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Differential Splicing Events</h1>

### Focuses on: 

* RBP-specific: 
    * \# Significant Diff Events 
    * \# Significant Diff Events w/ RBP KD at **ANY** Position
* Feature-specific: 
    * \# Significant Diff Events w/ RBP KD at **SPECIFIC** Position

In [ ]:
investigator.create_feature_metric_summary_table()

In [ ]:
investigatorigator.plot_differential_splicing_types()

In [ ]:
investigator.plot_differential_ranks()

In [ ]:
investigator.plot_differential_ratios()

In [ ]:
investigator.plot_matching_differential_ratios_scatterplot()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Metric w/ Regulatory Explanation</h1>

* `Global SHAP`
* `ElasticNet coefficients`
* `Total Binding`
* `# Differential Events`

In [ ]:
investigator.plot_feature_metric_summary_table()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Hacky, Quick, and Dirty Analysis</h1>

In [ ]:
investigator.hacky_not_bound_global_SHAP_by_number_binding()

In [ ]:
investigator.hacky_plot_bound_unbound_signed_local_SHAP_vs_PSI()

In [ ]:
investigator.hacky_plot_bound_unbound_all_data_vs_unique_binding_global_SHAP()