# SHAP + Network Analysis

## Purpose: 
{TODO}

## Packages and Options

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import polars as pl 
_=pl.Config.set_tbl_cols(100000)
_=pl.Config.set_tbl_rows(10000)
_=pl.Config.set_tbl_width_chars(10000)
_=pl.Config.set_fmt_str_lengths(10000)

In [2]:
%load_ext autoreload 
%autoreload 2
    
import importlib

SHAP_analysis_class = getattr(
    importlib.import_module("1_shap_network_analyzer"), 
    "ShapNetworkInvestigator"
)

## Instantiate Class

In [3]:
investigator = SHAP_analysis_class()
investigator.hash_metadata

2025-05-15 21:30:43.221 | SUCCESS  | 1_shap_network_analyzer:make_model_metadata_from_hash:77 - FROM CACHE: loaded hash metadata file

,hash,name,gamma,n_jobs,max_depth,objective,reg_alpha,subsample,reg_lambda,eval_metric,n_estimators,learning_rate,colsample_bytree,min_child_weight,early_stopping_rounds,cell_line,seed,shap_expected_value,alpha,l1_ratio
0,e048c0490ea6f3cfa263c0d3e66e9795583c45a8a5ef2d2715dc08920c13290d,ElasticNet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HepG2,17,NaN,0.000100,1.0
1,d3b95df0842783c0abe226462e97e83be58aa11ed676401dfd640438c3ce1e94,ElasticNet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K562,17,NaN,0.000838,0.1
2,c859f2093367b69aff13a5770150b486a226578fc6f13f1aaacda1b4b145d0c6,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,0.1,1.0,"['rmse', 'logloss']",100000.0,0.05,1.00,30.0,100.0,HepG2,17,1.521426,NaN,NaN
3,3cfd52c46852f8a3afe7b35fc548682916e347a79f66b05f13dec661b727a46b,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.5,1.0,0.1,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522846,NaN,NaN
4,e94727bc02235363dfbeed3e0818618e62955e5449e3a143e3c560f5e58d0e3c,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,1.0,1.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522952,NaN,NaN
5,f784792c7eeb91135eb22d916c79bfbef091e56d2a0a8f4ac8afa92d1e9e1538,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.5,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.522858,NaN,NaN
6,fdf52464ba1145bed424d92827c559d851550a0117d96a630474c08e558ac4fd,XGBRegressor,0.5,-1.0,3.0,reg:logistic,0.0,1.0,5.0,"['rmse', 'logloss']",100000.0,0.05,0.75,30.0,100.0,HepG2,17,1.523033,NaN,NaN
7,8f310837d07486fd286d4ad7975dcdd0c2bdfc795d2d59b1bb38f3ecc50044ca,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.5,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610363,NaN,NaN
8,1a5a622d0e4fb1bc7aeedf84cc41f73cd02c52b204046c305a4746fe7101c069,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.0,1.0,0.1,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610020,NaN,NaN
9,f93fa76e4f7b67d2494c9ef5eadbafe3f38bb4f2cad488040116e580f0cc0de2,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.8,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610097,NaN,NaN
10,3db6261088630963f3314e4c86c2390970e14123d59b38ed980d507266bba8a6,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.0,1.0,10.0,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.609713,NaN,NaN
11,8f29591764f9e0de183047a4da90dca42b0f2847784de62970a3f20930cbe0db,XGBRegressor,0.5,-1.0,5.0,reg:logistic,0.2,1.0,0.5,"['rmse', 'logloss']",100000.0,0.05,0.50,1.0,100.0,K562,17,1.610514,NaN,NaN

<h1 style="color: teal; font-weight: bold; font-size: 48px;">View Feature Distribution of Local SHAP</h1>

In [ ]:
# investigator.plot_local_SHAP_distribution_per_feature_as_mp4()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Global SHAP Across Models and for Average</h1>

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs")

In [ ]:
tables = investigator.plot_global_SHAP_mean_vs_variance(mode="5_dfs")

for key in tables: 
    key 
    tables[key].head()

In [ ]:
investigator.plot_global_SHAP(mode="5_dfs_average")

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Local SHAP Variance Analysis</h1>

In [ ]:
investigator.plot_SHAP_CV()

In [ ]:
investigator.plot_SHAP_std()

In [ ]:
investigator.plot_local_SHAP_mean_vs_variance()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">ElasticNet</h1>

In [ ]:
elasticnet = investigator.load_elasticnet_coefficients()

for key in elasticnet: 
    key 
    elasticnet[key]["coefficients"].head()

In [ ]:
investigator.plot_elasticnet_coefficients()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Differential Splicing Events</h1>

### Focuses on: 

* RBP-specific: 
    * \# Significant Diff Events 
    * \# Significant Diff Events w/ RBP KD at **ANY** Position
* Feature-specific: 
    * \# Significant Diff Events w/ RBP KD at **SPECIFIC** Position

In [10]:
investigator.feature_metric_summary_table.tail(n=102).head(n=12)

,RBP,Position,Cell Line,Feature,Global SHAP,ElasticNet Coefficient,Binding Percentage,Total Binding,# Diff. Events,# Diff. Events + Binding (Any Pos.),# Diff. Events + Binding (Specific Pos.),% Diff. Events + Binding (Any Pos.),% Diff. Events + Binding (Specific Pos.),Total RBP Binding,Binding Normalized % Diff. Events,Binding Normalized % Diff. Events + Binding (Any Pos.),Binding Normalized % Diff. Events + Binding (Specific Pos.)
1362,U2AF2,1,K562,U2AF2_1,0.005617,0.021088,2.665903,172700,1777.0,247.0,60.0,13.899831,3.376477,744970,0.238533,0.033156,0.034742
1363,U2AF2,2,K562,U2AF2_2,0.000139,0.000000,0.396860,25709,1777.0,247.0,8.0,13.899831,0.450197,744970,0.238533,0.033156,0.031118
1364,U2AF2,3,K562,U2AF2_3,0.009355,0.031296,2.905186,188201,1777.0,247.0,79.0,13.899831,4.445695,744970,0.238533,0.033156,0.041976
1365,U2AF2,4,K562,U2AF2_4,0.000258,-0.000000,0.465136,30132,1777.0,247.0,12.0,13.899831,0.675295,744970,0.238533,0.033156,0.039825
1366,U2AF2,5,K562,U2AF2_5,0.008733,-0.012962,4.674886,302844,1777.0,247.0,133.0,13.899831,7.484524,744970,0.238533,0.033156,0.043917
1367,U2AF2,6,K562,U2AF2_6,0.001336,-0.033731,0.391843,25384,1777.0,247.0,7.0,13.899831,0.393922,744970,0.238533,0.033156,0.027576
1368,UCHL5,1,K562,UCHL5_1,0.006092,-0.004234,6.525936,422757,315.0,63.0,19.0,20.000000,6.031746,2802257,0.011241,0.002248,0.004494
1369,UCHL5,2,K562,UCHL5_2,0.033789,-0.032256,9.118191,590686,315.0,63.0,26.0,20.000000,8.253968,2802257,0.011241,0.002248,0.004402
1370,UCHL5,3,K562,UCHL5_3,0.088084,0.077747,5.204130,337129,315.0,63.0,6.0,20.000000,1.904762,2802257,0.011241,0.002248,0.001780
1371,UCHL5,4,K562,UCHL5_4,0.108420,0.087913,6.415163,415581,315.0,63.0,14.0,20.000000,4.444444,2802257,0.011241,0.002248,0.003369
1372,UCHL5,5,K562,UCHL5_5,0.026374,-0.022581,7.414499,480319,315.0,63.0,18.0,20.000000,5.714286,2802257,0.011241,0.002248,0.003748
1373,UCHL5,6,K562,UCHL5_6,0.017423,-0.018177,8.579438,555785,315.0,63.0,15.0,20.000000,4.761905,2802257,0.011241,0.002248,0.002699

In [6]:
investigator.create_feature_metric_summary_table()

2025-05-15 21:36:25.804 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1162 - Feature metric summary table does not exist. Creating...
2025-05-15 21:36:25.806 | SUCCESS  | 1_shap_network_analyzer:calculate_global_SHAP:348 - FROM CACHE: loaded global SHAP file for mode 5_dfs_average
2025-05-15 21:36:25.806 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1172 - Processing cell line: HepG2
2025-05-15 21:36:25.826 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1218 - Calculating Binding Percentage for each feature
2025-05-15 21:36:44.243 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1246 - Calculating # differential significant events
2025-05-15 21:36:51.410 | WARNING  | 1_shap_network_analyzer:create_feature_metric_summary_table:1291 - RBPs with no knockdown data in HepG2: AGGF1, CDC40, DGCR8, DROSHA, EIF3H, EXOSC5, FXR2, IGF2BP1, NOLC1, PABPN1, POLR2G, RBM5, RPS3, SAFB, SDAD1, SRSF7, STAU2, WDR43, ZC3H11A, ZNF800
Length: 20
2025-05-15 21:36:51.411 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1172 - Processing cell line: K562
2025-05-15 21:36:51.435 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1218 - Calculating Binding Percentage for each feature
2025-05-15 21:37:26.330 | INFO     | 1_shap_network_analyzer:create_feature_metric_summary_table:1246 - Calculating # differential significant events
2025-05-15 21:37:35.823 | WARNING  | 1_shap_network_analyzer:create_feature_metric_summary_table:1291 - RBPs with no knockdown data in K562: ADAT1, APEX1, DDX21, DDX42, DDX43, DDX6, DGCR8, EIF4E, ELAC2, ELAVL1, EXOSC10, EXOSC5, FXR2, GARS, GNL3, IGF2BP1, METTL1, MORC2, NIPBL, NOLC1, NPM1, PRPF8, RNF187, RPS11, RPS3, RPS6, RYBP, SAFB, SDAD1, SF3B1, SRSF7, SRSF9, TRA2A, XRCC6, YWHAG, ZC3H11A, ZNF622, ZNF800
Length: 38
2025-05-15 21:37:35.846 | SUCCESS  | 1_shap_network_analyzer:create_feature_metric_summary_table:1324 - Created feature metric summary table

           RBP  Position Cell Line     Feature   Global SHAP  \
0        AGGF1         1     HepG2     AGGF1_1  4.224195e-07
1        AGGF1         2     HepG2     AGGF1_2  5.639487e-05
2        AGGF1         3     HepG2     AGGF1_3  7.411269e-04
3        AGGF1         4     HepG2     AGGF1_4  1.937224e-04
4        AGGF1         5     HepG2     AGGF1_5  3.205694e-05
5        AGGF1         6     HepG2     AGGF1_6  7.776903e-05
6        AKAP1         1     HepG2     AKAP1_1  5.033473e-04
7        AKAP1         2     HepG2     AKAP1_2  6.331148e-04
8        AKAP1         3     HepG2     AKAP1_3  0.000000e+00
9        AKAP1         4     HepG2     AKAP1_4  4.409641e-06
10       AKAP1         5     HepG2     AKAP1_5  1.630846e-06
11       AKAP1         6     HepG2     AKAP1_6  4.247955e-04
12         AQR         1     HepG2       AQR_1  5.764215e-03
13         AQR         2     HepG2       AQR_2  4.156559e-02
14         AQR         3     HepG2       AQR_3  1.110157e-01
15         AQR         4     HepG2       AQR_4  4.606772e-02
16         AQR         5     HepG2       AQR_5  3.418976e-02
17         AQR         6     HepG2       AQR_6  7.318747e-03
18       BCCIP         1     HepG2     BCCIP_1  0.000000e+00
19       BCCIP         2     HepG2     BCCIP_2  0.000000e+00
20       BCCIP         3     HepG2     BCCIP_3  0.000000e+00
21       BCCIP         4     HepG2     BCCIP_4  0.000000e+00
22       BCCIP         5     HepG2     BCCIP_5  0.000000e+00
23       BCCIP         6     HepG2     BCCIP_6  0.000000e+00
24      BCLAF1         1     HepG2    BCLAF1_1  2.693535e-03
25      BCLAF1         2     HepG2    BCLAF1_2  1.869491e-02
26      BCLAF1         3     HepG2    BCLAF1_3  1.948991e-01
27      BCLAF1         4     HepG2    BCLAF1_4  2.683703e-01
28      BCLAF1         5     HepG2    BCLAF1_5  2.500505e-02
29      BCLAF1         6     HepG2    BCLAF1_6  3.069591e-02
30       BUD13         1     HepG2     BUD13_1  2.383828e-03
31       BUD13         2     HepG2     BUD13_2  2.282244e-03
32       BUD13         3     HepG2     BUD13_3  2.401005e-02
33       BUD13         4     HepG2     BUD13_4  4.676259e-03
34       BUD13         5     HepG2     BUD13_5  1.446640e-02
35       BUD13         6     HepG2     BUD13_6  1.649165e-03
36       CDC40         1     HepG2     CDC40_1  4.889643e-04
37       CDC40         2     HepG2     CDC40_2  8.124426e-05
38       CDC40         3     HepG2     CDC40_3  2.477939e-04
39       CDC40         4     HepG2     CDC40_4  1.502713e-03
40       CDC40         5     HepG2     CDC40_5  3.523483e-06
41       CDC40         6     HepG2     CDC40_6  0.000000e+00
42      CSTF2T         1     HepG2    CSTF2T_1  9.207489e-05
43      CSTF2T         2     HepG2    CSTF2T_2  2.026202e-04
44      CSTF2T         3     HepG2    CSTF2T_3  1.821261e-03
45      CSTF2T         4     HepG2    CSTF2T_4  2.483604e-04
46      CSTF2T         5     HepG2    CSTF2T_5  4.905783e-05
47      CSTF2T         6     HepG2    CSTF2T_6  3.509512e-05
48       CSTF2         1     HepG2     CSTF2_1  7.646859e-04
49       CSTF2         2     HepG2     CSTF2_2  0.000000e+00
50       CSTF2         3     HepG2     CSTF2_3  0.000000e+00
51       CSTF2         4     HepG2     CSTF2_4  0.000000e+00
52       CSTF2         5     HepG2     CSTF2_5  0.000000e+00
53       CSTF2         6     HepG2     CSTF2_6  7.649780e-05
54       DDX3X         1     HepG2     DDX3X_1  2.463290e-02
55       DDX3X         2     HepG2     DDX3X_2  4.502641e-03
56       DDX3X         3     HepG2     DDX3X_3  3.696969e-02
57       DDX3X         4     HepG2     DDX3X_4  1.304215e-02
58       DDX3X         5     HepG2     DDX3X_5  4.682209e-02
59       DDX3X         6     HepG2     DDX3X_6  1.036990e-02
60       DDX52         1     HepG2     DDX52_1  0.000000e+00
61       DDX52         2     HepG2     DDX52_2  2.776925e-04
62       DDX52         3     HepG2     DDX52_3  0.000000e+00
63       DDX52         4     HepG2     DDX52_4  0.000000e+00
64       DDX52         5     HepG2     DDX52_5  2.962471e-04
65       DDX52         6     HepG2     DDX52_6  0.000000e+00
66       DDX55         1     HepG2     DDX55_1  1.644634e-04
67       DDX55         2     HepG2     DDX55_2  2.250806e-03
68       DDX55         3     HepG2     DDX55_3  7.080076e-05
69       DDX55         4     HepG2     DDX55_4  8.201743e-04
70       DDX55         5     HepG2     DDX55_5  5.045856e-04
71       DDX55         6     HepG2     DDX55_6  9.870518e-05
72       DDX59         1     HepG2     DDX59_1  2.845908e-04
73       DDX59         2     HepG2     DDX59_2  3.120705e-04
74       DDX59         3     HepG2     DDX59_3  1.030570e-03
75       DDX59         4     HepG2     DDX59_4  1.377831e-04
76       DDX59         5     HepG2     DDX59_5  5.294249e-04
77       DDX59         6     HepG2     DDX59_6  2.797839e-04
78        DDX6         1     HepG2      DDX6_1  0.000000e+00
79        DDX6         2     HepG2      DDX6_2  3.760775e-06
80        DDX6         3     HepG2      DDX6_3  2.815781e-04
81        DDX6         4     HepG2      DDX6_4  3.460182e-06
82        DDX6         5     HepG2      DDX6_5  0.000000e+00
83        DDX6         6     HepG2      DDX6_6  5.549950e-05
84       DGCR8         1     HepG2     DGCR8_1  3.509873e-04
85       DGCR8         2     HepG2     DGCR8_2  1.626346e-04
86       DGCR8         3     HepG2     DGCR8_3  2.247878e-03
87       DGCR8         4     HepG2     DGCR8_4  3.144872e-05
88       DGCR8         5     HepG2     DGCR8_5  0.000000e+00
89       DGCR8         6     HepG2     DGCR8_6  2.403918e-04
90       DHX30         1     HepG2     DHX30_1  0.000000e+00
91       DHX30         2     HepG2     DHX30_2  0.000000e+00
92       DHX30         3     HepG2     DHX30_3  0.000000e+00
93       DHX30         4     HepG2     DHX30_4  0.000000e+00
94       DHX30         5     HepG2     DHX30_5  0.000000e+00
95       DHX30         6     HepG2     DHX30_6  0.000000e+00
96        DKC1         1     HepG2      DKC1_1  1.137971e-04
97        DKC1         2     HepG2      DKC1_2  1.518490e-06
98        DKC1         3     HepG2      DKC1_3  2.787319e-04
99        DKC1         4     HepG2      DKC1_4  2.753836e-04
100       DKC1         5     HepG2      DKC1_5  3.173115e-04
101       DKC1         6     HepG2      DKC1_6  0.000000e+00
102     DROSHA         1     HepG2    DROSHA_1  2.330813e-04
103     DROSHA         2     HepG2    DROSHA_2  1.699721e-05
104     DROSHA         3     HepG2    DROSHA_3  7.901155e-05
105     DROSHA         4     HepG2    DROSHA_4  1.421305e-04
106     DROSHA         5     HepG2    DROSHA_5  3.365990e-05
107     DROSHA         6     HepG2    DROSHA_6  1.829189e-06
108     EFTUD2         1     HepG2    EFTUD2_1  1.651586e-03
109     EFTUD2         2     HepG2    EFTUD2_2  2.060457e-02
110     EFTUD2         3     HepG2    EFTUD2_3  2.882023e-03
111     EFTUD2         4     HepG2    EFTUD2_4  1.046188e-02
112     EFTUD2         5     HepG2    EFTUD2_5  4.666272e-03
113     EFTUD2         6     HepG2    EFTUD2_6  4.264903e-04
114      EIF3D         1     HepG2     EIF3D_1  0.000000e+00
115      EIF3D         2     HepG2     EIF3D_2  0.000000e+00
116      EIF3D         3     HepG2     EIF3D_3  3.498259e-04
117      EIF3D         4     HepG2     EIF3D_4  7.362258e-05
118      EIF3D         5     HepG2     EIF3D_5  2.289520e-03
119      EIF3D         6     HepG2     EIF3D_6  1.647696e-03
120      EIF3H         1     HepG2     EIF3H_1  1.010025e-04
121      EIF3H         2     HepG2     EIF3H_2  5.578304e-05
122      EIF3H         3     HepG2     EIF3H_3  1.934796e-03
123      EIF3H         4     HepG2     EIF3H_4  1.784697e-03
124      EIF3H         5     HepG2     EIF3H_5  6.840678e-05
125      EIF3H         6     HepG2     EIF3H_6  6.176067e-04
126     EXOSC5         1     HepG2    EXOSC5_1  0.000000e+00
127     EXOSC5         2     HepG2    EXOSC5_2  3.360671e-06
128     EXOSC5         3     HepG2    EXOSC5_3  0.000000e+00
129     EXOSC5         4     HepG2    EXOSC5_4  0.000000e+00
130     EXOSC5         5     HepG2    EXOSC5_5  5.893729e-05
131     EXOSC5         6     HepG2    EXOSC5_6  0.000000e+00
132    FAM120A         1     HepG2   FAM120A_1  0.000000e+00
133    FAM120A         2     HepG2   FAM120A_2  3.336872e-03
134    FAM120A         3     HepG2   FAM120A_3  7.416301e-06
135    FAM120A         4     HepG2   FAM120A_4  1.627294e-04
136    FAM120A         5     HepG2   FAM120A_5  3.625257e-06
137    FAM120A         6     HepG2   FAM120A_6  2.997975e-04
138    FASTKD2         1     HepG2   FASTKD2_1  0.000000e+00
139    FASTKD2         2     HepG2   FASTKD2_2  5.724311e-05
140    FASTKD2         3     HepG2   FASTKD2_3  0.000000e+00
141    FASTKD2         4     HepG2   FASTKD2_4  0.000000e+00
142    FASTKD2         5     HepG2   FASTKD2_5  2.308179e-05
143    FASTKD2         6     HepG2   FASTKD2_6  5.927071e-04
144      FKBP4         1     HepG2     FKBP4_1  0.000000e+00
145      FKBP4         2     HepG2     FKBP4_2  1.932352e-03
146      FKBP4         3     HepG2     FKBP4_3  5.225941e-04
147      FKBP4         4     HepG2     FKBP4_4  0.000000e+00
148      FKBP4         5     HepG2     FKBP4_5  0.000000e+00
149      FKBP4         6     HepG2     FKBP4_6  0.000000e+00
150        FTO         1     HepG2       FTO_1  4.332943e-05
151        FTO         2     HepG2       FTO_2  0.000000e+00
152        FTO         3     HepG2       FTO_3  2.819328e-04
153        FTO         4     HepG2       FTO_4  0.000000e+00
154        FTO         5     HepG2       FTO_5  7.978707e-04
155        FTO         6     HepG2       FTO_6  7.868969e-05
156      FUBP3         1     HepG2     FUBP3_1  1.122935e-04
157      FUBP3         2     HepG2     FUBP3_2  0.000000e+00
158      FUBP3         3     HepG2     FUBP3_3  1.728740e-04
159      FUBP3         4     HepG2     FUBP3_4  2.217122e-05
160      FUBP3         5     HepG2     FUBP3_5  0.000000e+00
161      FUBP3         6     HepG2     FUBP3_6  1.910555e-03
162        FUS         1     HepG2       FUS_1  3.379533e-05
163        FUS         2     HepG2       FUS_2  0.000000e+00
164        FUS         3     HepG2       FUS_3  0.000000e+00
165        FUS         4     HepG2       FUS_4  3.112765e-04
166        FUS         5     HepG2       FUS_5  0.000000e+00
167        FUS         6     HepG2       FUS_6  0.000000e+00
168       FXR2         1     HepG2      FXR2_1  9.693360e-05
169       FXR2         2     HepG2      FXR2_2  4.124366e-04
170       FXR2         3     HepG2      FXR2_3  5.267181e-03
171       FXR2         4     HepG2      FXR2_4  9.731019e-03
172       FXR2         5     HepG2      FXR2_5  2.467369e-04
173       FXR2         6     HepG2      FXR2_6  1.658391e-03
174      G3BP1         1     HepG2     G3BP1_1  3.163485e-04
175      G3BP1         2     HepG2     G3BP1_2  7.007430e-04
176      G3BP1         3     HepG2     G3BP1_3  6.234020e-02
177      G3BP1         4     HepG2     G3BP1_4  6.137973e-02
178      G3BP1         5     HepG2     G3BP1_5  9.088635e-03
179      G3BP1         6     HepG2     G3BP1_6  4.097531e-03
180      GRSF1         1     HepG2     GRSF1_1  1.155864e-03
181      GRSF1         2     HepG2     GRSF1_2  1.796603e-05
182      GRSF1         3     HepG2     GRSF1_3  0.000000e+00
183      GRSF1         4     HepG2     GRSF1_4  4.548128e-06
184      GRSF1         5     HepG2     GRSF1_5  8.881936e-06
185      GRSF1         6     HepG2     GRSF1_6  6.867117e-06
186      GRWD1         1     HepG2     GRWD1_1  3.276997e-03
187      GRWD1         2     HepG2     GRWD1_2  4.270126e-02
188      GRWD1         3     HepG2     GRWD1_3  1.144026e-01
189      GRWD1         4     HepG2     GRWD1_4  1.277639e-01
190      GRWD1         5     HepG2     GRWD1_5  5.894284e-02
191      GRWD1         6     HepG2     GRWD1_6  5.819685e-02
192     GTF2F1         1     HepG2    GTF2F1_1  3.737546e-05
193     GTF2F1         2     HepG2    GTF2F1_2  3.888787e-04
194     GTF2F1         3     HepG2    GTF2F1_3  2.293667e-06
195     GTF2F1         4     HepG2    GTF2F1_4  1.586156e-04
196     GTF2F1         5     HepG2    GTF2F1_5  1.339327e-04
197     GTF2F1         6     HepG2    GTF2F1_6  1.389693e-04
198       HLTF         1     HepG2      HLTF_1  0.000000e+00
199       HLTF         2     HepG2      HLTF_2  1.079459e-03
200       HLTF         3     HepG2      HLTF_3  1.081412e-03
201       HLTF         4     HepG2      HLTF_4  1.585769e-03
202       HLTF         5     HepG2      HLTF_5  0.000000e+00
203       HLTF         6     HepG2      HLTF_6  1.744783e-03
204    HNRNPA1         1     HepG2   HNRNPA1_1  0.000000e+00
205    HNRNPA1         2     HepG2   HNRNPA1_2  0.000000e+00
206    HNRNPA1         3     HepG2   HNRNPA1_3  0.000000e+00
207    HNRNPA1         4     HepG2   HNRNPA1_4  0.000000e+00
208    HNRNPA1         5     HepG2   HNRNPA1_5  0.000000e+00
209    HNRNPA1         6     HepG2   HNRNPA1_6  0.000000e+00
210     HNRNPC         1     HepG2    HNRNPC_1  5.948195e-06
211     HNRNPC         2     HepG2    HNRNPC_2  2.486786e-04
212     HNRNPC         3     HepG2    HNRNPC_3  4.571144e-03
213     HNRNPC         4     HepG2    HNRNPC_4  3.626799e-06
214     HNRNPC         5     HepG2    HNRNPC_5  6.200441e-06
215     HNRNPC         6     HepG2    HNRNPC_6  6.056196e-04
216     HNRNPK         1     HepG2    HNRNPK_1  1.429335e-03
217     HNRNPK         2     HepG2    HNRNPK_2  1.940690e-03
218     HNRNPK         3     HepG2    HNRNPK_3  5.453546e-03
219     HNRNPK         4     HepG2    HNRNPK_4  5.647968e-05
220     HNRNPK         5     HepG2    HNRNPK_5  0.000000e+00
221     HNRNPK         6     HepG2    HNRNPK_6  0.000000e+00
222     HNRNPL         1     HepG2    HNRNPL_1  2.141563e-04
223     HNRNPL         2     HepG2    HNRNPL_2  0.000000e+00
224     HNRNPL         3     HepG2    HNRNPL_3  0.000000e+00
225     HNRNPL         4     HepG2    HNRNPL_4  3.059112e-06
226     HNRNPL         5     HepG2    HNRNPL_5  0.000000e+00
227     HNRNPL         6     HepG2    HNRNPL_6  1.300746e-03
228     HNRNPM         1     HepG2    HNRNPM_1  0.000000e+00
229     HNRNPM         2     HepG2    HNRNPM_2  3.957746e-04
230     HNRNPM         3     HepG2    HNRNPM_3  1.399229e-03
231     HNRNPM         4     HepG2    HNRNPM_4  2.804393e-03
232     HNRNPM         5     HepG2    HNRNPM_5  0.000000e+00
233     HNRNPM         6     HepG2    HNRNPM_6  0.000000e+00
234   HNRNPUL1         1     HepG2  HNRNPUL1_1  0.000000e+00
235   HNRNPUL1         2     HepG2  HNRNPUL1_2  0.000000e+00
236   HNRNPUL1         3     HepG2  HNRNPUL1_3  0.000000e+00
237   HNRNPUL1         4     HepG2  HNRNPUL1_4  0.000000e+00
238   HNRNPUL1         5     HepG2  HNRNPUL1_5  0.000000e+00
239   HNRNPUL1         6     HepG2  HNRNPUL1_6  0.000000e+00
240     HNRNPU         1     HepG2    HNRNPU_1  0.000000e+00
241     HNRNPU         2     HepG2    HNRNPU_2  0.000000e+00
242     HNRNPU         3     HepG2    HNRNPU_3  0.000000e+00
243     HNRNPU         4     HepG2    HNRNPU_4  0.000000e+00
244     HNRNPU         5     HepG2    HNRNPU_5  0.000000e+00
245     HNRNPU         6     HepG2    HNRNPU_6  0.000000e+00
246    IGF2BP1         1     HepG2   IGF2BP1_1  5.873193e-03
247    IGF2BP1         2     HepG2   IGF2BP1_2  1.805878e-03
248    IGF2BP1         3     HepG2   IGF2BP1_3  1.476791e-02
249    IGF2BP1         4     HepG2   IGF2BP1_4  1.494330e-02
250    IGF2BP1         5     HepG2   IGF2BP1_5  9.232639e-04
251    IGF2BP1         6     HepG2   IGF2BP1_6  2.110285e-03
252    IGF2BP3         1     HepG2   IGF2BP3_1  2.659023e-03
253    IGF2BP3         2     HepG2   IGF2BP3_2  5.763492e-04
254    IGF2BP3         3     HepG2   IGF2BP3_3  1.041723e-03
255    IGF2BP3         4     HepG2   IGF2BP3_4  7.718484e-03
256    IGF2BP3         5     HepG2   IGF2BP3_5  7.684100e-04
257    IGF2BP3         6     HepG2   IGF2BP3_6  3.866686e-04
258       ILF3         1     HepG2      ILF3_1  9.280987e-06
259       ILF3         2     HepG2      ILF3_2  1.327394e-04
260       ILF3         3     HepG2      ILF3_3  2.265715e-03
261       ILF3         4     HepG2      ILF3_4  2.325751e-03
262       ILF3         5     HepG2      ILF3_5  0.000000e+00
263       ILF3         6     HepG2      ILF3_6  0.000000e+00
264      KHSRP         1     HepG2     KHSRP_1  5.059283e-05
265      KHSRP         2     HepG2     KHSRP_2  5.659156e-03
266      KHSRP         3     HepG2     KHSRP_3  3.042525e-03
267      KHSRP         4     HepG2     KHSRP_4  8.749684e-04
268      KHSRP         5     HepG2     KHSRP_5  4.432605e-03
269      KHSRP         6     HepG2     KHSRP_6  6.752918e-04
270      LARP4         1     HepG2     LARP4_1  3.039195e-03
271      LARP4         2     HepG2     LARP4_2  5.404945e-03
272      LARP4         3     HepG2     LARP4_3  1.605393e-02
273      LARP4         4     HepG2     LARP4_4  2.724869e-02
274      LARP4         5     HepG2     LARP4_5  1.036272e-02
275      LARP4         6     HepG2     LARP4_6  2.225036e-03
276      LARP7         1     HepG2     LARP7_1  1.054939e-04
277      LARP7         2     HepG2     LARP7_2  0.000000e+00
278      LARP7         3     HepG2     LARP7_3  8.102345e-06
279      LARP7         4     HepG2     LARP7_4  0.000000e+00
280      LARP7         5     HepG2     LARP7_5  1.695466e-04
281      LARP7         6     HepG2     LARP7_6  0.000000e+00
282     LIN28B         1     HepG2    LIN28B_1  4.743681e-04
283     LIN28B         2     HepG2    LIN28B_2  7.791403e-04
284     LIN28B         3     HepG2    LIN28B_3  2.092596e-02
285     LIN28B         4     HepG2    LIN28B_4  2.584717e-02
286     LIN28B         5     HepG2    LIN28B_5  1.210218e-03
287     LIN28B         6     HepG2    LIN28B_6  6.799364e-03
288      LSM11         1     HepG2     LSM11_1  8.543347e-05
289      LSM11         2     HepG2     LSM11_2  1.166830e-03
290      LSM11         3     HepG2     LSM11_3  5.488878e-06
291      LSM11         4     HepG2     LSM11_4  8.521618e-05
292      LSM11         5     HepG2     LSM11_5  1.924416e-04
293      LSM11         6     HepG2     LSM11_6  1.700210e-03
294      MATR3         1     HepG2     MATR3_1  0.000000e+00
295      MATR3         2     HepG2     MATR3_2  0.000000e+00
296      MATR3         3     HepG2     MATR3_3  5.695566e-04
297      MATR3         4     HepG2     MATR3_4  0.000000e+00
298      MATR3         5     HepG2     MATR3_5  9.079564e-06
299      MATR3         6     HepG2     MATR3_6  0.000000e+00
300      NCBP2         1     HepG2     NCBP2_1  1.077437e-03
301      NCBP2         2     HepG2     NCBP2_2  1.649304e-02
302      NCBP2         3     HepG2     NCBP2_3  3.046985e-03
303      NCBP2         4     HepG2     NCBP2_4  0.000000e+00
304      NCBP2         5     HepG2     NCBP2_5  2.467076e-03
305      NCBP2         6     HepG2     NCBP2_6  2.829026e-04
306       NIP7         1     HepG2      NIP7_1  8.564811e-05
307       NIP7         2     HepG2      NIP7_2  4.945452e-04
308       NIP7         3     HepG2      NIP7_3  0.000000e+00
309       NIP7         4     HepG2      NIP7_4  0.000000e+00
310       NIP7         5     HepG2      NIP7_5  4.898050e-04
311       NIP7         6     HepG2      NIP7_6  0.000000e+00
312       NKRF         1     HepG2      NKRF_1  1.171954e-04
313       NKRF         2     HepG2      NKRF_2  4.412900e-03
314       NKRF         3     HepG2      NKRF_3  2.276096e-03
315       NKRF         4     HepG2      NKRF_4  0.000000e+00
316       NKRF         5     HepG2      NKRF_5  0.000000e+00
317       NKRF         6     HepG2      NKRF_6  0.000000e+00
318      NOL12         1     HepG2     NOL12_1  7.952206e-06
319      NOL12         2     HepG2     NOL12_2  0.000000e+00
320      NOL12         3     HepG2     NOL12_3  0.000000e+00
321      NOL12         4     HepG2     NOL12_4  0.000000e+00
322      NOL12         5     HepG2     NOL12_5  2.741300e-06
323      NOL12         6     HepG2     NOL12_6  0.000000e+00
324      NOLC1         1     HepG2     NOLC1_1  2.112470e-04
325      NOLC1         2     HepG2     NOLC1_2  3.740408e-04

In [ ]:
investigator.plot_differential_splicing_types()

In [ ]:
investigator.plot_differential_ranks()

In [ ]:
investigator.plot_differential_ratios()

In [ ]:
investigator.plot_matching_differential_ratios_scatterplot()

<h1 style="color: teal; font-weight: bold; font-size: 48px;">Metric w/ Regulatory Explanation</h1>

* `Global SHAP`
* `ElasticNet coefficients`
* `Total Binding`
* `# Differential Events`

In [ ]:
investigator.plot_feature_metric_summary_table()