# Ayan's `XGBDT SHAP` Values Analysis

## Purpose: 

{TODO}

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

import glob

import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
ayan_shap_folder = "/project/PlatigLab/data/collaborators/BWH/3_XGBDT_SHAP_data_2024_07/"
cell_lines = ["K562", "HepG2"]
distance_thresholds = list({file.split("/")[-1].split("-")[1] for file in glob.glob(f"{ayan_shap_folder}/**/*data.dat", recursive=True)})
best_performing_distance_threshold=100

shap_files = sorted(glob.glob(f"{ayan_shap_folder}/**/*data.dat", recursive=True))

actual_psi_column_name = "target"
predicted_psi_column_name = "psi_hat"

In [17]:
rbp_ppi=pd.read_excel("../../../inputs/RBP-RBP_PPI/lang_et_al_rec-y2h_screening_results.xlsx")
# rbp_ppi = rbp_ppi[(rbp_ppi["sumIS"]>=7.1) & (rbp_ppi["UniProt species A"]=="HUMAN") & (rbp_ppi["UniProt species B"]=="HUMAN")]

rbp_ppi = rbp_ppi[(rbp_ppi["sumIS"]>=7.1)]


rbp_ppi.shape
rbp_ppi.head()

rbp_ppi["Found in both orientations "].value_counts(normalize=True)

(2416, 57)

,Protein A,Protein B,UniProt species A,UniProt species B,UniProt accessions A,UniProt accessions B,UniProt IDs A,UniProt IDs B,Times detected (RIS > 0),avgIS,sumIS,Found in both orientations,H47_avgIS,H47_sumIS,H47_found in both orientations,H47_times detected (RIS > 0),"Biogrid_all direct evidence (Y2H, reconstituted complex, structure)",Biogrid_all,Hippie,HuRI,Known interaction,Protein A has known interactions,Protein B has known interactions,HPA nuclear A,HPA nuclear B,HPA cytoplasmic A,HPA cytoplasmic B,HPA main locations A,HPA additional locations A,HPA main locations B,HPA additional locations B,HPA shared locations,Youn et al. 2018 (PMID 29395067),NanoBRET,NanoBRET MBU,NanoBRET MBU std,ENCODE eCLIP data A,ENCODE eCLIP data B,ENCODE eCLIP binding sites A,ENCODE eCLIP binding sites B,Jaccard index,Cobinding prob p(A|B),Cobinding prob p(B|A),Cobinding prob p(A|B) (≤54 nt),Cobinding prob p(B|A) (≤54 nt),Close binding events (≤54 nt) A vs. B,Fraction of close binding events A vs. B,Fraction of close binding events in random data A vs. B,Ratio of fractions A vs. B,Resampling p-value A vs. B,Resampling Wilcoxon p-value A vs. B,Close binding events (≤54 nt) B vs. A,Fraction of close binding events B vs. A,Fraction of close binding events in random data B vs. A,Ratio of fractions B vs. A,Resampling p-value B vs. A,Resampling Wilcoxon p-value B vs. A
0,CTBP1,RBM14,HUMAN,MOUSE,Q13363,Q8C2Q3,CTBP1_HUMAN,RBM14_MOUSE,10,8.41,17.19,1,NaN,NaN,NaN,NaN,1,1,1,0,1,1,1,1.0,1.0,0.0,0.0,Nucleoplasm,NaN,Nuclear speckles,NaN,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RBM14,CPSF6,MOUSE,MOUSE,Q8C2Q3,Q6NVF9,RBM14_MOUSE,CPSF6_MOUSE,11,13.98,16.03,0,NaN,NaN,NaN,NaN,0,0,0,0,0,1,0,1.0,1.0,0.0,0.0,Nuclear speckles,NaN,Nuclear speckles;Nucleoplasm,NaN,Nuclear speckles,0,NaN,NaN,NaN,0,1,0,791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PTBP1,PTBP2,HUMAN,HUMAN,P26599,Q9UKA9,PTBP1_HUMAN,PTBP2_HUMAN,8,4.49,15.73,1,0.00,5.47,0.0,5.0,0,0,0,0,0,0,0,1.0,1.0,0.0,0.0,Nucleoplasm,NaN,Nucleoplasm,NaN,Nucleoplasm,0,pos,13.34,0.94,1,0,16175,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SF1,EWSR1,HUMAN,MOUSE,Q15637,Q61545,SF01_HUMAN,EWS_MOUSE,3,3.29,15.50,0,7.17,11.66,0.0,3.0,1,1,1,0,1,1,1,1.0,1.0,0.0,0.0,Nucleoplasm,NaN,Nucleoplasm,Nucleoli,Nucleoplasm,0,NaN,NaN,NaN,0,1,0,8788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SRSF11,SRPK2,HUMAN,HUMAN,Q05519,P78362,SRS11_HUMAN,SRPK2_HUMAN,10,9.52,14.79,1,2.32,5.06,0.0,5.0,0,1,1,1,1,1,1,1.0,1.0,0.0,1.0,Nuclear speckles,NaN,Cytosol;Nucleoplasm,NaN,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Found in both orientations
0    0.93957
1    0.06043
Name: proportion, dtype: float64

## Despite larger distance thresholds having lower `R^2` performance, do they do better at predicting non-0/1 `PSI`?

In [3]:

# for cell_line in cell_lines: 
    
#     for threshold in distance_thresholds: 
#         f"{cell_line} {threshold}"
        
#         files = [ file for file in shap_files if f"{cell_line}-{threshold}-" in file and "-train-" not in file ]
#         assert len(files)==2, [file.split("/")[-1] for file in files]        
        

#         plt.figure(dpi=100, figsize=(10,10))
        
        
#         df = [pd.read_csv(file, sep=",", usecols=[actual_psi_column_name, predicted_psi_column_name]) for file in files if "-train-" not in file]
        
#         df = pd.concat(df)
        
# #         sns.scatterplot(
# #             df, 
# #             x="target", 
# #             y="psi_hat", 
# #             size=0.00000000000001
        
# #         )

#         plt.hist2d(
        
#             df["target"].to_list(), 
#             df["psi_hat"].to_list(), 
#             bins=10
            
#         )
          
#         plt.show()

## Do `RBP PPI pairs` have similar `SHAP` in places where they bind together vs. don’t bind?

In [4]:
data_dict = {}

for cell_line in cell_lines: 
    data_dict[cell_line] = {}
    
    f"{cell_line}"

    files = [ file for file in shap_files if f"{cell_line}-{best_performing_distance_threshold}-" in file and "-train-" not in file ]
    assert len(files)==2, [file.split("/")[-1] for file in files]    

    df = [ pd.read_csv(file, sep=",") for file in files ]

    data_dict[cell_line] = pd.concat(df)

'K562'

'HepG2'

In [7]:
def get_interacting_rbp_columns(df, rbp_ppi,

,AARS_5_left,AATF_5_left,ABCF1_5_left,ADAT1_5_left,AGGF1_5_left,AKAP1_5_left,AKAP8L_5_left,APEX1_5_left,APOBEC3C_5_left,AQR_5_left,BUD13_5_left,CPEB4_5_left,CPSF6_5_left,CSTF2T_5_left,DDX1_5_left,DDX21_5_left,DDX24_5_left,DDX3X_5_left,DDX42_5_left,DDX43_5_left,DDX47_5_left,DDX51_5_left,DDX52_5_left,DDX55_5_left,DDX6_5_left,DGCR8_5_left,DHX30_5_left,DROSHA_5_left,EEF2_5_left,EFTUD2_5_left,EIF3G_5_left,EIF4E_5_left,EIF4G2_5_left,ELAC2_5_left,ELAVL1_5_left,EWSR1_5_left,EXOSC10_5_left,EXOSC5_5_left,FAM120A_5_left,FASTKD2_5_left,FMR1_5_left,FTO_5_left,FUS_5_left,FXR1_5_left,FXR2_5_left,GARS_5_left,GEMIN5_5_left,GNL3_5_left,GPKOW_5_left,GRWD1_5_left,GTF2F1_5_left,HLTF_5_left,HNRNPA1_5_left,HNRNPC_5_left,HNRNPK_5_left,HNRNPL_5_left,HNRNPM_5_left,HNRNPU_5_left,HNRNPUL1_5_left,IGF2BP1_5_left,IGF2BP2_5_left,ILF3_5_left,KHDRBS1_5_left,KHSRP_5_left,LARP4_5_left,LARP7_5_left,LIN28B_5_left,LSM11_5_left,MATR3_5_left,MBNL1_5_left,METAP2_5_left,METTL1_5_left,MORC2_5_left,MTPAP_5_left,NCBP2_5_left,NIPBL_5_left,NOLC1_5_left,NONO_5_left,NPM1_5_left,NSUN2_5_left,PABPC4_5_left,PCBP1_5_left,PHF6_5_left,PPIL4_5_left,PRPF8_5_left,PTBP1_5_left,PUM1_5_left,PUM2_5_left,PUS1_5_left,QKI_5_left,RBFOX2_5_left,RBM15_5_left,RBM22_5_left,RNF187_5_left,RPS10_5_left,RPS11_5_left,RPS3_5_left,RPS6_5_left,RYBP_5_left,SAFB_5_left,SAFB2_5_left,SBDS_5_left,SDAD1_5_left,SERBP1_5_left,SF3B1_5_left,SF3B4_5_left,SLBP_5_left,SLTM_5_left,SMNDC1_5_left,SND1_5_left,SRSF1_5_left,SRSF7_5_left,SRSF9_5_left,SSB_5_left,SUPV3L1_5_left,TAF15_5_left,TARDBP_5_left,TBRG4_5_left,TIA1_5_left,TRA2A_5_left,TROVE2_5_left,U2AF1_5_left,U2AF2_5_left,UCHL5_5_left,UPF1_5_left,UTP18_5_left,UTP3_5_left,WDR3_5_left,WDR43_5_left,WRN_5_left,XRCC6_5_left,XRN2_5_left,YBX3_5_left,YWHAG_5_left,ZC3H11A_5_left,ZC3H8_5_left,ZNF622_5_left,ZNF800_5_left,ZRANB2_5_left,AARS_5_right,AATF_5_right,ABCF1_5_right,ADAT1_5_right,AGGF1_5_right,AKAP1_5_right,AKAP8L_5_right,APEX1_5_right,APOBEC3C_5_right,AQR_5_right,BUD13_5_right,CPEB4_5_right,CPSF6_5_right,CSTF2T_5_right,DDX1_5_right,DDX21_5_right,DDX24_5_right,DDX3X_5_right,DDX42_5_right,DDX43_5_right,DDX47_5_right,DDX51_5_right,DDX52_5_right,DDX55_5_right,DDX6_5_right,DGCR8_5_right,DHX30_5_right,DROSHA_5_right,EEF2_5_right,EFTUD2_5_right,EIF3G_5_right,EIF4E_5_right,EIF4G2_5_right,ELAC2_5_right,ELAVL1_5_right,EWSR1_5_right,EXOSC10_5_right,EXOSC5_5_right,FAM120A_5_right,FASTKD2_5_right,FMR1_5_right,FTO_5_right,FUS_5_right,FXR1_5_right,FXR2_5_right,GARS_5_right,GEMIN5_5_right,GNL3_5_right,GPKOW_5_right,GRWD1_5_right,GTF2F1_5_right,HLTF_5_right,HNRNPA1_5_right,HNRNPC_5_right,HNRNPK_5_right,HNRNPL_5_right,HNRNPM_5_right,HNRNPU_5_right,HNRNPUL1_5_right,IGF2BP1_5_right,IGF2BP2_5_right,ILF3_5_right,KHDRBS1_5_right,KHSRP_5_right,LARP4_5_right,LARP7_5_right,LIN28B_5_right,LSM11_5_right,MATR3_5_right,MBNL1_5_right,METAP2_5_right,METTL1_5_right,MORC2_5_right,MTPAP_5_right,NCBP2_5_right,NIPBL_5_right,NOLC1_5_right,NONO_5_right,NPM1_5_right,NSUN2_5_right,PABPC4_5_right,PCBP1_5_right,PHF6_5_right,PPIL4_5_right,PRPF8_5_right,PTBP1_5_right,PUM1_5_right,PUM2_5_right,PUS1_5_right,QKI_5_right,RBFOX2_5_right,RBM15_5_right,RBM22_5_right,RNF187_5_right,RPS10_5_right,RPS11_5_right,RPS3_5_right,RPS6_5_right,RYBP_5_right,SAFB_5_right,SAFB2_5_right,SBDS_5_right,SDAD1_5_right,SERBP1_5_right,SF3B1_5_right,SF3B4_5_right,SLBP_5_right,SLTM_5_right,SMNDC1_5_right,SND1_5_right,SRSF1_5_right,SRSF7_5_right,SRSF9_5_right,SSB_5_right,SUPV3L1_5_right,TAF15_5_right,TARDBP_5_right,TBRG4_5_right,TIA1_5_right,TRA2A_5_right,TROVE2_5_right,U2AF1_5_right,U2AF2_5_right,UCHL5_5_right,UPF1_5_right,UTP18_5_right,UTP3_5_right,WDR3_5_right,WDR43_5_right,WRN_5_right,XRCC6_5_right,XRN2_5_right,YBX3_5_right,YWHAG_5_right,ZC3H11A_5_right,ZC3H8_5_right,ZNF622_5_right,ZNF800_5_right,ZRANB2_5_right,AARS_center_left,AATF_center_left,ABCF1_center_left,ADAT1_center_left,AGGF1_center_left,AKAP1_center_left,AKAP8L_center_left,APEX1_center_left,APOBEC3C_center_left,AQR_center_left,BUD13_center_left,CPEB4_center_left,CPSF6_center_left,CSTF2T_center_left,DDX1_center_left,DDX21_center_left,DDX24_center_left,DDX3X_center_left,DDX42_center_left,DDX43_center_left,DDX47_center_left,DDX51_center_left,DDX52_center_left,DDX55_center_left,DDX6_center_left,DGCR8_center_left,DHX30_center_left,DROSHA_center_left,EEF2_center_left,EFTUD2_center_left,EIF3G_center_left,EIF4E_center_left,EIF4G2_center_left,ELAC2_center_left,ELAVL1_center_left,EWSR1_center_left,EXOSC10_center_left,EXOSC5_center_left,FAM120A_center_left,FASTKD2_center_left,FMR1_center_left,FTO_center_left,FUS_center_left,FXR1_center_left,FXR2_center_left,GARS_center_left,GEMIN5_center_left,GNL3_center_left,GPKOW_center_left,GRWD1_center_left,GTF2F1_center_left,HLTF_center_left,HNRNPA1_center_left,HNRNPC_center_left,HNRNPK_center_left,HNRNPL_center_left,HNRNPM_center_left,HNRNPU_center_left,HNRNPUL1_center_left,IGF2BP1_center_left,IGF2BP2_center_left,ILF3_center_left,KHDRBS1_center_left,KHSRP_center_left,LARP4_center_left,LARP7_center_left,LIN28B_center_left,LSM11_center_left,MATR3_center_left,MBNL1_center_left,METAP2_center_left,METTL1_center_left,MORC2_center_left,MTPAP_center_left,NCBP2_center_left,NIPBL_center_left,NOLC1_center_left,NONO_center_left,NPM1_center_left,NSUN2_center_left,PABPC4_center_left,PCBP1_center_left,PHF6_center_left,PPIL4_center_left,PRPF8_center_left,PTBP1_center_left,PUM1_center_left,PUM2_center_left,PUS1_center_left,QKI_center_left,RBFOX2_center_left,RBM15_center_left,RBM22_center_left,RNF187_center_left,RPS10_center_left,RPS11_center_left,RPS3_center_left,RPS6_center_left,RYBP_center_left,SAFB_center_left,SAFB2_center_left,SBDS_center_left,SDAD1_center_left,SERBP1_center_left,SF3B1_center_left,SF3B4_center_left,SLBP_center_left,SLTM_center_left,SMNDC1_center_left,SND1_center_left,SRSF1_center_left,SRSF7_center_left,SRSF9_center_left,SSB_center_left,SUPV3L1_center_left,TAF15_center_left,TARDBP_center_left,TBRG4_center_left,TIA1_center_left,TRA2A_center_left,TROVE2_center_left,U2AF1_center_left,U2AF2_center_left,UCHL5_center_left,UPF1_center_left,UTP18_center_left,UTP3_center_left,WDR3_center_left,WDR43_center_left,WRN_center_left,XRCC6_center_left,XRN2_center_left,YBX3_center_left,YWHAG_center_left,ZC3H11A_center_left,ZC3H8_center_left,ZNF622_center_left,ZNF800_center_left,ZRANB2_center_left,AARS_center_right,AATF_center_right,ABCF1_center_right,ADAT1_center_right,AGGF1_center_right,AKAP1_center_right,AKAP8L_center_right,APEX1_center_right,APOBEC3C_center_right,AQR_center_right,BUD13_center_right,CPEB4_center_right,CPSF6_center_right,CSTF2T_center_right,DDX1_center_right,DDX21_center_right,DDX24_center_right,DDX3X_center_right,DDX42_center_right,DDX43_center_right,DDX47_center_right,DDX51_center_right,DDX52_center_right,DDX55_center_right,DDX6_center_right,DGCR8_center_right,DHX30_center_right,DROSHA_center_right,EEF2_center_right,EFTUD2_center_right,EIF3G_center_right,EIF4E_center_right,EIF4G2_center_right,ELAC2_center_right,ELAVL1_center_right,EWSR1_center_right,EXOSC10_center_right,EXOSC5_center_right,FAM120A_center_right,FASTKD2_center_right,FMR1_center_right,FTO_center_right,FUS_center_right,FXR1_center_right,FXR2_center_right,GARS_center_right,GEMIN5_center_right,GNL3_center_right,GPKOW_center_right,GRWD1_center_right,GTF2F1_center_right,HLTF_center_right,HNRNPA1_center_right,HNRNPC_center_right,HNRNPK_center_right,HNRNPL_center_right,HNRNPM_center_right,HNRNPU_center_right,HNRNPUL1_center_right,IGF2BP1_center_right,IGF2BP2_center_right,ILF3_center_right,KHDRBS1_center_right,KHSRP_center_right,LARP4_center_right,LARP7_center_right,LIN28B_center_right,LSM11_center_right,MATR3_center_right,MBNL1_center_right,METAP2_center_right,METTL1_center_right,MORC2_center_right,MTPAP_center_right,NCBP2_center_right,NIPBL_center_right,NOLC1_center_right,NONO_center_right,NPM1_center_right,NSUN2_center_right,PABPC4_center_right,PCBP1_center_right,PHF6_center_right,PPIL4_center_right,PRPF8_center_right,PTBP1_center_right,PUM1_center_right,PUM2_center_right,PUS1_center_right,QKI_center_right,RBFOX2_center_right,RBM15_center_right,RBM22_center_right,RNF187_center_right,RPS10_center_right,RPS11_center_right,RPS3_center_right,RPS6_center_right,RYBP_center_right,SAFB_center_right,SAFB2_center_right,SBDS_center_right,SDAD1_center_right,SERBP1_center_right,SF3B1_center_right,SF3B4_center_right,SLBP_center_right,SLTM_center_right,SMNDC1_center_right,SND1_center_right,SRSF1_center_right,SRSF7_center_right,SRSF9_center_right,SSB_center_right,SUPV3L1_center_right,TAF15_center_right,TARDBP_center_right,TBRG4_center_right,TIA1_center_right,TRA2A_center_right,TROVE2_center_right,U2AF1_center_right,U2AF2_center_right,UCHL5_center_right,UPF1_center_right,UTP18_center_right,UTP3_center_right,WDR3_center_right,WDR43_center_right,WRN_center_right,XRCC6_center_right,XRN2_center_right,YBX3_center_right,YWHAG_center_right,ZC3H11A_center_right,ZC3H8_center_right,ZNF622_center_right,ZNF800_center_right,ZRANB2_center_right,AARS_3_left,AATF_3_left,ABCF1_3_left,ADAT1_3_left,AGGF1_3_left,AKAP1_3_left,AKAP8L_3_left,APEX1_3_left,APOBEC3C_3_left,AQR_3_left,BUD13_3_left,CPEB4_3_left,CPSF6_3_left,CSTF2T_3_left,DDX1_3_left,DDX21_3_left,DDX24_3_left,DDX3X_3_left,DDX42_3_left,DDX43_3_left,DDX47_3_left,DDX51_3_left,DDX52_3_left,DDX55_3_left,DDX6_3_left,DGCR8_3_left,DHX30_3_left,DROSHA_3_left,EEF2_3_left,EFTUD2_3_left,EIF3G_3_left,EIF4E_3_left,EIF4G2_3_left,ELAC2_3_left,ELAVL1_3_left,EWSR1_3_left,EXOSC10_3_left,EXOSC5_3_left,FAM120A_3_left,FASTKD2_3_left,FMR1_3_left,FTO_3_left,FUS_3_left,FXR1_3_left,FXR2_3_left,GARS_3_left,GEMIN5_3_left,GNL3_3_left,GPKOW_3_left,GRWD1_3_left,GTF2F1_3_left,HLTF_3_left,HNRNPA1_3_left,HNRNPC_3_left,HNRNPK_3_left,HNRNPL_3_left,HNRNPM_3_left,HNRNPU_3_left,HNRNPUL1_3_left,IGF2BP1_3_left,IGF2BP2_3_left,ILF3_3_left,KHDRBS1_3_left,KHSRP_3_left,LARP4_3_left,LARP7_3_left,LIN28B_3_left,LSM11_3_left,MATR3_3_left,MBNL1_3_left,METAP2_3_left,METTL1_3_left,MORC2_3_left,MTPAP_3_left,NCBP2_3_left,NIPBL_3_left,NOLC1_3_left,NONO_3_left,NPM1_3_left,NSUN2_3_left,PABPC4_3_left,PCBP1_3_left,PHF6_3_left,PPIL4_3_left,PRPF8_3_left,PTBP1_3_left,PUM1_3_left,PUM2_3_left,PUS1_3_left,QKI_3_left,RBFOX2_3_left,RBM15_3_left,RBM22_3_left,RNF187_3_left,RPS10_3_left,RPS11_3_left,RPS3_3_left,RPS6_3_left,RYBP_3_left,SAFB_3_left,SAFB2_3_left,SBDS_3_left,SDAD1_3_left,SERBP1_3_left,SF3B1_3_left,SF3B4_3_left,SLBP_3_left,SLTM_3_left,SMNDC1_3_left,SND1_3_left,SRSF1_3_left,SRSF7_3_left,SRSF9_3_left,SSB_3_left,SUPV3L1_3_left,TAF15_3_left,TARDBP_3_left,TBRG4_3_left,TIA1_3_left,TRA2A_3_left,TROVE2_3_left,U2AF1_3_left,U2AF2_3_left,UCHL5_3_left,UPF1_3_left,UTP18_3_left,UTP3_3_left,WDR3_3_left,WDR43_3_left,WRN_3_left,XRCC6_3_left,XRN2_3_left,YBX3_3_left,YWHAG_3_left,ZC3H11A_3_left,ZC3H8_3_left,ZNF622_3_left,ZNF800_3_left,ZRANB2_3_left,AARS_3_right,AATF_3_right,ABCF1_3_right,ADAT1_3_right,AGGF1_3_right,AKAP1_3_right,AKAP8L_3_right,APEX1_3_right,APOBEC3C_3_right,AQR_3_right,BUD13_3_right,CPEB4_3_right,CPSF6_3_right,CSTF2T_3_right,DDX1_3_right,DDX21_3_right,DDX24_3_right,DDX3X_3_right,DDX42_3_right,DDX43_3_right,DDX47_3_right,DDX51_3_right,DDX52_3_right,DDX55_3_right,DDX6_3_right,DGCR8_3_right,DHX30_3_right,DROSHA_3_right,EEF2_3_right,EFTUD2_3_right,EIF3G_3_right,EIF4E_3_right,EIF4G2_3_right,ELAC2_3_right,ELAVL1_3_right,EWSR1_3_right,EXOSC10_3_right,EXOSC5_3_right,FAM120A_3_right,FASTKD2_3_right,FMR1_3_right,FTO_3_right,FUS_3_right,FXR1_3_right,FXR2_3_right,GARS_3_right,GEMIN5_3_right,GNL3_3_right,GPKOW_3_right,GRWD1_3_right,GTF2F1_3_right,HLTF_3_right,HNRNPA1_3_right,HNRNPC_3_right,HNRNPK_3_right,HNRNPL_3_right,HNRNPM_3_right,HNRNPU_3_right,HNRNPUL1_3_right,IGF2BP1_3_right,IGF2BP2_3_right,ILF3_3_right,KHDRBS1_3_right,KHSRP_3_right,LARP4_3_right,LARP7_3_right,LIN28B_3_right,LSM11_3_right,MATR3_3_right,MBNL1_3_right,METAP2_3_right,METTL1_3_right,MORC2_3_right,MTPAP_3_right,NCBP2_3_right,NIPBL_3_right,NOLC1_3_right,NONO_3_right,NPM1_3_right,NSUN2_3_right,PABPC4_3_right,PCBP1_3_right,PHF6_3_right,PPIL4_3_right,PRPF8_3_right,PTBP1_3_right,PUM1_3_right,PUM2_3_right,PUS1_3_right,QKI_3_right,RBFOX2_3_right,RBM15_3_right,RBM22_3_right,RNF187_3_right,RPS10_3_right,RPS11_3_right,RPS3_3_right,RPS6_3_right,RYBP_3_right,SAFB_3_right,SAFB2_3_right,SBDS_3_right,SDAD1_3_right,SERBP1_3_right,SF3B1_3_right,SF3B4_3_right,SLBP_3_right,SLTM_3_right,SMNDC1_3_right,SND1_3_right,SRSF1_3_right,SRSF7_3_right,SRSF9_3_right,SSB_3_right,SUPV3L1_3_right,TAF15_3_right,TARDBP_3_right,TBRG4_3_right,TIA1_3_right,TRA2A_3_right,TROVE2_3_right,U2AF1_3_right,U2AF2_3_right,UCHL5_3_right,UPF1_3_right,UTP18_3_right,UTP3_3_right,WDR3_3_right,WDR43_3_right,WRN_3_right,XRCC6_3_right,XRN2_3_right,YBX3_3_right,YWHAG_3_right,ZC3H11A_3_right,ZC3H8_3_right,ZNF622_3_right,ZNF800_3_right,ZRANB2_3_right,target,psi_hat,AARS_5_left_shap,AATF_5_left_shap,ABCF1_5_left_shap,ADAT1_5_left_shap,AGGF1_5_left_shap,AKAP1_5_left_shap,AKAP8L_5_left_shap,APEX1_5_left_shap,APOBEC3C_5_left_shap,AQR_5_left_shap,BUD13_5_left_shap,CPEB4_5_left_shap,CPSF6_5_left_shap,CSTF2T_5_left_shap,DDX1_5_left_shap,DDX21_5_left_shap,DDX24_5_left_shap,DDX3X_5_left_shap,DDX42_5_left_shap,DDX43_5_left_shap,DDX47_5_left_shap,DDX51_5_left_shap,DDX52_5_left_shap,DDX55_5_left_shap,DDX6_5_left_shap,DGCR8_5_left_shap,DHX30_5_left_shap,DROSHA_5_left_shap,EEF2_5_left_shap,EFTUD2_5_left_shap,EIF3G_5_left_shap,EIF4E_5_left_shap,EIF4G2_5_left_shap,ELAC2_5_left_shap,ELAVL1_5_left_shap,EWSR1_5_left_shap,EXOSC10_5_left_shap,EXOSC5_5_left_shap,FAM120A_5_left_shap,FASTKD2_5_left_shap,FMR1_5_left_shap,FTO_5_left_shap,FUS_5_left_shap,FXR1_5_left_shap,FXR2_5_left_shap,GARS_5_left_shap,GEMIN5_5_left_shap,GNL3_5_left_shap,GPKOW_5_left_shap,GRWD1_5_left_shap,GTF2F1_5_left_shap,HLTF_5_left_shap,HNRNPA1_5_left_shap,HNRNPC_5_left_shap,HNRNPK_5_left_shap,HNRNPL_5_left_shap,HNRNPM_5_left_shap,HNRNPU_5_left_shap,HNRNPUL1_5_left_shap,IGF2BP1_5_left_shap,IGF2BP2_5_left_shap,ILF3_5_left_shap,KHDRBS1_5_left_shap,KHSRP_5_left_shap,LARP4_5_left_shap,LARP7_5_left_shap,LIN28B_5_left_shap,LSM11_5_left_shap,MATR3_5_left_shap,MBNL1_5_left_shap,METAP2_5_left_shap,METTL1_5_left_shap,MORC2_5_left_shap,MTPAP_5_left_shap,NCBP2_5_left_shap,NIPBL_5_left_shap,NOLC1_5_left_shap,NONO_5_left_shap,NPM1_5_left_shap,NSUN2_5_left_shap,PABPC4_5_left_shap,PCBP1_5_left_shap,PHF6_5_left_shap,PPIL4_5_left_shap,PRPF8_5_left_shap,PTBP1_5_left_shap,PUM1_5_left_shap,PUM2_5_left_shap,PUS1_5_left_shap,QKI_5_left_shap,RBFOX2_5_left_shap,RBM15_5_left_shap,RBM22_5_left_shap,RNF187_5_left_shap,RPS10_5_left_shap,RPS11_5_left_shap,RPS3_5_left_shap,RPS6_5_left_shap,RYBP_5_left_shap,SAFB_5_left_shap,SAFB2_5_left_shap,SBDS_5_left_shap,SDAD1_5_left_shap,SERBP1_5_left_shap,SF3B1_5_left_shap,SF3B4_5_left_shap,SLBP_5_left_shap,SLTM_5_left_shap,SMNDC1_5_left_shap,SND1_5_left_shap,SRSF1_5_left_shap,SRSF7_5_left_shap,SRSF9_5_left_shap,SSB_5_left_shap,SUPV3L1_5_left_shap,TAF15_5_left_shap,TARDBP_5_left_shap,TBRG4_5_left_shap,TIA1_5_left_shap,TRA2A_5_left_shap,TROVE2_5_left_shap,U2AF1_5_left_shap,U2AF2_5_left_shap,UCHL5_5_left_shap,UPF1_5_left_shap,UTP18_5_left_shap,UTP3_5_left_shap,WDR3_5_left_shap,WDR43_5_left_shap,WRN_5_left_shap,XRCC6_5_left_shap,XRN2_5_left_shap,YBX3_5_left_shap,YWHAG_5_left_shap,ZC3H11A_5_left_shap,ZC3H8_5_left_shap,ZNF622_5_left_shap,ZNF800_5_left_shap,ZRANB2_5_left_shap,AARS_5_right_shap,AATF_5_right_shap,ABCF1_5_right_shap,ADAT1_5_right_shap,AGGF1_5_right_shap,AKAP1_5_right_shap,AKAP8L_5_right_shap,APEX1_5_right_shap,APOBEC3C_5_right_shap,AQR_5_right_shap,BUD13_5_right_shap,CPEB4_5_right_shap,CPSF6_5_right_shap,CSTF2T_5_right_shap,DDX1_5_right_shap,DDX21_5_right_shap,DDX24_5_right_shap,DDX3X_5_right_shap,DDX42_5_right_shap,DDX43_5_right_shap,DDX47_5_right_shap,DDX51_5_right_shap,DDX52_5_right_shap,DDX55_5_right_shap,DDX6_5_right_shap,DGCR8_5_right_shap,DHX30_5_right_shap,DROSHA_5_right_shap,EEF2_5_right_shap,EFTUD2_5_right_shap,EIF3G_5_right_shap,EIF4E_5_right_shap,EIF4G2_5_right_shap,ELAC2_5_right_shap,ELAVL1_5_right_shap,EWSR1_5_right_shap,EXOSC10_5_right_shap,EXOSC5_5_right_shap,FAM120A_5_right_shap,FASTKD2_5_right_shap,FMR1_5_right_shap,FTO_5_right_shap,FUS_5_right_shap,FXR1_5_right_shap,FXR2_5_right_shap,GARS_5_right_shap,GEMIN5_5_right_shap,GNL3_5_right_shap,GPKOW_5_right_shap,GRWD1_5_right_shap,GTF2F1_5_right_shap,HLTF_5_right_shap,HNRNPA1_5_right_shap,HNRNPC_5_right_shap,HNRNPK_5_right_shap,HNRNPL_5_right_shap,HNRNPM_5_right_shap,HNRNPU_5_right_shap,HNRNPUL1_5_right_shap,IGF2BP1_5_right_shap,IGF2BP2_5_right_shap,ILF3_5_right_shap,KHDRBS1_5_right_shap,KHSRP_5_right_shap,LARP4_5_right_shap,LARP7_5_right_shap,LIN28B_5_right_shap,LSM11_5_right_shap,MATR3_5_right_shap,MBNL1_5_right_shap,METAP2_5_right_shap,METTL1_5_right_shap,MORC2_5_right_shap,MTPAP_5_right_shap,NCBP2_5_right_shap,NIPBL_5_right_shap,NOLC1_5_right_shap,NONO_5_right_shap,NPM1_5_right_shap,NSUN2_5_right_shap,PABPC4_5_right_shap,PCBP1_5_right_shap,PHF6_5_right_shap,PPIL4_5_right_shap,PRPF8_5_right_shap,PTBP1_5_right_shap,PUM1_5_right_shap,PUM2_5_right_shap,PUS1_5_right_shap,QKI_5_right_shap,RBFOX2_5_right_shap,RBM15_5_right_shap,RBM22_5_right_shap,RNF187_5_right_shap,RPS10_5_right_shap,RPS11_5_right_shap,RPS3_5_right_shap,RPS6_5_right_shap,RYBP_5_right_shap,SAFB_5_right_shap,SAFB2_5_right_shap,SBDS_5_right_shap,SDAD1_5_right_shap,SERBP1_5_right_shap,SF3B1_5_right_shap,SF3B4_5_right_shap,SLBP_5_right_shap,SLTM_5_right_shap,SMNDC1_5_right_shap,SND1_5_right_shap,SRSF1_5_right_shap,SRSF7_5_right_shap,SRSF9_5_right_shap,SSB_5_right_shap,SUPV3L1_5_right_shap,TAF15_5_right_shap,TARDBP_5_right_shap,TBRG4_5_right_shap,TIA1_5_right_shap,TRA2A_5_right_shap,TROVE2_5_right_shap,U2AF1_5_right_shap,U2AF2_5_right_shap,UCHL5_5_right_shap,UPF1_5_right_shap,UTP18_5_right_shap,UTP3_5_right_shap,WDR3_5_right_shap,WDR43_5_right_shap,WRN_5_right_shap,XRCC6_5_right_shap,XRN2_5_right_shap,YBX3_5_right_shap,YWHAG_5_right_shap,ZC3H11A_5_right_shap,ZC3H8_5_right_shap,ZNF622_5_right_shap,ZNF800_5_right_shap,ZRANB2_5_right_shap,AARS_center_left_shap,AATF_center_left_shap,ABCF1_center_left_shap,ADAT1_center_left_shap,AGGF1_center_left_shap,AKAP1_center_left_shap,AKAP8L_center_left_shap,APEX1_center_left_shap,APOBEC3C_center_left_shap,AQR_center_left_shap,BUD13_center_left_shap,CPEB4_center_left_shap,CPSF6_center_left_shap,CSTF2T_center_left_shap,DDX1_center_left_shap,DDX21_center_left_shap,DDX24_center_left_shap,DDX3X_center_left_shap,DDX42_center_left_shap,DDX43_center_left_shap,DDX47_center_left_shap,DDX51_center_left_shap,DDX52_center_left_shap,DDX55_center_left_shap,DDX6_center_left_shap,DGCR8_center_left_shap,DHX30_center_left_shap,DROSHA_center_left_shap,EEF2_center_left_shap,EFTUD2_center_left_shap,EIF3G_center_left_shap,EIF4E_center_left_shap,EIF4G2_center_left_shap,ELAC2_center_left_shap,ELAVL1_center_left_shap,EWSR1_center_left_shap,EXOSC10_center_left_shap,EXOSC5_center_left_shap,FAM120A_center_left_shap,FASTKD2_center_left_shap,FMR1_center_left_shap,FTO_center_left_shap,FUS_center_left_shap,FXR1_center_left_shap,FXR2_center_left_shap,GARS_center_left_shap,GEMIN5_center_left_shap,GNL3_center_left_shap,GPKOW_center_left_shap,GRWD1_center_left_shap,GTF2F1_center_left_shap,HLTF_center_left_shap,HNRNPA1_center_left_shap,HNRNPC_center_left_shap,HNRNPK_center_left_shap,HNRNPL_center_left_shap,HNRNPM_center_left_shap,HNRNPU_center_left_shap,HNRNPUL1_center_left_shap,IGF2BP1_center_left_shap,IGF2BP2_center_left_shap,ILF3_center_left_shap,KHDRBS1_center_left_shap,KHSRP_center_left_shap,LARP4_center_left_shap,LARP7_center_left_shap,LIN28B_center_left_shap,LSM11_center_left_shap,MATR3_center_left_shap,MBNL1_center_left_shap,METAP2_center_left_shap,METTL1_center_left_shap,MORC2_center_left_shap,MTPAP_center_left_shap,NCBP2_center_left_shap,NIPBL_center_left_shap,NOLC1_center_left_shap,NONO_center_left_shap,NPM1_center_left_shap,NSUN2_center_left_shap,PABPC4_center_left_shap,PCBP1_center_left_shap,PHF6_center_left_shap,PPIL4_center_left_shap,PRPF8_center_left_shap,PTBP1_center_left_shap,PUM1_center_left_shap,PUM2_center_left_shap,PUS1_center_left_shap,QKI_center_left_shap,RBFOX2_center_left_shap,RBM15_center_left_shap,RBM22_c

,AGGF1_5_left,AKAP1_5_left,AQR_5_left,BCCIP_5_left,BCLAF1_5_left,BUD13_5_left,CDC40_5_left,CSTF2_5_left,CSTF2T_5_left,DDX3X_5_left,DDX52_5_left,DDX55_5_left,DDX59_5_left,DDX6_5_left,DGCR8_5_left,DHX30_5_left,DKC1_5_left,DROSHA_5_left,EFTUD2_5_left,EIF3D_5_left,EIF3H_5_left,EXOSC5_5_left,FAM120A_5_left,FASTKD2_5_left,FKBP4_5_left,FTO_5_left,FUBP3_5_left,FUS_5_left,FXR2_5_left,G3BP1_5_left,GRSF1_5_left,GRWD1_5_left,GTF2F1_5_left,HLTF_5_left,HNRNPA1_5_left,HNRNPC_5_left,HNRNPK_5_left,HNRNPL_5_left,HNRNPM_5_left,HNRNPU_5_left,HNRNPUL1_5_left,IGF2BP1_5_left,IGF2BP3_5_left,ILF3_5_left,KHSRP_5_left,LARP4_5_left,LARP7_5_left,LIN28B_5_left,LSM11_5_left,MATR3_5_left,NCBP2_5_left,NIP7_5_left,NKRF_5_left,NOL12_5_left,NOLC1_5_left,NSUN2_5_left,PABPN1_5_left,PCBP1_5_left,PCBP2_5_left,POLR2G_5_left,PPIG_5_left,PRPF4_5_left,PRPF8_5_left,PTBP1_5_left,QKI_5_left,RBFOX2_5_left,RBM15_5_left,RBM22_5_left,RBM5_5_left,RPS3_5_left,SAFB_5_left,SDAD1_5_left,SF3A3_5_left,SF3B4_5_left,SFPQ_5_left,SLTM_5_left,SMNDC1_5_left,SND1_5_left,SRSF1_5_left,SRSF7_5_left,SRSF9_5_left,SSB_5_left,STAU2_5_left,SUB1_5_left,SUGP2_5_left,SUPV3L1_5_left,TAF15_5_left,TARDBP_5_left,TBRG4_5_left,TIA1_5_left,TIAL1_5_left,TRA2A_5_left,TROVE2_5_left,U2AF1_5_left,U2AF2_5_left,UCHL5_5_left,UPF1_5_left,UTP18_5_left,WDR43_5_left,XPO5_5_left,XRCC6_5_left,XRN2_5_left,YBX3_5_left,ZC3H11A_5_left,ZNF800_5_left,AGGF1_5_right,AKAP1_5_right,AQR_5_right,BCCIP_5_right,BCLAF1_5_right,BUD13_5_right,CDC40_5_right,CSTF2_5_right,CSTF2T_5_right,DDX3X_5_right,DDX52_5_right,DDX55_5_right,DDX59_5_right,DDX6_5_right,DGCR8_5_right,DHX30_5_right,DKC1_5_right,DROSHA_5_right,EFTUD2_5_right,EIF3D_5_right,EIF3H_5_right,EXOSC5_5_right,FAM120A_5_right,FASTKD2_5_right,FKBP4_5_right,FTO_5_right,FUBP3_5_right,FUS_5_right,FXR2_5_right,G3BP1_5_right,GRSF1_5_right,GRWD1_5_right,GTF2F1_5_right,HLTF_5_right,HNRNPA1_5_right,HNRNPC_5_right,HNRNPK_5_right,HNRNPL_5_right,HNRNPM_5_right,HNRNPU_5_right,HNRNPUL1_5_right,IGF2BP1_5_right,IGF2BP3_5_right,ILF3_5_right,KHSRP_5_right,LARP4_5_right,LARP7_5_right,LIN28B_5_right,LSM11_5_right,MATR3_5_right,NCBP2_5_right,NIP7_5_right,NKRF_5_right,NOL12_5_right,NOLC1_5_right,NSUN2_5_right,PABPN1_5_right,PCBP1_5_right,PCBP2_5_right,POLR2G_5_right,PPIG_5_right,PRPF4_5_right,PRPF8_5_right,PTBP1_5_right,QKI_5_right,RBFOX2_5_right,RBM15_5_right,RBM22_5_right,RBM5_5_right,RPS3_5_right,SAFB_5_right,SDAD1_5_right,SF3A3_5_right,SF3B4_5_right,SFPQ_5_right,SLTM_5_right,SMNDC1_5_right,SND1_5_right,SRSF1_5_right,SRSF7_5_right,SRSF9_5_right,SSB_5_right,STAU2_5_right,SUB1_5_right,SUGP2_5_right,SUPV3L1_5_right,TAF15_5_right,TARDBP_5_right,TBRG4_5_right,TIA1_5_right,TIAL1_5_right,TRA2A_5_right,TROVE2_5_right,U2AF1_5_right,U2AF2_5_right,UCHL5_5_right,UPF1_5_right,UTP18_5_right,WDR43_5_right,XPO5_5_right,XRCC6_5_right,XRN2_5_right,YBX3_5_right,ZC3H11A_5_right,ZNF800_5_right,AGGF1_center_left,AKAP1_center_left,AQR_center_left,BCCIP_center_left,BCLAF1_center_left,BUD13_center_left,CDC40_center_left,CSTF2_center_left,CSTF2T_center_left,DDX3X_center_left,DDX52_center_left,DDX55_center_left,DDX59_center_left,DDX6_center_left,DGCR8_center_left,DHX30_center_left,DKC1_center_left,DROSHA_center_left,EFTUD2_center_left,EIF3D_center_left,EIF3H_center_left,EXOSC5_center_left,FAM120A_center_left,FASTKD2_center_left,FKBP4_center_left,FTO_center_left,FUBP3_center_left,FUS_center_left,FXR2_center_left,G3BP1_center_left,GRSF1_center_left,GRWD1_center_left,GTF2F1_center_left,HLTF_center_left,HNRNPA1_center_left,HNRNPC_center_left,HNRNPK_center_left,HNRNPL_center_left,HNRNPM_center_left,HNRNPU_center_left,HNRNPUL1_center_left,IGF2BP1_center_left,IGF2BP3_center_left,ILF3_center_left,KHSRP_center_left,LARP4_center_left,LARP7_center_left,LIN28B_center_left,LSM11_center_left,MATR3_center_left,NCBP2_center_left,NIP7_center_left,NKRF_center_left,NOL12_center_left,NOLC1_center_left,NSUN2_center_left,PABPN1_center_left,PCBP1_center_left,PCBP2_center_left,POLR2G_center_left,PPIG_center_left,PRPF4_center_left,PRPF8_center_left,PTBP1_center_left,QKI_center_left,RBFOX2_center_left,RBM15_center_left,RBM22_center_left,RBM5_center_left,RPS3_center_left,SAFB_center_left,SDAD1_center_left,SF3A3_center_left,SF3B4_center_left,SFPQ_center_left,SLTM_center_left,SMNDC1_center_left,SND1_center_left,SRSF1_center_left,SRSF7_center_left,SRSF9_center_left,SSB_center_left,STAU2_center_left,SUB1_center_left,SUGP2_center_left,SUPV3L1_center_left,TAF15_center_left,TARDBP_center_left,TBRG4_center_left,TIA1_center_left,TIAL1_center_left,TRA2A_center_left,TROVE2_center_left,U2AF1_center_left,U2AF2_center_left,UCHL5_center_left,UPF1_center_left,UTP18_center_left,WDR43_center_left,XPO5_center_left,XRCC6_center_left,XRN2_center_left,YBX3_center_left,ZC3H11A_center_left,ZNF800_center_left,AGGF1_center_right,AKAP1_center_right,AQR_center_right,BCCIP_center_right,BCLAF1_center_right,BUD13_center_right,CDC40_center_right,CSTF2_center_right,CSTF2T_center_right,DDX3X_center_right,DDX52_center_right,DDX55_center_right,DDX59_center_right,DDX6_center_right,DGCR8_center_right,DHX30_center_right,DKC1_center_right,DROSHA_center_right,EFTUD2_center_right,EIF3D_center_right,EIF3H_center_right,EXOSC5_center_right,FAM120A_center_right,FASTKD2_center_right,FKBP4_center_right,FTO_center_right,FUBP3_center_right,FUS_center_right,FXR2_center_right,G3BP1_center_right,GRSF1_center_right,GRWD1_center_right,GTF2F1_center_right,HLTF_center_right,HNRNPA1_center_right,HNRNPC_center_right,HNRNPK_center_right,HNRNPL_center_right,HNRNPM_center_right,HNRNPU_center_right,HNRNPUL1_center_right,IGF2BP1_center_right,IGF2BP3_center_right,ILF3_center_right,KHSRP_center_right,LARP4_center_right,LARP7_center_right,LIN28B_center_right,LSM11_center_right,MATR3_center_right,NCBP2_center_right,NIP7_center_right,NKRF_center_right,NOL12_center_right,NOLC1_center_right,NSUN2_center_right,PABPN1_center_right,PCBP1_center_right,PCBP2_center_right,POLR2G_center_right,PPIG_center_right,PRPF4_center_right,PRPF8_center_right,PTBP1_center_right,QKI_center_right,RBFOX2_center_right,RBM15_center_right,RBM22_center_right,RBM5_center_right,RPS3_center_right,SAFB_center_right,SDAD1_center_right,SF3A3_center_right,SF3B4_center_right,SFPQ_center_right,SLTM_center_right,SMNDC1_center_right,SND1_center_right,SRSF1_center_right,SRSF7_center_right,SRSF9_center_right,SSB_center_right,STAU2_center_right,SUB1_center_right,SUGP2_center_right,SUPV3L1_center_right,TAF15_center_right,TARDBP_center_right,TBRG4_center_right,TIA1_center_right,TIAL1_center_right,TRA2A_center_right,TROVE2_center_right,U2AF1_center_right,U2AF2_center_right,UCHL5_center_right,UPF1_center_right,UTP18_center_right,WDR43_center_right,XPO5_center_right,XRCC6_center_right,XRN2_center_right,YBX3_center_right,ZC3H11A_center_right,ZNF800_center_right,AGGF1_3_left,AKAP1_3_left,AQR_3_left,BCCIP_3_left,BCLAF1_3_left,BUD13_3_left,CDC40_3_left,CSTF2_3_left,CSTF2T_3_left,DDX3X_3_left,DDX52_3_left,DDX55_3_left,DDX59_3_left,DDX6_3_left,DGCR8_3_left,DHX30_3_left,DKC1_3_left,DROSHA_3_left,EFTUD2_3_left,EIF3D_3_left,EIF3H_3_left,EXOSC5_3_left,FAM120A_3_left,FASTKD2_3_left,FKBP4_3_left,FTO_3_left,FUBP3_3_left,FUS_3_left,FXR2_3_left,G3BP1_3_left,GRSF1_3_left,GRWD1_3_left,GTF2F1_3_left,HLTF_3_left,HNRNPA1_3_left,HNRNPC_3_left,HNRNPK_3_left,HNRNPL_3_left,HNRNPM_3_left,HNRNPU_3_left,HNRNPUL1_3_left,IGF2BP1_3_left,IGF2BP3_3_left,ILF3_3_left,KHSRP_3_left,LARP4_3_left,LARP7_3_left,LIN28B_3_left,LSM11_3_left,MATR3_3_left,NCBP2_3_left,NIP7_3_left,NKRF_3_left,NOL12_3_left,NOLC1_3_left,NSUN2_3_left,PABPN1_3_left,PCBP1_3_left,PCBP2_3_left,POLR2G_3_left,PPIG_3_left,PRPF4_3_left,PRPF8_3_left,PTBP1_3_left,QKI_3_left,RBFOX2_3_left,RBM15_3_left,RBM22_3_left,RBM5_3_left,RPS3_3_left,SAFB_3_left,SDAD1_3_left,SF3A3_3_left,SF3B4_3_left,SFPQ_3_left,SLTM_3_left,SMNDC1_3_left,SND1_3_left,SRSF1_3_left,SRSF7_3_left,SRSF9_3_left,SSB_3_left,STAU2_3_left,SUB1_3_left,SUGP2_3_left,SUPV3L1_3_left,TAF15_3_left,TARDBP_3_left,TBRG4_3_left,TIA1_3_left,TIAL1_3_left,TRA2A_3_left,TROVE2_3_left,U2AF1_3_left,U2AF2_3_left,UCHL5_3_left,UPF1_3_left,UTP18_3_left,WDR43_3_left,XPO5_3_left,XRCC6_3_left,XRN2_3_left,YBX3_3_left,ZC3H11A_3_left,ZNF800_3_left,AGGF1_3_right,AKAP1_3_right,AQR_3_right,BCCIP_3_right,BCLAF1_3_right,BUD13_3_right,CDC40_3_right,CSTF2_3_right,CSTF2T_3_right,DDX3X_3_right,DDX52_3_right,DDX55_3_right,DDX59_3_right,DDX6_3_right,DGCR8_3_right,DHX30_3_right,DKC1_3_right,DROSHA_3_right,EFTUD2_3_right,EIF3D_3_right,EIF3H_3_right,EXOSC5_3_right,FAM120A_3_right,FASTKD2_3_right,FKBP4_3_right,FTO_3_right,FUBP3_3_right,FUS_3_right,FXR2_3_right,G3BP1_3_right,GRSF1_3_right,GRWD1_3_right,GTF2F1_3_right,HLTF_3_right,HNRNPA1_3_right,HNRNPC_3_right,HNRNPK_3_right,HNRNPL_3_right,HNRNPM_3_right,HNRNPU_3_right,HNRNPUL1_3_right,IGF2BP1_3_right,IGF2BP3_3_right,ILF3_3_right,KHSRP_3_right,LARP4_3_right,LARP7_3_right,LIN28B_3_right,LSM11_3_right,MATR3_3_right,NCBP2_3_right,NIP7_3_right,NKRF_3_right,NOL12_3_right,NOLC1_3_right,NSUN2_3_right,PABPN1_3_right,PCBP1_3_right,PCBP2_3_right,POLR2G_3_right,PPIG_3_right,PRPF4_3_right,PRPF8_3_right,PTBP1_3_right,QKI_3_right,RBFOX2_3_right,RBM15_3_right,RBM22_3_right,RBM5_3_right,RPS3_3_right,SAFB_3_right,SDAD1_3_right,SF3A3_3_right,SF3B4_3_right,SFPQ_3_right,SLTM_3_right,SMNDC1_3_right,SND1_3_right,SRSF1_3_right,SRSF7_3_right,SRSF9_3_right,SSB_3_right,STAU2_3_right,SUB1_3_right,SUGP2_3_right,SUPV3L1_3_right,TAF15_3_right,TARDBP_3_right,TBRG4_3_right,TIA1_3_right,TIAL1_3_right,TRA2A_3_right,TROVE2_3_right,U2AF1_3_right,U2AF2_3_right,UCHL5_3_right,UPF1_3_right,UTP18_3_right,WDR43_3_right,XPO5_3_right,XRCC6_3_right,XRN2_3_right,YBX3_3_right,ZC3H11A_3_right,ZNF800_3_right,target,psi_hat,AGGF1_5_left_shap,AKAP1_5_left_shap,AQR_5_left_shap,BCCIP_5_left_shap,BCLAF1_5_left_shap,BUD13_5_left_shap,CDC40_5_left_shap,CSTF2_5_left_shap,CSTF2T_5_left_shap,DDX3X_5_left_shap,DDX52_5_left_shap,DDX55_5_left_shap,DDX59_5_left_shap,DDX6_5_left_shap,DGCR8_5_left_shap,DHX30_5_left_shap,DKC1_5_left_shap,DROSHA_5_left_shap,EFTUD2_5_left_shap,EIF3D_5_left_shap,EIF3H_5_left_shap,EXOSC5_5_left_shap,FAM120A_5_left_shap,FASTKD2_5_left_shap,FKBP4_5_left_shap,FTO_5_left_shap,FUBP3_5_left_shap,FUS_5_left_shap,FXR2_5_left_shap,G3BP1_5_left_shap,GRSF1_5_left_shap,GRWD1_5_left_shap,GTF2F1_5_left_shap,HLTF_5_left_shap,HNRNPA1_5_left_shap,HNRNPC_5_left_shap,HNRNPK_5_left_shap,HNRNPL_5_left_shap,HNRNPM_5_left_shap,HNRNPU_5_left_shap,HNRNPUL1_5_left_shap,IGF2BP1_5_left_shap,IGF2BP3_5_left_shap,ILF3_5_left_shap,KHSRP_5_left_shap,LARP4_5_left_shap,LARP7_5_left_shap,LIN28B_5_left_shap,LSM11_5_left_shap,MATR3_5_left_shap,NCBP2_5_left_shap,NIP7_5_left_shap,NKRF_5_left_shap,NOL12_5_left_shap,NOLC1_5_left_shap,NSUN2_5_left_shap,PABPN1_5_left_shap,PCBP1_5_left_shap,PCBP2_5_left_shap,POLR2G_5_left_shap,PPIG_5_left_shap,PRPF4_5_left_shap,PRPF8_5_left_shap,PTBP1_5_left_shap,QKI_5_left_shap,RBFOX2_5_left_shap,RBM15_5_left_shap,RBM22_5_left_shap,RBM5_5_left_shap,RPS3_5_left_shap,SAFB_5_left_shap,SDAD1_5_left_shap,SF3A3_5_left_shap,SF3B4_5_left_shap,SFPQ_5_left_shap,SLTM_5_left_shap,SMNDC1_5_left_shap,SND1_5_left_shap,SRSF1_5_left_shap,SRSF7_5_left_shap,SRSF9_5_left_shap,SSB_5_left_shap,STAU2_5_left_shap,SUB1_5_left_shap,SUGP2_5_left_shap,SUPV3L1_5_left_shap,TAF15_5_left_shap,TARDBP_5_left_shap,TBRG4_5_left_shap,TIA1_5_left_shap,TIAL1_5_left_shap,TRA2A_5_left_shap,TROVE2_5_left_shap,U2AF1_5_left_shap,U2AF2_5_left_shap,UCHL5_5_left_shap,UPF1_5_left_shap,UTP18_5_left_shap,WDR43_5_left_shap,XPO5_5_left_shap,XRCC6_5_left_shap,XRN2_5_left_shap,YBX3_5_left_shap,ZC3H11A_5_left_shap,ZNF800_5_left_shap,AGGF1_5_right_shap,AKAP1_5_right_shap,AQR_5_right_shap,BCCIP_5_right_shap,BCLAF1_5_right_shap,BUD13_5_right_shap,CDC40_5_right_shap,CSTF2_5_right_shap,CSTF2T_5_right_shap,DDX3X_5_right_shap,DDX52_5_right_shap,DDX55_5_right_shap,DDX59_5_right_shap,DDX6_5_right_shap,DGCR8_5_right_shap,DHX30_5_right_shap,DKC1_5_right_shap,DROSHA_5_right_shap,EFTUD2_5_right_shap,EIF3D_5_right_shap,EIF3H_5_right_shap,EXOSC5_5_right_shap,FAM120A_5_right_shap,FASTKD2_5_right_shap,FKBP4_5_right_shap,FTO_5_right_shap,FUBP3_5_right_shap,FUS_5_right_shap,FXR2_5_right_shap,G3BP1_5_right_shap,GRSF1_5_right_shap,GRWD1_5_right_shap,GTF2F1_5_right_shap,HLTF_5_right_shap,HNRNPA1_5_right_shap,HNRNPC_5_right_shap,HNRNPK_5_right_shap,HNRNPL_5_right_shap,HNRNPM_5_right_shap,HNRNPU_5_right_shap,HNRNPUL1_5_right_shap,IGF2BP1_5_right_shap,IGF2BP3_5_right_shap,ILF3_5_right_shap,KHSRP_5_right_shap,LARP4_5_right_shap,LARP7_5_right_shap,LIN28B_5_right_shap,LSM11_5_right_shap,MATR3_5_right_shap,NCBP2_5_right_shap,NIP7_5_right_shap,NKRF_5_right_shap,NOL12_5_right_shap,NOLC1_5_right_shap,NSUN2_5_right_shap,PABPN1_5_right_shap,PCBP1_5_right_shap,PCBP2_5_right_shap,POLR2G_5_right_shap,PPIG_5_right_shap,PRPF4_5_right_shap,PRPF8_5_right_shap,PTBP1_5_right_shap,QKI_5_right_shap,RBFOX2_5_right_shap,RBM15_5_right_shap,RBM22_5_right_shap,RBM5_5_right_shap,RPS3_5_right_shap,SAFB_5_right_shap,SDAD1_5_right_shap,SF3A3_5_right_shap,SF3B4_5_right_shap,SFPQ_5_right_shap,SLTM_5_right_shap,SMNDC1_5_right_shap,SND1_5_right_shap,SRSF1_5_right_shap,SRSF7_5_right_shap,SRSF9_5_right_shap,SSB_5_right_shap,STAU2_5_right_shap,SUB1_5_right_shap,SUGP2_5_right_shap,SUPV3L1_5_right_shap,TAF15_5_right_shap,TARDBP_5_right_shap,TBRG4_5_right_shap,TIA1_5_right_shap,TIAL1_5_right_shap,TRA2A_5_right_shap,TROVE2_5_right_shap,U2AF1_5_right_shap,U2AF2_5_right_shap,UCHL5_5_right_shap,UPF1_5_right_shap,UTP18_5_right_shap,WDR43_5_right_shap,XPO5_5_right_shap,XRCC6_5_right_shap,XRN2_5_right_shap,YBX3_5_right_shap,ZC3H11A_5_right_shap,ZNF800_5_right_shap,AGGF1_center_left_shap,AKAP1_center_left_shap,AQR_center_left_shap,BCCIP_center_left_shap,BCLAF1_center_left_shap,BUD13_center_left_shap,CDC40_center_left_shap,CSTF2_center_left_shap,CSTF2T_center_left_shap,DDX3X_center_left_shap,DDX52_center_left_shap,DDX55_center_left_shap,DDX59_center_left_shap,DDX6_center_left_shap,DGCR8_center_left_shap,DHX30_center_left_shap,DKC1_center_left_shap,DROSHA_center_left_shap,EFTUD2_center_left_shap,EIF3D_center_left_shap,EIF3H_center_left_shap,EXOSC5_center_left_shap,FAM120A_center_left_shap,FASTKD2_center_left_shap,FKBP4_center_left_shap,FTO_center_left_shap,FUBP3_center_left_shap,FUS_center_left_shap,FXR2_center_left_shap,G3BP1_center_left_shap,GRSF1_center_left_shap,GRWD1_center_left_shap,GTF2F1_center_left_shap,HLTF_center_left_shap,HNRNPA1_center_left_shap,HNRNPC_center_left_shap,HNRNPK_center_left_shap,HNRNPL_center_left_shap,HNRNPM_center_left_shap,HNRNPU_center_left_shap,HNRNPUL1_center_left_shap,IGF2BP1_center_left_shap,IGF2BP3_center_left_shap,ILF3_center_left_shap,KHSRP_center_left_shap,LARP4_center_left_shap,LARP7_center_left_shap,LIN28B_center_left_shap,LSM11_center_left_shap,MATR3_center_left_shap,NCBP2_center_left_shap,NIP7_center_left_shap,NKRF_center_left_shap,NOL12_center_left_shap,NOLC1_center_left_shap,NSUN2_center_left_shap,PABPN1_center_left_shap,PCBP1_center_left_shap,PCBP2_center_left_shap,POLR2G_center_left_shap,PPIG_center_left_shap,PRPF4_center_left_shap,PRPF8_center_left_shap,PTBP1_center_left_shap,QKI_center_left_shap,RBFOX2_center_left_shap,RBM15_center_left_shap,RBM22_center_left_shap,RBM5_center_left_shap,RPS3_center_left_shap,SAFB_center_left_shap,SDAD1_center_left_shap,SF3A3_center_left_shap,SF3B4_center_left_shap,SFPQ_center_left_shap,SLTM_center_left_shap,SMNDC1_center_left_shap,SND1_center_left_shap,SRSF1_center_left_shap,SRSF7_center_left_shap,SRSF9_center_left_shap,SSB_center_left_shap,STAU2_center_left_shap,SUB1_center_left_shap,SUGP2_center_left_shap,SUPV3L1_center_left_shap,TAF15_center_left_shap,TARDBP_center_left_shap,TBRG4_center_left_shap,TIA1_center_left_shap,TIAL1_center_left_shap,TRA2A_center_left_shap,TROVE2_center_left_shap,U2AF1_center_left_shap,U2AF2_center_left_shap,UCHL5_center_left_shap,UPF1_center_left_shap,UTP18_center_left_shap,WDR43_center_left_shap,XPO5_center_left_shap,XRCC6_center_left_shap,XRN2_center_left_shap,YBX3_center_left_shap,ZC3H11A_center_left_shap,ZNF800_center_left_shap,AGGF1_center_right_shap,AKAP1_center_right_shap,AQR_center_right_shap,BCCIP_center_right_shap,BCLAF1_center_right_shap,BUD13_center_right_shap,CDC40_center_right_shap,CSTF2_center_right_shap,CSTF2T_center_right_shap,DDX3X_center_right_shap,DDX52_center_right_shap,DDX55_center_right_shap,DDX59_center_right_shap,DDX6_center_right_shap,DGCR8_center_right_shap,DHX30_center_right_shap,DKC1_center_right_shap,DROSHA_center_right_shap,EFTUD2_center_right_shap,EIF3D_center_right_shap,EIF3H_center_right_shap,EXOSC5_center_right_shap,FAM120A_center_right_shap,FASTKD2_center_right_shap,FKBP4_center_right_shap,FTO_center_right_shap,FUBP3_center_right_shap,FUS_center_right_shap,FXR2_center_right_shap,G3BP1_center_right_shap,GRSF1_center_right_shap,GRWD1_center_right_shap,GTF2F1_center_right_shap,HLTF_center_right_shap,HNRNPA1_center_right_shap,HNRNPC_center_right_shap,HNRNPK_center_right_shap,HNRNPL_center_right_shap,HNRNPM_center_right_shap,HNRNPU_center_right_shap,HNRNPUL1_center_right_shap,IGF2BP1_center_right_shap,IGF2BP3_center_right_shap,ILF3_center_right_shap,KHSRP_center_right_shap,LARP4_center_right_shap,LARP7_center_right_shap,LIN28B_center_right_shap,LSM11_center_right_shap,MATR3_center_right_shap,NCBP2_center_right_shap,NIP7_center_right_shap,NKRF_center_right_shap,NOL12_center_right_shap,NOLC1_center_right_shap,NSUN2_center_right_shap,PABPN1_center_right_shap,PCBP1_center_right_shap,PCBP2_center_right_shap,POLR2G_center_right_shap,PPIG_center_right_shap,PRPF4_center_right_shap,PRPF8_center_right_shap,PTBP1_center_right_shap,QKI_center_right_shap,RBFOX2_center_right_shap,RBM15_center_right_shap,RBM22_center_right_shap,RBM5_center_right_shap,RPS3_center_right_shap,SAFB_center_right_shap,SDAD1_center_right_shap,SF3A3_center_right_shap,SF3B4_center_right_shap,SFPQ_center_right_shap,SLTM_center_right_shap,SMNDC1_center_right_shap,SND1_center_right_shap,SRSF1_center_right_shap,SRSF7_center_right_shap,SRSF9_center_right_shap,SSB_center_right_shap,STAU2_center_right_shap,SUB1_center_right_shap,SUGP2_center_right_shap,SUPV3L1_center_right_shap,TAF15_center_right_shap,TARDBP_center_right_shap,TBRG4_center_right_shap,TIA1_center_right_shap,TIAL1_center_right_shap,TRA2A_center_right_shap,TROVE2_center_right_shap,U2AF1_center_right_shap,U2AF2_center_right_shap,UCHL5_center_right_shap,UPF1_center_right_shap,UTP18_center_right_shap,WDR43_center_right_shap,XPO5_center_right_shap,XRCC6_center_right_shap,XRN2_center_right_shap,YBX3_center_right_shap,ZC3H11A_center_right_shap,ZNF800_center_right_shap,AGGF1_3_left_shap,AKAP1_3_left_shap,AQR_3_left_shap,BCCIP_3_left_shap,BCLAF1_3_left_shap,BUD13_3_left_shap,CDC40_3_left_shap,CSTF2_3_left_shap,CSTF2T_3_left_shap,DDX3X_3_left_shap,DDX52_3_left_shap,DDX55_3_left_shap,DDX59_3_left_shap,DDX6_3_left_shap,DGCR8_3_left_shap,DHX30_3_left_shap,DKC1_3_left_shap,DROSHA_3_left_shap,EFTUD2_3_left_shap,EIF3D_3_left_shap,EIF3H_3_left_shap,EXOSC5_3_left_shap,FAM120A_3_left_shap,FASTKD2_3_left_shap,FKBP4_3_left_shap,FTO_3_left_shap,FUBP3_3_left_shap,FUS_3_left_shap,FXR2_3_left_shap,G3BP1_3_left_shap,GRSF1_3_left_shap,GRWD1_3_left_shap,GTF2F1_3_left_shap,HLTF_3_left_shap,HNRNPA1_3_left_shap,HNRNPC_3_left_shap,HNRNPK_3_left_shap,HNRNPL_3_left_shap,HNRNPM_3_left_shap,HNRNPU_3_left_shap,HNRNPUL1_3_left_shap,IGF2BP1_3_left_shap,IGF2BP3_3_left_shap,ILF3_3_left_shap,KHSRP_3_left_shap,LARP4_3_left_shap,LARP7_3_left_shap,LIN28B_3_left_shap,LSM11_3_left_shap,MATR3_3_left_shap,NCBP2_3_left_shap,NIP7_3_left_shap,NKRF_3_left_shap,NOL12_3_left_shap,NOLC1_3_left_shap,NSUN2_3_left_shap,PABPN1_3_left_shap,PCBP1_3_left_shap,PCBP2_3_left_shap,POLR2G_3_left_shap,PPIG_3_left_shap,PRPF4_3_left_shap,PRPF8_3_left_shap,PTBP1_3_left_shap,QKI_3_left_shap,RBFOX2_3_left_shap,RBM15_3_left_shap,RBM22_3_left_shap,RBM5_3_left_shap,RPS3_3_left_shap,SAFB_3_left_shap,SDAD1_3_left_shap,SF3A3_3_left_shap,SF3B4_3_left_shap,SFPQ_3_left_shap,SLTM_3_left_shap,SMNDC1_3_left_shap,SND1_3_left_shap,SRSF1_3_left_shap,SRSF7_3_left_shap,SRSF9_3_left_shap,SSB_3_left_shap,STAU2_3_left_shap,SUB1_3_left_shap,SUGP2_3_left_shap,SUPV3L1_3_left_