# Create `Splice-Junction-to-RBP-Number-of-Peaks` Dictionary

## Purpose: 

* Take `bedtools closest` output and clean it up. 
* Create dictionary of splice junction to number of times RBP binds. 
* Output dictionary.

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import glob, pickle, gzip, sys

## Literals

In [2]:
cell_lines = ["K562", "HepG2"]
thresholds = [25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 500, 1000, 2000, 5000, 10000]

## Load and Clean `BedTools Closest` Output

In [3]:
eclip_to_splice_junctions = {}

for cell_line in cell_lines:
    eclip_to_splice_junctions[cell_line] = {}
    for distance in thresholds: 
        
        file = glob.glob("../output/peaks_to_splice_junctions/{}_{}_*.bed".format(cell_line, distance))
        assert len(file)==1
        
        tmp_mappings = pd.read_csv(file[0], sep="\t", header=None)
        
        assert tmp_mappings[5].equals(tmp_mappings[11])
        assert all(tmp_mappings[9].str.startswith("chr"))
            
        # filter for the RBP, unique splice junction ID, and distance columns
        tmp_mappings = tmp_mappings[[3, 9]]
        
        # parse out RBP column
        tmp_mappings["RBP"] = tmp_mappings[3].str.split("_").str[0]
        # change column names for clarity
        tmp_mappings = tmp_mappings.rename(
            columns={
                
                9: "Splice Junction ID",
            }
        )
    
        # ensure there are no null values in matrix 
        assert tmp_mappings.notnull().all().all()
        
        tmp_mappings.head()  
        
        # save the refined dataset
        eclip_to_splice_junctions[cell_line][distance] = tmp_mappings

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15947_-     AQR
1  EFTUD2_K562_IDR       chr1_17605_-  EFTUD2
2   SF3B4_K562_IDR       chr1_17605_-   SF3B4
3   DDX24_K562_IDR      chr1_169264_-   DDX24
4   DDX24_K562_IDR      chr1_172556_-   DDX24

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15947_-     AQR
1  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T
2  EFTUD2_K562_IDR       chr1_17605_-  EFTUD2
3   DDX24_K562_IDR       chr1_17605_-   DDX24
4   SF3B4_K562_IDR       chr1_17605_-   SF3B4

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15947_-     AQR
1  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T
2  EFTUD2_K562_IDR       chr1_17605_-  EFTUD2
3   DDX24_K562_IDR       chr1_17605_-   DDX24
4  SMNDC1_K562_IDR       chr1_17605_-  SMNDC1

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15947_-     AQR
1     AQR_K562_IDR       chr1_16606_-     AQR
2  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T
3  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T
4   SF3B4_K562_IDR       chr1_17368_-   SF3B4

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15947_-     AQR
1     AQR_K562_IDR       chr1_16606_-     AQR
2  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T
3  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T
4   SF3B4_K562_IDR       chr1_17368_-   SF3B4

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15795_-     AQR
1     AQR_K562_IDR       chr1_15947_-     AQR
2     AQR_K562_IDR       chr1_16606_-     AQR
3  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T
4  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15795_-     AQR
1     AQR_K562_IDR       chr1_15947_-     AQR
2     AQR_K562_IDR       chr1_16606_-     AQR
3  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T
4  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15795_-     AQR
1     AQR_K562_IDR       chr1_15947_-     AQR
2     AQR_K562_IDR       chr1_16606_-     AQR
3  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T
4  CSTF2T_K562_IDR       chr1_17605_-  CSTF2T

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15795_-     AQR
1     AQR_K562_IDR       chr1_15947_-     AQR
2     AQR_K562_IDR       chr1_16606_-     AQR
3  CSTF2T_K562_IDR       chr1_17232_-  CSTF2T
4  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T

                 3 Splice Junction ID     RBP
0     AQR_K562_IDR       chr1_15795_-     AQR
1     AQR_K562_IDR       chr1_15947_-     AQR
2     AQR_K562_IDR       chr1_16606_-     AQR
3  CSTF2T_K562_IDR       chr1_17232_-  CSTF2T
4  CSTF2T_K562_IDR       chr1_17368_-  CSTF2T

                3 Splice Junction ID    RBP
0    AQR_K562_IDR       chr1_15795_-    AQR
1    AQR_K562_IDR       chr1_15947_-    AQR
2  BUD13_K562_IDR       chr1_15795_-  BUD13
3  BUD13_K562_IDR       chr1_15947_-  BUD13
4  BUD13_K562_IDR       chr1_16606_-  BUD13

              3 Splice Junction ID  RBP
0  AQR_K562_IDR       chr1_15004_-  AQR
1  AQR_K562_IDR       chr1_15038_-  AQR
2  AQR_K562_IDR       chr1_15795_-  AQR
3  AQR_K562_IDR       chr1_15947_-  AQR
4  AQR_K562_IDR       chr1_16606_-  AQR

              3 Splice Junction ID  RBP
0  AQR_K562_IDR       chr1_15004_-  AQR
1  AQR_K562_IDR       chr1_15038_-  AQR
2  AQR_K562_IDR       chr1_15795_-  AQR
3  AQR_K562_IDR       chr1_15947_-  AQR
4  AQR_K562_IDR       chr1_16606_-  AQR

              3 Splice Junction ID  RBP
0  AQR_K562_IDR       chr1_15004_-  AQR
1  AQR_K562_IDR       chr1_15038_-  AQR
2  AQR_K562_IDR       chr1_15795_-  AQR
3  AQR_K562_IDR       chr1_15947_-  AQR
4  AQR_K562_IDR       chr1_16606_-  AQR

              3 Splice Junction ID  RBP
0  AQR_K562_IDR       chr1_15004_-  AQR
1  AQR_K562_IDR       chr1_15038_-  AQR
2  AQR_K562_IDR       chr1_15795_-  AQR
3  AQR_K562_IDR       chr1_15947_-  AQR
4  AQR_K562_IDR       chr1_16606_-  AQR

                  3 Splice Junction ID     RBP
0   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8
1    PPIG_HepG2_IDR      chr1_187577_-    PPIG
2  BCLAF1_HepG2_IDR      chr1_851926_+  BCLAF1
3  BCLAF1_HepG2_IDR      chr1_851987_+  BCLAF1
4  BCLAF1_HepG2_IDR      chr1_851998_+  BCLAF1

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
1   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8
2    PPIG_HepG2_IDR      chr1_187577_-    PPIG
3  BCLAF1_HepG2_IDR      chr1_851926_+  BCLAF1
4  BCLAF1_HepG2_IDR      chr1_851987_+  BCLAF1

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
1  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2
2   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8
3    PPIG_HepG2_IDR      chr1_187577_-    PPIG
4  BCLAF1_HepG2_IDR      chr1_851926_+  BCLAF1

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
2  EFTUD2_HepG2_IDR       chr1_17368_-  EFTUD2
3  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2
4   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
2  EFTUD2_HepG2_IDR       chr1_17368_-  EFTUD2
3  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2
4   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
2  EFTUD2_HepG2_IDR       chr1_17368_-  EFTUD2
3  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2
4   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
2  EFTUD2_HepG2_IDR       chr1_17368_-  EFTUD2
3  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2
4   PRPF8_HepG2_IDR      chr1_187128_-   PRPF8

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
2   PRPF4_HepG2_IDR       chr1_17742_-   PRPF4
3  EFTUD2_HepG2_IDR       chr1_17368_-  EFTUD2
4  EFTUD2_HepG2_IDR       chr1_17605_-  EFTUD2

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17232_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
2   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
3   PRPF4_HepG2_IDR       chr1_17742_-   PRPF4
4  EFTUD2_HepG2_IDR       chr1_17232_-  EFTUD2

                  3 Splice Junction ID     RBP
0   PRPF4_HepG2_IDR       chr1_17232_-   PRPF4
1   PRPF4_HepG2_IDR       chr1_17368_-   PRPF4
2   PRPF4_HepG2_IDR       chr1_17605_-   PRPF4
3   PRPF4_HepG2_IDR       chr1_17742_-   PRPF4
4  EFTUD2_HepG2_IDR       chr1_17232_-  EFTUD2

                 3 Splice Junction ID    RBP
0  PRPF4_HepG2_IDR       chr1_17055_-  PRPF4
1  PRPF4_HepG2_IDR       chr1_17232_-  PRPF4
2  PRPF4_HepG2_IDR       chr1_17368_-  PRPF4
3  PRPF4_HepG2_IDR       chr1_17605_-  PRPF4
4  PRPF4_HepG2_IDR       chr1_17742_-  PRPF4

                 3 Splice Junction ID    RBP
0  PRPF4_HepG2_IDR       chr1_16606_-  PRPF4
1  PRPF4_HepG2_IDR       chr1_16765_-  PRPF4
2  PRPF4_HepG2_IDR       chr1_16857_-  PRPF4
3  PRPF4_HepG2_IDR       chr1_17055_-  PRPF4
4  PRPF4_HepG2_IDR       chr1_17232_-  PRPF4

                 3 Splice Junction ID    RBP
0  PRPF4_HepG2_IDR       chr1_15795_-  PRPF4
1  PRPF4_HepG2_IDR       chr1_15947_-  PRPF4
2  PRPF4_HepG2_IDR       chr1_16606_-  PRPF4
3  PRPF4_HepG2_IDR       chr1_16765_-  PRPF4
4  PRPF4_HepG2_IDR       chr1_16857_-  PRPF4

                 3 Splice Junction ID    RBP
0  PRPF4_HepG2_IDR       chr1_15004_-  PRPF4
1  PRPF4_HepG2_IDR       chr1_15038_-  PRPF4
2  PRPF4_HepG2_IDR       chr1_15795_-  PRPF4
3  PRPF4_HepG2_IDR       chr1_15947_-  PRPF4
4  PRPF4_HepG2_IDR       chr1_16606_-  PRPF4

                 3 Splice Junction ID    RBP
0  PRPF4_HepG2_IDR       chr1_15004_-  PRPF4
1  PRPF4_HepG2_IDR       chr1_15038_-  PRPF4
2  PRPF4_HepG2_IDR       chr1_15795_-  PRPF4
3  PRPF4_HepG2_IDR       chr1_15947_-  PRPF4
4  PRPF4_HepG2_IDR       chr1_16606_-  PRPF4

## Get Dictionary of Splice Junction to RBPs Bound


**Dictionary structure**: 

```
{
    cell_line: {
        distance threshold:{
            splice junction id: {
                RBP name: # eCLIP Peaks 
            }
        }
    }
}
```

In [4]:
# dict following paradigm described above 
all_splice_junction_to_rbp_num_peaks = {}

# for each cell line 
for cell_line in cell_lines:

    cell_line
    all_splice_junction_to_rbp_num_peaks[cell_line] = {}
    
    # for each distance threshold 
    for distance in thresholds: 

        distance
        
        # get a count for the number of peaks of a given RBP at a specific splice junction for a distance threshold 
        # use pd.unstack method to convert output series into a 2D matrix where null values are made into 0
        threshold_mappings = eclip_to_splice_junctions[cell_line][distance].groupby(["Splice Junction ID", "RBP"]).size().unstack(fill_value=0)
        
        # get the rbps that should be included in the dataset but had no data show up 
        # (we need to indicate that these data are available but are all "0" values)
        cell_line_eclip = glob.glob(f"../output/bedtools_input/{cell_line}_*.bed")
        assert len(cell_line_eclip)==1
        
        cell_line_eclip  = pd.read_csv(cell_line_eclip[0], sep="\t", header=None)
        cell_line_eclip["RBP"] = cell_line_eclip[3].str.split("_").str[0]
        
        missing_rbps = set(cell_line_eclip["RBP"].unique().tolist()) - set(threshold_mappings.columns.tolist())
        print(f"Missing RBPS: {missing_rbps}")
        
        # if there are missing rbps 
        if len(missing_rbps)>0: 
            # fill all values for the rbp as 0 
            for rbp in missing_rbps: 
                threshold_mappings[rbp] = 0
        
        # sort RBP columns by name 
        threshold_mappings = threshold_mappings.sort_index(axis=0).sort_index(axis=1)
        
        # convert dataframe to dict whereby first key is splice junciton id and value is another dict where 
        # sub-dict key is RBP name and value is number of peaks
        all_splice_junction_to_rbp_num_peaks[cell_line][distance] = threshold_mappings.to_dict(orient="index")

'K562'

25

Missing RBPS: {'SBDS', 'WDR3'}

50

Missing RBPS: {'SBDS', 'WDR3'}

75

Missing RBPS: {'SBDS', 'WDR3'}

100

Missing RBPS: {'SBDS'}

125

Missing RBPS: {'SBDS'}

150

Missing RBPS: {'SBDS'}

175

Missing RBPS: {'SBDS'}

200

Missing RBPS: {'SBDS'}

225

Missing RBPS: {'SBDS'}

250

Missing RBPS: {'SBDS'}

500

Missing RBPS: set()

1000

Missing RBPS: set()

2000

Missing RBPS: set()

5000

Missing RBPS: set()

10000

Missing RBPS: set()

'HepG2'

25

Missing RBPS: {'TBRG4'}

50

Missing RBPS: {'TBRG4'}

75

Missing RBPS: {'TBRG4'}

100

Missing RBPS: {'TBRG4'}

125

Missing RBPS: set()

150

Missing RBPS: set()

175

Missing RBPS: set()

200

Missing RBPS: set()

225

Missing RBPS: set()

250

Missing RBPS: set()

500

Missing RBPS: set()

1000

Missing RBPS: set()

2000

Missing RBPS: set()

5000

Missing RBPS: set()

10000

Missing RBPS: set()

## Output Dictionary as `GZIP Pickle` File

In [5]:
for cell_line in cell_lines: 
    for distance in thresholds: 

        with gzip.GzipFile(f"../output/splice_junction_rbp_num_peaks/{cell_line}_{distance}.pkl.gz", 'wb') as file: 
            pickle.dump(all_splice_junction_to_rbp_num_peaks[cell_line][distance], file)

#### Test that the pickling and compressing worked

In [9]:
with gzip.open("../output/splice_junction_rbp_num_peaks/K562_100.pkl.gz", 'rb') as f:
    data = pickle.load(f)


for i in range(0,15):
    keys = list(data.keys())

    print(data[keys[i]])

{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 1, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 1, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 1, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 2, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 1, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 1, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 1, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 1, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 2, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 1, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 1, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 1, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 2, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 1, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 1, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 1, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 1, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 1, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 1, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 1, 'BUD13': 1, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 1, 'BUD13': 1, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 1, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 1, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 0, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 2, 'ZC3H8': 0, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 1, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 1, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 1, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 1, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 1, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 1, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 2, 'ZC3H8': 1, 'ZRANB2': 0}
{'AARS': 0, 'AATF': 0, 'ABCF1': 0, 'AGGF1': 0, 'AKAP1': 0, 'AKAP8L': 0, 'APOBEC3C': 0, 'AQR': 0, 'BUD13': 0, 'CPEB4': 0, 'CPSF6': 0, 'CSTF2T': 0, 'DDX1': 0, 'DDX24': 0, 'DDX3X': 0, 'DDX47': 0, 'DDX51': 0, 'DDX52': 0, 'DDX55': 0, 'DHX30': 0, 'DROSHA': 0, 'EEF2': 0, 'EFTUD2': 0, 'EIF3G': 0, 'EIF4G2': 0, 'EWSR1': 0, 'FAM120A': 0, 'FASTKD2': 0, 'FMR1': 0, 'FTO': 0, 'FUS': 0, 'FXR1': 0, 'GEMIN5': 0, 'GPKOW': 0, 'GRWD1': 0, 'GTF2F1': 0, 'HLTF': 0, 'HNRNPA1': 0, 'HNRNPC': 0, 'HNRNPK': 0, 'HNRNPL': 0, 'HNRNPM': 0, 'HNRNPU': 0, 'HNRNPUL1': 0, 'IGF2BP2': 0, 'ILF3': 0, 'KHDRBS1': 0, 'KHSRP': 0, 'LARP4': 0, 'LARP7': 0, 'LIN28B': 0, 'LSM11': 0, 'MATR3': 0, 'MBNL1': 0, 'METAP2': 0, 'MTPAP': 0, 'NCBP2': 0, 'NONO': 0, 'NSUN2': 0, 'PABPC4': 0, 'PCBP1': 0, 'PHF6': 0, 'PPIL4': 0, 'PTBP1': 0, 'PUM1': 0, 'PUM2': 0, 'PUS1': 0, 'QKI': 0, 'RBFOX2': 0, 'RBM15': 0, 'RBM22': 0, 'RPS10': 0, 'SAFB2': 0, 'SBDS': 0, 'SERBP1': 0, 'SF3B4': 0, 'SLBP': 0, 'SLTM': 0, 'SMNDC1': 0, 'SND1': 0, 'SRSF1': 0, 'SSB': 0, 'SUPV3L1': 0, 'TAF15': 0, 'TARDBP': 0, 'TBRG4': 0, 'TIA1': 0, 'TROVE2': 0, 'U2AF1': 0, 'U2AF2': 0, 'UCHL5': 0, 'UPF1': 0, 'UTP18': 0, 'UTP3': 0, 'WDR3': 0, 'WDR43': 0, 'WRN': 0, 'XRN2': 0, 'YBX3': 1, 'ZC3H8': 0, 'ZRANB2': 0}