# Create eCLIP Peaks per Cell Line

## Purpose: 

For each cell line: 

* Take the `RBPs` that have both `eCLIP` and `shRNA RNA-Seq` data
* Take all `eCLIP` peaks from all these `RBPs`
* Create a single `BED` file of all these peaks

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import glob

## Literals

In [2]:
cell_lines = ["K562", "HepG2"]

## Load `shRNA` + `eCLIP` Metadata and Do Relevant Filtering

In [3]:
shrna_metadata = pd.read_csv(
    "../../../inputs/metadata/ENCODE_shRNA_knockdown_FASTQ_metadata.tsv", 
    sep="\t",
)

eclip_metadata = pd.read_csv(
    "../../../inputs/metadata/eclip_metadata.tsv", 
    sep="\t"
)

In [4]:
shrna_metadata.index.size

# filter for polyA mRNA and released files 
shrna_metadata = shrna_metadata[
    (shrna_metadata["Library made from"]=="polyadenylated mRNA") & 
    (shrna_metadata["File Status"]=="released") 
]

shrna_metadata.index.size
shrna_metadata.head(n=2)

2134

2038

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
0,ENCFF258AKK,fastq,fastq,NaN,reads,NaN,ENCSR584UYK,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,NaN,NaN,NaN,NaN,NaN,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2017-12-06,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,1,/files/ENCFF028JDE/,NaN,NaN,1994094569,"Brenton Graveley, UConn",3d23629ac0b7f322dfa14662bd726f38,SRA:SRR14845888,https://www.encodeproject.org/files/ENCFF258AKK/@@download/ENCFF258AKK.fastq.gz,NaN,Illumina HiSeq 2500,NaN,released,s3://encode-public/2017/11/20/ae51799c-275f-4979-97b6-32ec3fc23ea3/ENCFF258AKK.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2017/11/20/ae51799c-275f-4979-97b6-32ec3fc23ea3/ENCFF258AKK.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,missing spikeins,NaN
1,ENCFF988NMV,fastq,fastq,NaN,reads,NaN,ENCSR584UYK,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,NaN,NaN,NaN,NaN,NaN,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2017-12-06,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,1,/files/ENCFF205QCK/,NaN,NaN,2338694468,"Brenton Graveley, UConn",c915da979858c0bb6200c273f9975ea0,SRA:SRR14845889,https://www.encodeproject.org/files/ENCFF988NMV/@@download/ENCFF988NMV.fastq.gz,NaN,Illumina HiSeq 2500,NaN,released,s3://encode-public/2017/11/20/b13eb07a-8e4e-48a0-87df-621b8df8f50f/ENCFF988NMV.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2017/11/20/b13eb07a-8e4e-48a0-87df-621b8df8f50f/ENCFF988NMV.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,missing spikeins,NaN

In [5]:
# subset eCLIP metadata to hg38 genome, released files, and IDR peaks
eclip_metadata = eclip_metadata[
    (eclip_metadata["File assembly"]=="GRCh38") & 
    (eclip_metadata["File Status"]=="released") &
    (eclip_metadata["Biological replicate(s)"]=="1, 2") 
]

eclip_metadata.head()

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
5,ENCFF612HOP,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR322HHA,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIAL1-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,"1, 2","1_1, 2_1",NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF563EHM/, /files/ENCFF302ROS/, /files/ENCFF269URO/, /files/ENCFF413UKK/, /files/ENCFF902OZA/, /files/ENCFF467UOO/",53192,"Gene Yeo, UCSD",af3aa5df326ffd258cec7648e6fc1460,NaN,https://www.encodeproject.org/files/ENCFF612HOP/@@download/ENCFF612HOP.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/12/03/74424fe3-6c3e-4ba5-96ae-cb4515b364b5/ENCFF612HOP.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/12/03/74424fe3-6c3e-4ba5-96ae-cb4515b364b5/ENCFF612HOP.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN
11,ENCFF028GAJ,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR734ZHL,eCLIP,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTP3-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,"1, 2","1_1, 2_1",NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF826UUS/, /files/ENCFF269URO/, /files/ENCFF484NSW/, /files/ENCFF090UAF/, /files/ENCFF106YFV/, /files/ENCFF612HAQ/",472,"Gene Yeo, UCSD",f47468af5dd2162f89ec55589650f819,NaN,https://www.encodeproject.org/files/ENCFF028GAJ/@@download/ENCFF028GAJ.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/12/03/eb2a782f-07df-4247-8183-fa39ebe7faa6/ENCFF028GAJ.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/12/03/eb2a782f-07df-4247-8183-fa39ebe7faa6/ENCFF028GAJ.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN
17,ENCFF783INO,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR964VOX,eCLIP,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTP18-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,"1, 2","1_1, 2_1",NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF211AAW/, /files/ENCFF353ULN/, /files/ENCFF503MUZ/, /files/ENCFF269URO/, /files/ENCFF046FNK/, /files/ENCFF026UJY/",3716,"Gene Yeo, UCSD",5297d741e7e066646b1fd981f9ddd8ef,NaN,https://www.encodeproject.org/files/ENCFF783INO/@@download/ENCFF783INO.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/12/03/2d06de07-5042-4ce3-bad4-a847956533b5/ENCFF783INO.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/12/03/2d06de07-5042-4ce3-bad4-a847956533b5/ENCFF783INO.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN
23,ENCFF323PUC,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR018WPY,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AQR-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,"1, 2","1_1, 2_1",NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF073PST/, /files/ENCFF269URO/, /files/ENCFF947JHV/, /files/ENCFF882PEQ/, /files/ENCFF636MSJ/, /files/ENCFF217IZI/",234555,"Gene Yeo, UCSD",f0e433d02e4d6f4aef0a663033b98a0a,NaN,https://www.encodeproject.org/files/ENCFF323PUC/@@download/ENCFF323PUC.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/12/03/d49c8a68-b2be-4a1f-8adc-9cd784e6a73c/ENCFF323PUC.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/12/03/d49c8a68-b2be-4a1f-8adc-9cd784e6a73c/ENCFF323PUC.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,mixed read lengths,NaN,NaN
29,ENCFF644EIR,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR488JKQ,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTP18-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,"1, 2","1_1, 2_1",NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF840HCE/, /files/ENCFF511WWE/, /files/ENCFF146BNV/, /files/ENCFF444SAJ/, /files/ENCFF978BQG/, /files/ENCFF269URO/",1346,"Gene Yeo, UCSD",f2302b8ec8ef5f33e74ea3eaf63d30fc,NaN,https://www.encodeproject.org/files/ENCFF644EIR/@@download/ENCFF644EIR.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/12/03/5943953f-29ef-4d8a-b95c-4334b23736f7/ENCFF644EIR.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/12/03/5943953f-29ef-4d8a-b95c-4334b23736f7/ENCFF644EIR.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN

## Get `shRNA` and `eCLIP RBP` Intersection 

Obviously done per cell line.

In [6]:
# dict where key is cell line and value is RBPs with both eCLIP and shRNA data
matching_rbps = {}

# for each cell line 
for cell_line in cell_lines: 
    
    # get all RBPs for shRNA data that match that cell line 
    shrna_rbps = set(shrna_metadata[shrna_metadata["Biosample term name"]==cell_line]["Experiment target"].to_list())
    len(shrna_rbps) 
    
    # get all RBPs for eCLIP in that cell line 
    eclip_rbps = set(eclip_metadata[eclip_metadata["Biosample term name"]==cell_line]["Experiment target"].to_list())
    len(eclip_rbps)
    
    "RBPs that are only in eCLIP and not shRNA" 
    print(eclip_rbps.difference(shrna_rbps))
    
    # get sorted list of RBPs in both shRNA and eCLIP for that cell line 
    matching_rbps[cell_line] = sorted(list(shrna_rbps.intersection(eclip_rbps)))

213

139

'RBPs that are only in eCLIP and not shRNA'

{'ZNF800-human', 'ELAVL1-human', 'MORC2-human', 'EXOSC5-human', 'DDX6-human', 'RPS11-human', 'ZNF622-human', 'DDX43-human', 'RPS3-human', 'PRPF8-human', 'RPS6-human', 'EIF4E-human', 'ZC3H11A-human', 'DDX21-human', 'NIPBL-human', 'ADAT1-human', 'ELAC2-human', 'EXOSC10-human', 'FXR2-human', 'RNF187-human', 'GARS-human', 'APEX1-human', 'NOLC1-human', 'SDAD1-human', 'DDX42-human', 'SF3B1-human', 'METTL1-human', 'RYBP-human', 'GNL3-human', 'SRSF7-human', 'XRCC6-human', 'YWHAG-human', 'DGCR8-human', 'NPM1-human', 'SRSF9-human', 'IGF2BP1-human', 'TRA2A-human', 'SAFB-human'}

233

105

'RBPs that are only in eCLIP and not shRNA'

{'ZNF800-human', 'PABPN1-human', 'EXOSC5-human', 'WDR43-human', 'RBM5-human', 'RPS3-human', 'EIF3H-human', 'STAU2-human', 'ZC3H11A-human', 'AGGF1-human', 'FXR2-human', 'NOLC1-human', 'SDAD1-human', 'SRSF7-human', 'POLR2G-human', 'DGCR8-human', 'CDC40-human', 'DROSHA-human', 'IGF2BP1-human', 'SAFB-human'}

In [7]:
# for each cell line, show RBPs with both 
# eCLIP and shRNA in a given cell line 
for cell_line in matching_rbps: 
    cell_line 
    
    len(matching_rbps[cell_line])
    print(matching_rbps[cell_line])

'K562'

101

['AARS-human', 'AATF-human', 'ABCF1-human', 'AGGF1-human', 'AKAP1-human', 'AKAP8L-human', 'APOBEC3C-human', 'AQR-human', 'BUD13-human', 'CPEB4-human', 'CPSF6-human', 'CSTF2T-human', 'DDX1-human', 'DDX24-human', 'DDX3X-human', 'DDX47-human', 'DDX51-human', 'DDX52-human', 'DDX55-human', 'DHX30-human', 'DROSHA-human', 'EEF2-human', 'EFTUD2-human', 'EIF3G-human', 'EIF4G2-human', 'EWSR1-human', 'FAM120A-human', 'FASTKD2-human', 'FMR1-human', 'FTO-human', 'FUS-human', 'FXR1-human', 'GEMIN5-human', 'GPKOW-human', 'GRWD1-human', 'GTF2F1-human', 'HLTF-human', 'HNRNPA1-human', 'HNRNPC-human', 'HNRNPK-human', 'HNRNPL-human', 'HNRNPM-human', 'HNRNPU-human', 'HNRNPUL1-human', 'IGF2BP2-human', 'ILF3-human', 'KHDRBS1-human', 'KHSRP-human', 'LARP4-human', 'LARP7-human', 'LIN28B-human', 'LSM11-human', 'MATR3-human', 'MBNL1-human', 'METAP2-human', 'MTPAP-human', 'NCBP2-human', 'NONO-human', 'NSUN2-human', 'PABPC4-human', 'PCBP1-human', 'PHF6-human', 'PPIL4-human', 'PTBP1-human', 'PUM1-human', 'PUM2-human', 'PUS1-human', 'QKI-human', 'RBFOX2-human', 'RBM15-human', 'RBM22-human', 'RPS10-human', 'SAFB2-human', 'SBDS-human', 'SERBP1-human', 'SF3B4-human', 'SLBP-human', 'SLTM-human', 'SMNDC1-human', 'SND1-human', 'SRSF1-human', 'SSB-human', 'SUPV3L1-human', 'TAF15-human', 'TARDBP-human', 'TBRG4-human', 'TIA1-human', 'TROVE2-human', 'U2AF1-human', 'U2AF2-human', 'UCHL5-human', 'UPF1-human', 'UTP18-human', 'UTP3-human', 'WDR3-human', 'WDR43-human', 'WRN-human', 'XRN2-human', 'YBX3-human', 'ZC3H8-human', 'ZRANB2-human']

'HepG2'

85

['AKAP1-human', 'AQR-human', 'BCCIP-human', 'BCLAF1-human', 'BUD13-human', 'CSTF2-human', 'CSTF2T-human', 'DDX3X-human', 'DDX52-human', 'DDX55-human', 'DDX59-human', 'DDX6-human', 'DHX30-human', 'DKC1-human', 'EFTUD2-human', 'EIF3D-human', 'FAM120A-human', 'FASTKD2-human', 'FKBP4-human', 'FTO-human', 'FUBP3-human', 'FUS-human', 'G3BP1-human', 'GRSF1-human', 'GRWD1-human', 'GTF2F1-human', 'HLTF-human', 'HNRNPA1-human', 'HNRNPC-human', 'HNRNPK-human', 'HNRNPL-human', 'HNRNPM-human', 'HNRNPU-human', 'HNRNPUL1-human', 'IGF2BP3-human', 'ILF3-human', 'KHSRP-human', 'LARP4-human', 'LARP7-human', 'LIN28B-human', 'LSM11-human', 'MATR3-human', 'NCBP2-human', 'NIP7-human', 'NKRF-human', 'NOL12-human', 'NSUN2-human', 'PCBP1-human', 'PCBP2-human', 'PPIG-human', 'PRPF4-human', 'PRPF8-human', 'PTBP1-human', 'QKI-human', 'RBFOX2-human', 'RBM15-human', 'RBM22-human', 'SF3A3-human', 'SF3B4-human', 'SFPQ-human', 'SLTM-human', 'SMNDC1-human', 'SND1-human', 'SRSF1-human', 'SRSF9-human', 'SSB-human', 'SUB1-human', 'SUGP2-human', 'SUPV3L1-human', 'TAF15-human', 'TARDBP-human', 'TBRG4-human', 'TIA1-human', 'TIAL1-human', 'TRA2A-human', 'TROVE2-human', 'U2AF1-human', 'U2AF2-human', 'UCHL5-human', 'UPF1-human', 'UTP18-human', 'XPO5-human', 'XRCC6-human', 'XRN2-human', 'YBX3-human']

## Get All Peaks per Cell Line

In [8]:
# key is cell line and value is all peaks 
# for RBPs with eCLIP in that cell line
all_peaks = {}

# for each cell line 
for cell_line in cell_lines: 
    
    # list of dataframes that will be concatted to 
    # get all RBPs peaks in a given cell line 
    concat_peaks = []
    
    # for each RBP in both assays 
    for rbp in matching_rbps[cell_line]: 
        # subset eCLIP to cell line and RBP 
        tmp_metadata = eclip_metadata[
            (eclip_metadata["Biosample term name"]==cell_line) & 
            (eclip_metadata["Experiment target"]==rbp)
        ]
        
        # for the few cases where they re-did the eCLIP
        if tmp_metadata.index.size!=1: 
            # get the newest eCLIP experiment
            tmp_metadata = tmp_metadata.sort_values("Experiment date released", ascending=False).head(n=1)
                                                 
        assert tmp_metadata.index.size==1, tmp_metadata
        
        # get the file associated with that cell line and RBP 
        file = glob.glob(
            "/project/PlatigLab/data/ENCORE/eCLIP/encode/peaks/{}.bed.gz".format(tmp_metadata.iloc[0,0])
        )
        assert len(file)==1
        
        # load eCLIP peaks file 
        tmp_peaks = pd.read_csv(
            file[0], 
            compression="gzip", 
            sep="\t", 
            header=None
        )
        
        # since we are concatenatting all peaks together downstream
        # make sure to identify peaks by their rbp_cell-line_filtering methods
        tmp_peaks[3] = rbp.split("-")[0] + "_" + cell_line + "_IDR"
        
        # only take the first 6 columns to create a BED6 file 
        tmp_peaks = tmp_peaks[
            list(range(0,6))
        ]
        
        # add this rbps peaks to the list of peaks for the cell line 
        concat_peaks.append(tmp_peaks)
        
    # concattenate all the peaks for the whole cell line 
    all_peaks[cell_line] = pd.concat(concat_peaks)

## Output Cell-Line-Specific Peaks as `BED` File

In [9]:
# for each cell line 
for cell_line in cell_lines: 
    tmp_df = all_peaks[cell_line] 
    
    # print number of rows and first few lines 
    tmp_df.index.size 
    tmp_df.head()
    
    # output as BED file 
    tmp_df.to_csv(
        "../output/bedtools_input/{}_all_peaks.bed".format(cell_line),
        sep="\t", 
        index=False, 
        header=False
    )

358745

       0         1         2              3     4  5
0  chr21   8401778   8401840  AARS_K562_IDR  1000  +
1  chr19   4035770   4035869  AARS_K562_IDR  1000  +
2  chr11  93721690  93721719  AARS_K562_IDR  1000  +
3  chr19   2270224   2270300  AARS_K562_IDR  1000  +
4   chrM     12167     12208  AARS_K562_IDR  1000  +

415279

       0          1          2                3     4  5
0  chr17    4937481    4937632  AKAP1_HepG2_IDR  1000  -
1  chr22   38735168   38735229  AKAP1_HepG2_IDR  1000  -
2   chr7  158395622  158395681  AKAP1_HepG2_IDR  1000  -
3   chr1  204126917  204127045  AKAP1_HepG2_IDR  1000  +
4  chr20    3252306    3252445  AKAP1_HepG2_IDR  1000  -