# Matrixize `rMATS` Data

## Purpose: 

Take all `rMATS` files for `shRNA RBP Knockdowns` where `eCLIP` data is also available. 

Use those to create cell line and splice-type specific matrices of either counts or inclusion levels, which are then outputted.

## Packages and Options

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import glob, os 
import numpy as np 
import sys

## Literals

In [2]:
# eclip metadata file 
eclip_metadata_file = "/project/PlatigLab/data/eCLIP/encode/metadata.tsv"

# shrna metadata link 
shrna_metadata_link = "https://www.encodeproject.org/metadata/?assay_title=shRNA+RNA-seq&replicates.library.biosample.donor.organism.scientific_name=Homo+sapiens&files.file_type=fastq&status=released&type=Experiment"

# input data folder 
input_data_folder = "/project/PlatigLab/data/collaborators/BWH/encode_shRNA_processed_data/"

In [3]:
cell_lines = ["HepG2", "K562"]
splice_types = ["A3SS", "A5SS", "SE", "MXE", "RI"]

# directory name to pull either batch-corrected or not batch-corrected files 
norm_or_not_pattern = "MATS_output"

# choose whether you want skipping and junction counts to be summated or not
get_total_counts = True 

# whether you want inclevel vs IJC/SJC counts
get_inclevel=True

# order of samples if junction and skipping counts are SUMMATED 
summated_sample_ordering = ["KO_Sample_1", "KO_Sample_2", "CTRL_Sample_1", "CTRL_Sample_2"]
# order of samples if junction and skipping counts are NOT SUMMATED
non_summated_sample_ordering = ["KO_Sample_1_IJC", "KO_Sample_2_IJC", "KO_Sample_1_SJC", "KO_Sample_2_SJC", "CTRL_Sample_1_IJC", "CTRL_Sample_2_IJC", "CTRL_Sample_1_SJC", "CTRL_Sample_2_SJC"]

# folder for where to output data 
output_data_folder = "../output/hg38/summated-counts/"

## Load `eCLIP` and `shRNA KD` Metadata

#### `eCLIP`

In [4]:
eclip_metadata = pd.read_csv(eclip_metadata_file, sep="\t")

# subset to hg38 data and those data that are released
eclip_metadata = eclip_metadata[
    (eclip_metadata["File assembly"]=="GRCh38") & 
    (eclip_metadata["File analysis status"]=="released")
]

eclip_metadata.head(2)

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
2,ENCFF467UOO,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR322HHA,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIAL1-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,2,2_1,NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF413UKK/, /files/ENCFF563EHM/",958646,"Gene Yeo, UCSD",e6cf0562482c6e05672bff84b530895f,NaN,https://www.encodeproject.org/files/ENCFF467UOO/@@download/ENCFF467UOO.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/04/29/b11f2b95-857f-4507-ab1d-ecc12b97e121/ENCFF467UOO.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/04/29/b11f2b95-857f-4507-ab1d-ecc12b97e121/ENCFF467UOO.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN
3,ENCFF302ROS,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR322HHA,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIAL1-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,1,1_1,NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF902OZA/, /files/ENCFF563EHM/",1232263,"Gene Yeo, UCSD",f779f629ad64cfe93ab1ba9e5979de4c,NaN,https://www.encodeproject.org/files/ENCFF302ROS/@@download/ENCFF302ROS.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/04/29/24e80d04-74d3-4698-bafa-8de5abc182a8/ENCFF302ROS.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/04/29/24e80d04-74d3-4698-bafa-8de5abc182a8/ENCFF302ROS.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN

#### `shRNA Knockdown RNA-Seq`

In [5]:
# link sent to everyone as the metadata file we will use 
knockdown_metadata = pd.read_csv(
    shrna_metadata_link, 
    sep="\t",
)

# subset knockdown to only poly mRNA samples
knockdown_metadata = knockdown_metadata[knockdown_metadata["Library made from"]=="polyadenylated mRNA"]

knockdown_metadata.head(2)

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
0,ENCFF698IDD,fastq,fastq,NaN,reads,NaN,ENCSR363QIA,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/9128/'], '@type': ['Target', 'Item'], 'name': 'PRPF4-human', 'label': 'PRPF4', '@id': '/targets/PRPF4-human/', 'title': 'PRPF4 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': 'd4ef9d73-126d-4102-a4d3-d276240f29f3', 'status': 'released'}",NaN,NaN,NaN,PRPF4-human,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2021-01-28,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,1,/files/ENCFF489FFV/,NaN,NaN,1135692401,"Brenton Graveley, UConn",740fa1390c95fc92f6f9a364718227a9,SRA:SRR14844613,https://www.encodeproject.org/files/ENCFF698IDD/@@download/ENCFF698IDD.fastq.gz,NaN,Illumina HiSeq 2500,"/files/ENCFF475HIX/, /files/ENCFF687PMR/",released,s3://encode-public/2018/09/01/4e406561-c77e-4bbb-be0e-71c180f376d4/ENCFF698IDD.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2018/09/01/4e406561-c77e-4bbb-be0e-71c180f376d4/ENCFF698IDD.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing compliant biosample characterization,NaN,NaN
1,ENCFF937SOU,fastq,fastq,NaN,reads,NaN,ENCSR363QIA,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/9128/'], '@type': ['Target', 'Item'], 'name': 'PRPF4-human', 'label': 'PRPF4', '@id': '/targets/PRPF4-human/', 'title': 'PRPF4 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': 'd4ef9d73-126d-4102-a4d3-d276240f29f3', 'status': 'released'}",NaN,NaN,NaN,PRPF4-human,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2021-01-28,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,2,/files/ENCFF594HCT/,NaN,NaN,831391922,"Brenton Graveley, UConn",9da79a0c8acc4dc2882e5a0827d52285,SRA:SRR14844616,https://www.encodeproject.org/files/ENCFF937SOU/@@download/ENCFF937SOU.fastq.gz,NaN,Illumina HiSeq 2500,"/files/ENCFF860QVJ/, /files/ENCFF204IKW/",released,s3://encode-public/2018/09/01/a77e84a2-4b36-4130-837b-1374771e69c9/ENCFF937SOU.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2018/09/01/a77e84a2-4b36-4130-837b-1374771e69c9/ENCFF937SOU.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing compliant biosample characterization,NaN,NaN

## Get RBPs w/ Both `eCLIP` and `shRNA` Data

In [6]:
# dictionary by cell line and splice type of the files to load
input_data_files = {}

# for each cell line and splice type 
for cell_line in cell_lines: 
    # initialize cell line sub dict 
    input_data_files[cell_line] = {}
    
    # subset eclip and knockdown metadata to cell type 
    tmp_eclip = eclip_metadata[eclip_metadata["Biosample term name"]==cell_line]
    tmp_shrna = knockdown_metadata[knockdown_metadata["Biosample term name"]==cell_line]
    
    # subset knockdown metdata to eclip data that has the RBPs
    # get all the targets and subset to the unique RBPs
    common_rbps = tmp_shrna[
        tmp_shrna["Experiment target"].isin(
            tmp_eclip["Experiment target"]
        )
    ]["Experiment target"].unique().tolist()
    
    # remove the "-human" tag at the end of RBP names
    common_rbps = [rbp.split("-")[0] for rbp in common_rbps]
    
    # for eaccommon_rbpsh splice type 
    for splice_type in splice_types: 
        
        # glob for the cell line and splice type of the data files 
        tmp_data_files = sorted(
            glob.glob(
                "{}/*{}*/*{}*".format(input_data_folder, cell_line, splice_type), 
                recursive=True
            )
        )
            
        # remove files from that have the tag "Transfection" because these files are not polyadenylated RNA 
        # also remove any files whose RBP is not included in the common RBPs
        input_data_files[cell_line][splice_type] = [file for file in tmp_data_files if not "Transfection" in file and file.split("/")[-2].split("-")[0] in common_rbps ]
        
        len(input_data_files[cell_line][splice_type])

85

85

85

85

85

101

101

101

101

101

## Matrixization Algorithm

In [7]:
def matrixize_rmats_table(file = None, get_total_counts=None, inclevel=None):
    """
    Takes all rMATS files and extracts genomic features from them to create a matrix using junction and skipping counts. 
    
    Parameters:
        files (list): list of file paths where the rMATS files can be found (default = None)
        get_total_counts (bool): whether to sum junction and skipping counts or keep them separate (default = None)   
        inclevel (bool): if True, take the inclusion level and if False use the SJC/IJC counts 
    
    Returns: 
        matrix (pandas.DataFrame): a Pandas DataFrame where features are columns and rows are samples
        
    """
    
    assert file!=None and get_total_counts!=None and inclevel!=None
    
     # need to extract rbp and cell line from path 
    rbp_cell_line = None

    for path_part in file.split("/"): 
        # save the entire line that has the rbp-batch-cell_line nomenclature
        if "HepG2" in path_part or "K562" in path_part: 
            rbp_cell_line = path_part 

    assert rbp_cell_line != None, rbp_cell_line
    
    # dictionary where genomic position feature is key and value is sub-dict 
    # sub-dict has key for sample and value of that is the counts 
    # NOTE: if "get_total_counts=False", you will have double the sampls since "SJC" and "IJC" will be kept separate. 
    matrix_dict = {}

    # load as dataframe 
    tmp_df = pd.read_csv(file,sep="\t")

    # get index position of concatenation start string 
    # we are making strings from the exact chromosome, strand and genomic positions 
    # to do so, we need to concatenate all rows after "chr" column until the "ID.1" column 
    # this is a known assumption that all the chromosome, strand, and genomic position information 
    # is between the "chr" column upto and excluding "ID.1" column
    concatenation_start = tmp_df.columns.tolist().index("chr")
    concatenation_end = tmp_df.columns.tolist().index("ID.1")

    # take all columns to make feature name 
    # convert them to strings 
    # concatenate each column row-wise with "_" as delimiter
    # (e.g. chr17_-_62496792_62497000_62496792_62496891_62498127_62498187)
    tmp_df["Feature"] = tmp_df.iloc[
        :,concatenation_start:concatenation_end
    ].astype("str").apply(
        lambda x: '_'.join(x.values.tolist()), axis=1
    )
    
    # get inclevel columns
    if inclevel: 
        count_columns = ["IncLevel1", "IncLevel2"]
    # get IJC/SJC counts columns
    elif not inclevel: 
        count_columns = ["IJC_SAMPLE_1", "SJC_SAMPLE_1", "IJC_SAMPLE_2", "SJC_SAMPLE_2"]
        
    # take all the counts that are comma separated per column 
    # and combine them into one column that is entirely comma-separated 
    # e.g. 780,750	758,759	260,253	543,571	 becomes 780,750,758,759,260,253,543,571
    tmp_df["Counts"] = tmp_df[count_columns].astype(str).apply(
        lambda x: ",".join(x.values.tolist()),axis=1
    )

    # subset to the columns involving features and counts 
    tmp_df = tmp_df[["Feature", "Counts"]]

    # for each feature we are now going to sum up the skipping and inclusion junction counts
    # there are 8 numbers corresponding to 4 samples
    # we are using the sample count summation indices dictionary that tells us which indices to pull from list
    for row in tmp_df.itertuples():
        
        feature = row[1]
        matrix_dict[feature] = {}
        
        numbers = row[2]
        numbers = numbers.split(',') 
        
        # get inclevel values 
        if inclevel: 
            for sample_name, ratio in zip(summated_sample_ordering, numbers): 
                
                sample_name = "{}-{}".format(rbp_cell_line, sample_name)
                
                # if NA then save as Numpy NaN
                if ratio =="NA": 
                    matrix_dict[feature][sample_name] = np.nan
                # just save the inclevel value
                else: 
                    matrix_dict[feature][sample_name] = ratio
                                
        # get actual counts (i.e. SJC/IJC)
        elif not inclevel: 

            # for each feature, we need to sum the skipping and inclusion counts 
            # 4 samples so 4 features
            if get_total_counts: 
                # get list of length 4  
                summations = summate_counts(numbers)

                assert len(summations)==4 and len(summated_sample_ordering)==4

                # assign each value in their respective order with correct sample naming
                for sample_name, value in zip(summated_sample_ordering, summations): 

                    # include RBP, batch, and cell line info in the sample name 
                    sample_name = "{}-{}".format(rbp_cell_line, sample_name)

                    matrix_dict[feature][sample_name] = value    


            # OR ELSE for each feature, separate skipping and inculsion counts 
            # 4 samples * (SJC/IJC) = 8 features 
            elif not get_total_counts:

                assert len(numbers)==8 and len(non_summated_sample_ordering)==8

                # assign each value in correct order 
                for sample_name, value in zip(non_summated_sample_ordering, numbers): 

                    # include RBP, batch, and cell line info in the sample name 
                    sample_name = "{}-{}".format(rbp_cell_line, sample_name)

                    matrix_dict[feature][sample_name] = value   
    
    # return dataframe where features are the index and columns are samples 
    return pd.DataFrame.from_dict(
        matrix_dict, 
        orient="index"
    )
    

def summate_counts(numbers): 
    """
    Parameters: 
        numbers (list): list of numbers to be summated in particular order
    
    Returns: 
        summation_list (list): list of numbers that have come as a result of correct summations
    
    """
        
    # list to save the summations 
    summation_list = []
    
    # which list indices should be pulled out for each sample
    # when summating and finding out counts per sample per feature 
    sample_count_summation_indices = {
        "KO_1": [0,2],
        "KO_2": [1,3],
        "CTRL_1": [4,6],
        "CTRL_2": [5,7],
    }
                
    # to get counts for each sample
    # pull the correct indices corresponding to junction and skipping counts for that sample 
    # sum that up and save those results in dictionary
    for sample in sample_count_summation_indices: 
        summation_list.append(
            sum(
                [int(numbers[index]) for index in sample_count_summation_indices[sample] ]
            )
        
        )
        
    return summation_list

## Validation of Matrix Creation Algorithm

In [8]:
random_file = '/project/PlatigLab/data/collaborators/BWH/encode_shRNA_processed_data/AATF-BGHLV14-HepG2/A3SS.MATS.JC.txt'

original_df = pd.read_csv(random_file, sep="\t")

original_df.iloc[130:132, :]

,ID,GeneID,geneSymbol,chr,strand,longExonStart_0base,longExonEnd,shortES,shortEE,flankingES,flankingEE,ID.1,IJC_SAMPLE_1,SJC_SAMPLE_1,IJC_SAMPLE_2,SJC_SAMPLE_2,IncFormLen,SkipFormLen,PValue,FDR,IncLevel1,IncLevel2,IncLevelDifference
130,207,ENSG00000100197.21,CYP2D6,chr22,-,42127841,42127983,42127841,42127934,42128173,42128350,207,"3,0","1,0","4,3","0,0",148,99,1.0,1.0,"0.667,NA","1.0,1.0",-0.333
131,210,ENSG00000196419.12,XRCC6,chr22,+,41636112,41636251,41636235,41636251,41628117,41628230,210,"1549,1547","0,0","1317,1028","2,0",198,99,1.0,1.0,"1.0,1.0","0.997,1.0",0.002

In [9]:
matrixize_rmats_table(file = random_file, inclevel=True, get_total_counts=True).iloc[130:132,:]

,AATF-BGHLV14-HepG2-KO_Sample_1,AATF-BGHLV14-HepG2-KO_Sample_2,AATF-BGHLV14-HepG2-CTRL_Sample_1,AATF-BGHLV14-HepG2-CTRL_Sample_2
chr22_-_42127841_42127983_42127841_42127934_42128173_42128350,0.667,NaN,1.0,1.0
chr22_+_41636112_41636251_41636235_41636251_41628117_41628230,1.0,1.0,0.997,1.0

## Create All Matrices

In [10]:
all_matrices = {}

# for each cell line 
for cell_line in cell_lines: 
    
    all_matrices[cell_line] = {}
    
    # for each splice type 
    for splice_type in splice_types: 
        
        # dataframe for outer joining 
        join_df = pd.DataFrame()
        
        "{} {}".format(cell_line, splice_type)
        
        # for each rMATS table associated with this cell line and splice type
        for file in input_data_files[cell_line][splice_type]: 
            
            # convert rMATS table to matrix of counts 
            matrix = matrixize_rmats_table(
                file = file, 
                get_total_counts = get_total_counts, 
                inclevel=get_inclevel
            )
            
            if get_total_counts: 
                assert len(matrix.columns)==4
            elif not get_total_counts: 
                assert len(matrix.columns)==8
                
            join_df = join_df.join(matrix, how="outer")
        
        # check that number of samples is as expected
        if get_total_counts: 
            assert len(join_df.columns)==len(input_data_files[cell_line][splice_type])*4
        elif not get_total_counts: 
            assert len(join_df.columns)==len(input_data_files[cell_line][splice_type])*8
                    
        # save to dictionary 
        all_matrices[cell_line][splice_type] = join_df

'HepG2 A3SS'

'HepG2 A5SS'

'HepG2 SE'

'HepG2 MXE'

'HepG2 RI'

'K562 A3SS'

'K562 A5SS'

'K562 SE'

'K562 MXE'

'K562 RI'

## Find Duplicate Samples

#### Get preliminary dictionary with duplicated samples

In [13]:
# duplicate samples dictionary 
duplicated_dict = {}

# iterate through splice types and cell lines 
# initialize necessary subdicts
for cell_line in cell_lines: 
    duplicated_dict[cell_line] = {}
    
    for splice_type in splice_types:     
        "{} {}".format(cell_line, splice_type)

        
        # transpose so that features are columns and samples are rows 
        tmp_df = all_matrices[cell_line][splice_type].T
        tmp_df.columns.size
        
        # get the features that have no missing values and save as list 
        columns_to_keep = (tmp_df.notna().sum() / tmp_df.index.size)==1
        columns_to_keep = columns_to_keep[columns_to_keep==True].index.to_list()
        
        # subset original data to these non-NaN features
        tmp_df = tmp_df[columns_to_keep]
        tmp_df.columns.size
        
        # keep all the rows that are duplicated
        tmp_df = tmp_df[tmp_df.duplicated(keep=False)]    
        
        # group the rows by all columns and get dict of row values to samples
        # save to duplicate dict 
        duplicated_dict[cell_line][splice_type]= tmp_df.groupby(list(tmp_df)).groups

'HepG2 A3SS'

11488

344

'HepG2 A5SS'

7361

212

'HepG2 SE'

168043

1168

'HepG2 MXE'

36478

115

'HepG2 RI'

5654

335

'K562 A3SS'

12343

2480

'K562 A5SS'

8157

1492

'K562 SE'

200957

9940

'K562 MXE'

49286

871

'K562 RI'

5700

2411

### Validation of duplicated samples

Need to check whether each set of duplicated samples: 
* Are from the same batch
* Are the only set from that batch

In [14]:
# for each cell line and splice type 
for cell_line in cell_lines:     
    for splice_type in splice_types: 
        
        # each batch per set of duplicates saved 
        all_batches = []
        
        # for each group of duplicated samples 
        for key in duplicated_dict[cell_line][splice_type]: 
            
            # get batch identifier for each sample in list 
            # and assert that there is no more than 1 unique entry 
            batch_id = list(
                set(
                    [ID.split("-")[1] for ID in duplicated_dict[cell_line][splice_type][key].to_list()]
                )
            )
            assert len(batch_id)==1, batch_id

            # append batch id to list of batch ids for each group of duplicates 
            all_batches.append(batch_id[0])
                    
        # this makes sure that between each set of duplicated samples, no batch IDs are used twice
        # this is since the value_counts() should yield a batch ID no more than twice (1 for each control sample)
        # if so, you can say that a set of duplicated samples represents batch "X" control sample "y"
        batches_across_duplicates = pd.Series(all_batches).value_counts()
        batches_across_duplicates[batches_across_duplicates>2]

BGHLV12    4
BGHLV14    4
BGHLV17    3
Name: count, dtype: int64

BGHLV14    4
BGHLV12    4
BGHLV17    3
Name: count, dtype: int64

BGHLV14    4
BGHLV12    4
BGHLV17    3
Name: count, dtype: int64

BGHLV14    4
BGHLV12    4
BGHLV17    3
Name: count, dtype: int64

BGHLV12    4
BGHLV14    4
BGHLV17    3
Name: count, dtype: int64

BGKLV13    4
BGKLV24    4
BGKLV08    4
BGKLV25    4
BGKLV21    4
Name: count, dtype: int64

BGKLV13    4
BGKLV24    4
BGKLV08    4
BGKLV21    4
BGKLV25    4
Name: count, dtype: int64

BGKLV13    4
BGKLV24    4
BGKLV25    4
BGKLV21    4
BGKLV08    4
Name: count, dtype: int64

BGKLV24    4
BGKLV21    4
BGKLV13    4
BGKLV25    4
BGKLV08    4
Name: count, dtype: int64

BGKLV08    4
BGKLV13    4
BGKLV24    4
BGKLV21    4
BGKLV25    4
Name: count, dtype: int64

**THIS MEANS THAT NOT EVERY BATCH USED 2 CONTROL SAMPLES AND HENCE, ARE NOT THE CONTROLS FOR THE ENTIRE BATCH**

Across all cell lines and splice types and for each duplicated sample group: 
* Is there the same number of them across all combinations? (There should be)
* Do they contain the same set of samples across all combinations?

In [15]:
# for each cell line 
for cell_line in cell_lines:
    # take A5SS as an example to compare against all other splice types downstream 
    # pull out all duplicated sample groups 
    comparison_dict = duplicated_dict[cell_line]["A5SS"]
    control_duplicated_sample_groups = [comparison_dict[key].to_list() for key in comparison_dict]
    
    for splice_type in splice_types: 
        
        # make sure that the number of duplicate sample groups is the same
        assert len(comparison_dict.keys()) == len(duplicated_dict[cell_line][splice_type].keys())
        
        # for each group of duplicated samples in current iteration
        for key in duplicated_dict[cell_line][splice_type]: 
            # get list of duplicate sample group
            sample_group= duplicated_dict[cell_line][splice_type][key].to_list()
            
            # this makes sure that the exact list of duplicated sample groups is found 
            # in our "control" set of duplicated sample groups which ultimately ensures 
            # that the same samples are marked as duplicates across splice types 
            assert sample_group in control_duplicated_sample_groups

### Visual Validation that Duplicates are Actually Duplicates

Get some samples to visually look at

In [16]:
# transpose so that features are columns and samples are rows 
tmp_df = all_matrices["HepG2"]["A3SS"].T
tmp_df.columns.size

# get the features that have no missing values and save as list 
columns_to_keep = (tmp_df.notna().sum() / tmp_df.index.size)==1
columns_to_keep = columns_to_keep[columns_to_keep==True].index.to_list()

# subset original data to these non-NaN features
tmp_df = tmp_df[columns_to_keep]
tmp_df.columns.size

# keep all the rows that are duplicated
tmp_df = tmp_df[tmp_df.duplicated(keep=False)] 

# select 3 samples to compare 
tmp_df[
    tmp_df.index.isin(
        ['DDX52-BGHLV16-HepG2-CTRL_Sample_2','EEF2-BGHLV16-HepG2-CTRL_Sample_2','EFTUD2-BGHLV16-HepG2-CTRL_Sample_2']
    )
].iloc[:, 1:100]

11488

344

,chr10_-_5794884_5795019_5794884_5794989_5796762_5796862,chr10_-_71821875_71822016_71821875_71822007_71825836_71825893,chr11_+_63988626_63988752_63988653_63988752_63988336_63988398,chr11_+_65113490_65113594_65113523_65113594_65113219_65113414,chr11_+_65920547_65920662_65920568_65920662_65920342_65920462,chr11_+_66067945_66068045_66067948_66068045_66063627_66063729,chr11_+_67611402_67611569_67611476_67611569_67610994_67611207,chr11_+_67611402_67611569_67611521_67611569_67610994_67611207,chr11_+_75402303_75402446_75402351_75402446_75401639_75401733,chr11_+_758949_759057_759008_759057_755878_756002,chr11_+_8683862_8684081_8684005_8684081_8683201_8683265,chr11_+_8683960_8684081_8684005_8684081_8683201_8683265,chr11_+_8684685_8684892_8684717_8684892_8684005_8684081,chr11_+_8684685_8684892_8684822_8684892_8684005_8684081,chr11_+_8684717_8684892_8684822_8684892_8684005_8684081,chr11_-_10799551_10799756_10799551_10799609_10800089_10800348,chr11_-_10805906_10806047_10805906_10806010_10807254_10807381,chr11_-_119017361_119017545_119017361_119017433_119017957_119018053,chr11_-_123060115_123060268_123060115_123060211_123060592_123060798,chr11_-_17075096_17075197_17075096_17075163_17075453_17075623,chr11_-_1752787_1753670_1752787_1753661_1753802_1753901,chr11_-_1753802_1753901_1753802_1753880_1753993_1754138,chr11_-_2133516_2133674_2133516_2133665_2135366_2135529,chr11_-_61964986_61965112_61964986_61965105_61965368_61965515,chr11_-_64317057_64317147_64317057_64317132_64317263_64317365,chr11_-_65121499_65121644_65121499_65121539_65121738_65121821,chr12_+_130874545_130874733_130874550_130874733_130873002_130873128,chr12_+_49758351_49758480_49758382_49758480_49758226_49758275,chr12_+_53021715_53021860_53021805_53021860_53019909_53020026,chr12_+_53298018_53298150_53298044_53298150_53297849_53297924,chr12_+_53459799_53461143_53461014_53461143_53459271_53459403,chr12_+_53462480_53462567_53462492_53462567_53461014_53461143,chr12_+_53468776_53468832_53468779_53468832_53467804_53467843,chr12_+_56134079_56134181_56134109_56134181_56133780_56133873,chr12_+_56158680_56158711_56158683_56158711_56158355_56158404,chr12_+_56159497_56159622_56159586_56159622_56158683_56158711,chr12_+_56159586_56159730_56159622_56159730_56158683_56158711,chr12_+_56159586_56160148_56159974_56160148_56158683_56158711,chr12_+_56159974_56160148_56160024_56160148_56159586_56159622,chr12_+_57512235_57512353_57512302_57512353_57512007_57512103,chr12_+_57716088_57716193_57716091_57716193_57715759_57715970,chr12_+_6769843_6769999_6769920_6769999_6769602_6769674,chr12_+_95476070_95476178_95476142_95476178_95474151_95474330,chr12_-_120198553_120198739_120198553_120198631_120198853_120199000,chr12_-_120198553_120198770_120198553_120198631_120198853_120199000,chr12_-_120198553_120198770_120198553_120198739_120198853_120199000,chr12_-_120200729_120200891_120200729_120200831_120201082_120201211,chr12_-_121328315_121328497_121328315_121328458_121330582_121330672,chr12_-_121849686_121849938_121849686_121849790_121854702_121854792,chr12_-_53669870_53670114_53669870_53669948_53672575_53672645,chr12_-_56275001_56275131_56275001_56275048_56275995_56276195,chr12_-_56275995_56276195_56275995_56276143_56282419_56282608,chr12_-_56610408_56610539_56610408_56610517_56611572_56611633,chr12_-_56714601_56714687_56714601_56714675_56724451_56724523,chr12_-_56714601_56714703_56714601_56714687_56724451_56724523,chr12_-_56724451_56724549_56724451_56724523_56725262_56725299,chr12_-_6581290_6581388_6581290_6581385_6581648_6581814,chr12_-_6583197_6583378_6583197_6583375_6587383_6587559,chr13_+_113637619_113637896_113637817_113637896_113636533_113636700,chr13_-_45333470_45337553_45333470_45337388_45338659_45338776,chr14_+_23641665_23643219_23643151_23643219_23639793_23639895,chr14_+_24237041_24237152_24237070_24237152_24235966_24236140,chr14_+_35312862_35313059_35312880_35313059_35310739_35310895,chr14_+_69768603_69768674_69768612_69768674_69768137_69768282,chr14_+_77717495_77717598_77717501_77717598_77715771_77715879,chr14_-_21211405_21211566_21211405_21211563_21211809_21211923,chr14_-_21263310_21263582_21263310_21263336_21269297_21269425,chr14_-_21263310_21263829_21263310_21263336_21269297_21269442,chr14_-_21371873_21372044_21371873_21371970_21373337_21373430,chr14_-_23064104_23064257_23064104_23064221_23064354_23064485,chr14_-_23064354_23064488_23064354_23064485_23065965_23066008,chr14_-_23563583_23563638_23563583_23563609_23563715_23563856,chr14_-_24145709_24145772_24145709_24145752_24146207_24146240,chr14_-_24145709_24145896_24145709_24145752_24146207_24146240,chr14_-_24145709_24145896_24145709_24145772_24146207_24146240,chr14_-_24211410_24211592_24211410_24211512_24211679_24211829,chr14_-_35402393_35402663_35402393_35402534_35402770_35402859,chr14_-_67685014_67685204_67685014_67685165_67690211_67690421,chr15_+_24974287_24974456_24974310_24974456_24967931_24968082,chr15_+_24974310_24974456_24974386_24974456_24967931_24968082,chr15_+_24974310_24974456_24974397_24974456_24967931_24968082,chr15_+_41350987_41351129_41351032_41351129_41349097_41349241,chr15_+_41350990_41351129_41351032_41351129_41349097_41349241,chr15_+_43793686_43794046_43793709_43794046_43792974_43793083,chr15_+_78542482_78542645_78542575_78542645_78542176_78542219,chr15_-_56707081_56707150_56707081_56707143_56707262_56707306,chr15_-_58916934_58917020_58916934_58916999_58932355_58932443,chr15_-_68787412_68787535_68787412_68787495_68787769_68787919,chr16_+_28714320_28714446_28714350_28714446_28713908_28714098,chr16_+_31183857_31184002_31183860_31184002_31182512_31182664,chr16_+_31189119_31189226_31189122_31189226_31188324_31188357,chr16_+_85804936_85805104_85804940_85805104_85801204_85801278,chr16_+_89561226_89561751_89561595_89561751_89560939_89561063,chr16_-_11841694_11841820_11841694_11841817_11841906_11842000,chr16_-_11896557_11896785_11896557_11896782_11897839_11897881,chr16_-_18788062_18788142_18788062_18788105_18788980_18789118,chr16_-_18788062_18788159_18788062_18788105_18788980_18789118,chr16_-_18788062_18788159_18788062_18788142_18788980_18789118,chr16_-_1962496_1962909_1962496_1962656_1963148_1963256
DDX52-BGHLV16-HepG2-CTRL_Sample_2,0.996,0.003,0.011,0.969,0.015,0.991,1.0,0.875,0.005,0.996,0.003,0.003,0.0,0.99,0.995,0.99,0.996,0.993,0.992,0.992,0.994,0.977,0.216,0.97,0.978,0.995,0.995,0.003,0.01,0.007,0.012,0.4,0.819,0.089,0.024,0.005,0.999,0.989,0.946,0.88,0.323,0.06,0.939,0.999,0.998,0.003,0.068,0.74,0.009,0.01,0.938,0.969,0.007,0.985,0.005,0.044,0.981,0.928,0.126,0.001,0.225,0.008,0.002,0.988,1.0,0.958,0.079,0.18,0.99,0.856,0.772,0.955,0.993,0.983,0.209,0.996,0.974,0.975,0.0,0.994,0.987,0.579,0.39,0.01,0.977,1.0,0.061,0.974,0.133,0.651,0.01,0.997,0.975,0.962,0.806,0.996,0.985,0.003,0.999
EFTUD2-BGHLV16-HepG2-CTRL_Sample_2,0.992,0.001,0.007,0.976,0.024,1.0,1.0,0.866,0.003,0.967,0.008,0.005,0.0,0.992,0.996,0.996,1.0,0.987,0.988,0.976,0.995,0.97,0.223,0.969,0.991,0.984,0.995,0.003,0.016,0.011,0.015,0.37,0.808,0.161,0.02,0.007,1.0,0.988,0.944,0.957,0.263,0.081,0.926,0.997,0.988,0.003,0.054,0.668,0.012,0.007,0.972,0.966,0.008,0.983,0.002,0.048,1.0,0.937,0.042,0.001,0.202,0.009,0.002,0.998,0.988,0.969,0.073,0.138,0.983,0.821,0.84,0.938,0.994,0.986,0.216,1.0,0.988,0.981,0.0,0.993,0.979,0.601,0.428,0.008,0.983,0.519,0.036,0.974,0.079,0.671,0.016,0.992,0.97,0.936,0.744,0.995,0.984,0.002,0.998

## Create New Names to Label Control Samples

In [ ]:
# for each cell line, store new names for duplicate samples
new_sample_names = {}

# for each cell line
for cell_line in cell_lines:
    new_sample_names[cell_line] = {}
    
    # since we showcased that the duplicate sample groups are 
    # the same across splice types, we can just use 1 of the splice types
    # iterating through all duplicate sample groups for A3SS splice type 
    for key in duplicated_dict[cell_line]["A3SS"]: 
        
        # get RBPs involved in each group of duplicate samples
        rbps_involved = [sample.split("-")[0] for sample in duplicated_dict[cell_line]["A3SS"][key].to_list()]
        rbps_involved = "_".join(rbps_involved)

        # for each sample name
        for sample in duplicated_dict[cell_line]["A3SS"][key]: 
            
            # save new sample name as combination of RBPs involved and the rest of the suffix 
            # e.g. DDX52-BGHLV16-HepG2-CTRL_Sample_2 ---> DDX52_EEF2_EFTUD2_EIF3D_FAM120A_GEMIN5_METAP2_PA2G4_PKM2_RPS19_SERBP1_TROVE2-BGHLV16-HepG2-CTRL_Sample_2
            new_sample_names[cell_line][sample] = "{}-{}".format(
                rbps_involved, 
                "-".join(
                    sample.split("-")[1:]
                )
            )

## Update Original Matrices w/ New Sample Names

In [ ]:

# for each cell line and splice type 
for cell_line in cell_lines: 
    for splice_type in splice_types: 

        tmp_df = all_matrices[cell_line][splice_type].T
        
        tmp_df = tmp_df.rename(
            index= new_sample_names[cell_line]
        ) 

        tmp_df.index.size
        
        tmp_df = tmp_df[~tmp_df.index.duplicated(keep="first")]
        
        tmp_df.index.size
        
        tmp_df.T.to_csv(
            "{}/{}_{}.tsv.gz".format(
                output_data_folder, 
                cell_line, 
                splice_type
            ), 
            compression="gzip", 
            sep="\t"
        )