# Matrixize `rMATS` Data

## Purpose: 

Take all `rMATS` files for `shRNA RBP Knockdowns` (and optionally, where `eCLIP` data is also available). 

Use those to create cell line and splice-type specific matrices of either counts or inclusion levels, which are then outputted for downstream analysis

## Packages and Options

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import glob, os, sys
import numpy as np

## Literals

In [2]:
# eclip metadata file 
eclip_metadata_file = "../../../inputs/metadata/eclip_metadata.tsv"

# shrna metadata file 
shrna_metadata_file = "../../../inputs/metadata/ENCODE_shRNA_knockdown_FASTQ_metadata.tsv"

# input data folder 
input_data_folder = "/project/PlatigLab/data/collaborators/BWH/ENCODE_shRNA_RBP_KD/"

In [3]:
cell_lines = ["HepG2", "K562"]
splice_types = ["A3SS", "A5SS", "SE", "MXE", "RI"]


# directory name to pull either batch-corrected or not batch-corrected files 
norm_or_not_pattern = "MATS_output"

# choose whether you want skipping and junction counts to be summated or not
get_total_counts = True 

# whether you want inclevel vs IJC/SJC counts
get_inclevel=True

# whether to only look at RBPs that have eCLIP
eclip_intersection= False

# order of samples if junction and skipping counts are SUMMATED 
summated_sample_ordering = ["KO_Sample_1", "KO_Sample_2", "CTRL_Sample_1", "CTRL_Sample_2"]
# order of samples if junction and skipping counts are NOT SUMMATED
non_summated_sample_ordering = ["KO_Sample_1_IJC", "KO_Sample_2_IJC", "KO_Sample_1_SJC", "KO_Sample_2_SJC", "CTRL_Sample_1_IJC", "CTRL_Sample_2_IJC", "CTRL_Sample_1_SJC", "CTRL_Sample_2_SJC"]

# folder for where to output data 
output_data_folder = "../output/hg38/inclusion-level/"

## Load `eCLIP` and `shRNA KD` Metadata

#### `eCLIP`

In [4]:
eclip_metadata = pd.read_csv(eclip_metadata_file, sep="\t")

# subset to hg38 data and those data that are released
eclip_metadata = eclip_metadata[
    (eclip_metadata["File assembly"]=="GRCh38") & 
    (eclip_metadata["File analysis status"]=="released")
]

eclip_metadata.head(2)

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
2,ENCFF467UOO,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR322HHA,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIAL1-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,2,2_1,NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF413UKK/, /files/ENCFF563EHM/",958646,"Gene Yeo, UCSD",e6cf0562482c6e05672bff84b530895f,NaN,https://www.encodeproject.org/files/ENCFF467UOO/@@download/ENCFF467UOO.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/04/29/b11f2b95-857f-4507-ab1d-ecc12b97e121/ENCFF467UOO.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/04/29/b11f2b95-857f-4507-ab1d-ecc12b97e121/ENCFF467UOO.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN
3,ENCFF302ROS,bed narrowPeak,bed,narrowPeak,peaks,GRCh38,ENCSR322HHA,eCLIP,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIAL1-human,RNA,NaN,NaN,NaN,ultraviolet irradiation,strand-specific,2018-08-30,ENCODE,NaN,see document,175-300,1,1_1,NaN,NaN,NaN,NaN,NaN,NaN,"/files/ENCFF902OZA/, /files/ENCFF563EHM/",1232263,"Gene Yeo, UCSD",f779f629ad64cfe93ab1ba9e5979de4c,NaN,https://www.encodeproject.org/files/ENCFF302ROS/@@download/ENCFF302ROS.bed.gz,NaN,NaN,NaN,released,s3://encode-public/2018/04/29/24e80d04-74d3-4698-bafa-8de5abc182a8/ENCFF302ROS.bed.gz,https://datasetencode.blob.core.windows.net/dataset/2018/04/29/24e80d04-74d3-4698-bafa-8de5abc182a8/ENCFF302ROS.bed.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,Lab custom GRCh38,released,NaN,NaN,NaN

#### `shRNA Knockdown RNA-Seq`

In [5]:
# link sent to everyone as the metadata file we will use 
knockdown_metadata = pd.read_csv(
    shrna_metadata_file, 
    sep="\t",
)
knockdown_metadata.index.size

# subset knockdown to only poly mRNA samples
knockdown_metadata = knockdown_metadata[knockdown_metadata["Library made from"]=="polyadenylated mRNA"]
knockdown_metadata["Experiment target"] = knockdown_metadata["Experiment target"].str.split("-").str[0]

# # samples named incorrectly by ENCODE for hg19 data 
# # this could be because the gene name was diffferent in hg19 genome 
# hg19_sample_renamings = {
#     "AGO1": "EIF2C1", 
#     "CELF1": "CUGBP1", 
#     "APOBEC3C": "APOBE",
#     "YBX3": "CSDA", 
#     "NELFE": "RDBP", 
#     "CCAR2": "KIAA1967", 
#     "PKM": "PKM2"
# }

# # replace hg38 names with hg19 names so it matches data folder structure
# knockdown_metadata = knockdown_metadata.replace(hg19_sample_renamings)

# this should print nothing since we replaced the name 
knockdown_metadata[knockdown_metadata["Experiment target"]=="AGO1"]

2134

,File accession,File format,File type,File format type,Output type,File assembly,Experiment accession,Assay,Donor(s),Biosample term id,Biosample term name,Biosample type,Biosample organism,Biosample treatments,Biosample treatments amount,Biosample treatments duration,Biosample genetic modifications methods,Biosample genetic modifications categories,Biosample genetic modifications targets,Biosample genetic modifications gene targets,Biosample genetic modifications site coordinates,Biosample genetic modifications zygosity,Experiment target,Library made from,Library depleted in,Library extraction method,Library lysis method,Library crosslinking method,Library strand specific,Experiment date released,Project,RBNS protein concentration,Library fragmentation method,Library size range,Biological replicate(s),Technical replicate(s),Read length,Mapped read length,Run type,Paired end,Paired with,Index of,Derived from,Size,Lab,md5sum,dbxrefs,File download URL,Genome annotation,Platform,Controlled by,File Status,s3_uri,Azure URL,File analysis title,File analysis status,Audit WARNING,Audit NOT_COMPLIANT,Audit ERROR
202,ENCFF753WMF,fastq,fastq,NaN,reads,NaN,ENCSR268JDD,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,1,/files/ENCFF521YJN/,NaN,NaN,2230177408,"Brenton Graveley, UConn",110d0c88d05bd9e3fa138d85eedd1e8f,SRA:SRR4421556,https://www.encodeproject.org/files/ENCFF753WMF/@@download/ENCFF753WMF.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF781HCE/, /files/ENCFF420XPX/",released,s3://encode-public/2014/10/29/96950fd8-683e-4ae6-9477-e97419de86c2/ENCFF753WMF.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/10/29/96950fd8-683e-4ae6-9477-e97419de86c2/ENCFF753WMF.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
203,ENCFF259SCX,fastq,fastq,NaN,reads,NaN,ENCSR268JDD,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,1,/files/ENCFF650VKT/,NaN,NaN,2091118688,"Brenton Graveley, UConn",7f00fefead205961d8b8fed15faa5788,SRA:SRR4421555,https://www.encodeproject.org/files/ENCFF259SCX/@@download/ENCFF259SCX.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF781HCE/, /files/ENCFF420XPX/",released,s3://encode-public/2014/10/29/f837508e-5691-4e1e-b119-b68087c9f3fc/ENCFF259SCX.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/10/29/f837508e-5691-4e1e-b119-b68087c9f3fc/ENCFF259SCX.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
204,ENCFF650VKT,fastq,fastq,NaN,reads,NaN,ENCSR268JDD,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,2,/files/ENCFF259SCX/,NaN,NaN,2044576438,"Brenton Graveley, UConn",ff17207e50a63549bcff7716a6d17ce7,SRA:SRR4421555,https://www.encodeproject.org/files/ENCFF650VKT/@@download/ENCFF650VKT.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF121QGM/, /files/ENCFF861HTL/",released,s3://encode-public/2014/10/29/c7a9b802-dcaa-4bb1-bd80-78c564803398/ENCFF650VKT.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/10/29/c7a9b802-dcaa-4bb1-bd80-78c564803398/ENCFF650VKT.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
205,ENCFF521YJN,fastq,fastq,NaN,reads,NaN,ENCSR268JDD,shRNA RNA-seq,/human-donors/ENCDO000AAD/,EFO:0002067,K562,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,2,/files/ENCFF753WMF/,NaN,NaN,2176679964,"Brenton Graveley, UConn",04c55aef44450be97fe25aa76d893c9f,SRA:SRR4421556,https://www.encodeproject.org/files/ENCFF521YJN/@@download/ENCFF521YJN.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF121QGM/, /files/ENCFF861HTL/",released,s3://encode-public/2014/10/29/80709ec1-40fe-48ad-89b0-3a3a8307e4e8/ENCFF521YJN.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/10/29/80709ec1-40fe-48ad-89b0-3a3a8307e4e8/ENCFF521YJN.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
960,ENCFF406QLI,fastq,fastq,NaN,reads,NaN,ENCSR533HXS,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,1,/files/ENCFF212NRX/,NaN,NaN,2582032494,"Brenton Graveley, UConn",070e30d3d1dde2ecf13be3c28c34318b,SRA:SRR3469496,https://www.encodeproject.org/files/ENCFF406QLI/@@download/ENCFF406QLI.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF510FRX/, /files/ENCFF307YSL/",released,s3://encode-public/2014/11/04/1f0cab99-3633-414b-bacf-637881ab3af0/ENCFF406QLI.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/11/04/1f0cab99-3633-414b-bacf-637881ab3af0/ENCFF406QLI.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
961,ENCFF739XYN,fastq,fastq,NaN,reads,NaN,ENCSR533HXS,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,1,/files/ENCFF074NKA/,NaN,NaN,2378606647,"Brenton Graveley, UConn",30f75a1e21bd82c4c9071e2540506bc7,SRA:SRR3469497,https://www.encodeproject.org/files/ENCFF739XYN/@@download/ENCFF739XYN.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF510FRX/, /files/ENCFF307YSL/",released,s3://encode-public/2014/11/04/7d7fb63c-41b3-4dc1-95ce-559c5eeff57a/ENCFF739XYN.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/11/04/7d7fb63c-41b3-4dc1-95ce-559c5eeff57a/ENCFF739XYN.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
962,ENCFF212NRX,fastq,fastq,NaN,reads,NaN,ENCSR533HXS,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,1,1_1,100,NaN,paired-ended,2,/files/ENCFF406QLI/,NaN,NaN,2543497036,"Brenton Graveley, UConn",8d78c57bea27ad55652b1523ecd7f796,SRA:SRR3469496,https://www.encodeproject.org/files/ENCFF212NRX/@@download/ENCFF212NRX.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF409JQD/, /files/ENCFF823EPB/",released,s3://encode-public/2014/11/04/b333f661-62df-4692-88a9-4ec2028d2332/ENCFF212NRX.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/11/04/b333f661-62df-4692-88a9-4ec2028d2332/ENCFF212NRX.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN
963,ENCFF074NKA,fastq,fastq,NaN,reads,NaN,ENCSR533HXS,shRNA RNA-seq,/human-donors/ENCDO000AAC/,EFO:0001187,HepG2,cell line,Homo sapiens,NaN,NaN,NaN,RNAi,interference,"{'schema_version': '14', 'aliases': [], 'organism': {'schema_version': '6', '@type': ['Organism', 'Item'], 'name': 'human', 'taxon_id': '9606', 'scientific_name': 'Homo sapiens', '@id': '/organisms/human/', 'uuid': '7745b647-ff15-4ff3-9ced-b897d4e2983c', 'status': 'released'}, 'genes': ['/genes/26523/'], '@type': ['Target', 'Item'], 'name': 'AGO1-human', 'label': 'AGO1', '@id': '/targets/AGO1-human/', 'title': 'AGO1 (Homo sapiens)', 'investigated_as': ['RNA binding protein'], 'uuid': '58574588-7bee-49e6-8628-4b3d03725dff', 'status': 'released'}",NaN,NaN,NaN,AGO1,polyadenylated mRNA,NaN,Maxwell 16 LEV simpleRNA Cells Kit (Promega cat#: AS1270),NaN,NaN,reverse,2014-11-20,ENCODE,NaN,chemical (Illumina TruSeq),>200,2,2_1,100,NaN,paired-ended,2,/files/ENCFF739XYN/,NaN,NaN,2335545185,"Brenton Graveley, UConn",d286047b3abcec708e17cb21cc3618fb,SRA:SRR3469497,https://www.encodeproject.org/files/ENCFF074NKA/@@download/ENCFF074NKA.fastq.gz,NaN,Illumina HiSeq 2000,"/files/ENCFF409JQD/, /files/ENCFF823EPB/",released,s3://encode-public/2014/11/04/29c05b91-c19f-4908-85ed-63eeee1bbe78/ENCFF074NKA.fastq.gz,https://datasetencode.blob.core.windows.net/dataset/2014/11/04/29c05b91-c19f-4908-85ed-63eeee1bbe78/ENCFF074NKA.fastq.gz?sv=2019-10-10&si=prod&sr=c&sig=9qSQZo4ggrCNpybBExU8SypuUZV33igI11xw0P7rB3c%3D,NaN,NaN,missing biosample characterization,NaN,NaN

## Get RBPs To Look At

Either take: 
* All `shRNA` RBPs
* RBPs w/ Both `eCLIP` and `shRNA`

In [6]:
# dictionary by cell line and splice type of the files to load
input_data_files = {}

# for each cell line and splice type 
for cell_line in cell_lines: 
    # initialize cell line sub dict 
    input_data_files[cell_line] = {}
    
    # subset eclip and knockdown metadata to cell type 
    tmp_eclip = eclip_metadata[eclip_metadata["Biosample term name"]==cell_line]
    tmp_shrna = knockdown_metadata[knockdown_metadata["Biosample term name"]==cell_line]
    
    # if you want to look at RBPs that have both shRNA and eCLIP data 
    if eclip_intersection: 
    
        # subset knockdown metdata to eclip data that has the RBPs
        # get all the targets and subset to the unique RBPs
        rbps_to_take = tmp_shrna[
            tmp_shrna["Experiment target"].isin(
                tmp_eclip["Experiment target"]
            )
        ]["Experiment target"].unique().tolist()
    
    # RBPs that have shRNA data regardless of eCLIP
    elif not eclip_intersection: 
        
        # just take all the RBP targets
        # need to remove NaN values since control samples have no targets 
        rbps_to_take = tmp_shrna["Experiment target"].dropna().unique().tolist()
        
    # for each splice type 
    for splice_type in splice_types: 
        
        # glob for the cell line and splice type of the data files 
        tmp_data_files = sorted(
            glob.glob(
                "{}/*{}*/*{}*.txt".format(input_data_folder, cell_line, splice_type), 
                recursive=True
            )
        )         
        
        # remove files from that have the tag "Transfection" because these files are not polyadenylated RNA 
        # also remove any files whose RBP is not included in the common RBPs
        input_data_files[cell_line][splice_type] = [file for file in tmp_data_files if not "Transfection" in file and file.split("/")[-2].split("-")[0] in rbps_to_take ]
        
        len(input_data_files[cell_line][splice_type])

232

232

232

232

232

212

212

212

212

212

## Matrixization Algorithm

In [7]:
def matrixize_rmats_table(file = None, get_total_counts=None, inclevel=None):
    """
    Takes all rMATS files and extracts genomic features from them to create a matrix using junction and skipping counts. 
    
    Parameters:
        files (list): list of file paths where the rMATS files can be found (default = None)
        get_total_counts (bool): whether to sum junction and skipping counts or keep them separate (default = None)   
        inclevel (bool): if True, take the inclusion level and if False use the SJC/IJC counts 
    
    Returns: 
        matrix (pandas.DataFrame): a Pandas DataFrame where features are columns and rows are samples
        
    """
    
    assert file!=None and get_total_counts!=None and inclevel!=None
    
     # need to extract rbp and cell line from path 
    rbp_cell_line = None

    for path_part in file.split("/"): 
        # save the entire line that has the rbp-batch-cell_line nomenclature
        if "HepG2" in path_part or "K562" in path_part: 
            rbp_cell_line = path_part 

    assert rbp_cell_line != None, rbp_cell_line
    
    # dictionary where genomic position feature is key and value is sub-dict 
    # sub-dict has key for sample and value of that is the counts 
    # NOTE: if "get_total_counts=False", you will have double the sampls since "SJC" and "IJC" will be kept separate. 
    matrix_dict = {}

    # load as dataframe 
    tmp_df = pd.read_csv(file,sep="\t")

    # get index position of concatenation start string 
    # we are making strings from the exact chromosome, strand and genomic positions 
    # to do so, we need to concatenate all rows after "chr" column until the "ID.1" column 
    # this is a known assumption that all the chromosome, strand, and genomic position information 
    # is between the "chr" column upto and excluding "ID.1" column
    concatenation_start = tmp_df.columns.tolist().index("chr")
    concatenation_end = tmp_df.columns.tolist().index("ID.1")

    # take all columns to make feature name 
    # convert them to strings 
    # concatenate each column row-wise with "_" as delimiter
    # (e.g. chr17_-_62496792_62497000_62496792_62496891_62498127_62498187)
    tmp_df["Feature"] = tmp_df.iloc[
        :,concatenation_start:concatenation_end
    ].astype("str").apply(
        lambda x: '_'.join(x.values.tolist()), axis=1
    )
    
    # get inclevel columns
    if inclevel: 
        count_columns = ["IncLevel1", "IncLevel2"]
    # get IJC/SJC counts columns
    elif not inclevel: 
        count_columns = ["IJC_SAMPLE_1", "SJC_SAMPLE_1", "IJC_SAMPLE_2", "SJC_SAMPLE_2"]
        
    # take all the counts that are comma separated per column 
    # and combine them into one column that is entirely comma-separated 
    # e.g. 780,750	758,759	260,253	543,571	 becomes 780,750,758,759,260,253,543,571
    tmp_df["Counts"] = tmp_df[count_columns].astype(str).apply(
        lambda x: ",".join(x.values.tolist()),axis=1
    )

    # subset to the columns involving features and counts 
    tmp_df = tmp_df[["Feature", "Counts"]]

    # for each feature we are now going to sum up the skipping and inclusion junction counts
    # there are 8 numbers corresponding to 4 samples
    # we are using the sample count summation indices dictionary that tells us which indices to pull from list
    for row in tmp_df.itertuples():
        
        feature = row[1]
        matrix_dict[feature] = {}
        
        numbers = row[2]
        numbers = numbers.split(',') 
        
        # get inclevel values 
        if inclevel: 
            for sample_name, ratio in zip(summated_sample_ordering, numbers): 
                
                sample_name = "{}-{}".format(rbp_cell_line, sample_name)
                
                # if NA then save as Numpy NaN
                if ratio =="NA": 
                    matrix_dict[feature][sample_name] = np.nan
                # just save the inclevel value
                else: 
                    matrix_dict[feature][sample_name] = ratio
                                
        # get actual counts (i.e. SJC/IJC)
        elif not inclevel: 

            # for each feature, we need to sum the skipping and inclusion counts 
            # 4 samples so 4 features
            if get_total_counts: 
                # get list of length 4  
                summations = summate_counts(numbers)

                assert len(summations)==4 and len(summated_sample_ordering)==4

                # assign each value in their respective order with correct sample naming
                for sample_name, value in zip(summated_sample_ordering, summations): 

                    # include RBP, batch, and cell line info in the sample name 
                    sample_name = "{}-{}".format(rbp_cell_line, sample_name)

                    matrix_dict[feature][sample_name] = value    


            # OR ELSE for each feature, separate skipping and inculsion counts 
            # 4 samples * (SJC/IJC) = 8 features 
            elif not get_total_counts:

                assert len(numbers)==8 and len(non_summated_sample_ordering)==8

                # assign each value in correct order 
                for sample_name, value in zip(non_summated_sample_ordering, numbers): 

                    # include RBP, batch, and cell line info in the sample name 
                    sample_name = "{}-{}".format(rbp_cell_line, sample_name)

                    matrix_dict[feature][sample_name] = value   
    
    # return dataframe where features are the index and columns are samples 
    return pd.DataFrame.from_dict(
        matrix_dict, 
        orient="index"
    )
    

def summate_counts(numbers): 
    """
    Parameters: 
        numbers (list): list of numbers to be summated in particular order
    
    Returns: 
        summation_list (list): list of numbers that have come as a result of correct summations
    
    """
        
    # list to save the summations 
    summation_list = []
    
    # which list indices should be pulled out for each sample
    # when summating and finding out counts per sample per feature 
    sample_count_summation_indices = {
        "KO_1": [0,2],
        "KO_2": [1,3],
        "CTRL_1": [4,6],
        "CTRL_2": [5,7],
    }
                
    # to get counts for each sample
    # pull the correct indices corresponding to junction and skipping counts for that sample 
    # sum that up and save those results in dictionary
    for sample in sample_count_summation_indices: 
        summation_list.append(
            sum(
                [int(numbers[index]) for index in sample_count_summation_indices[sample] ]
            )
        
        )
        
    return summation_list

## Validation of Matrix Creation Algorithm

In [8]:
random_file = '/project/PlatigLab/data/collaborators/BWH/ENCODE_shRNA_RBP_KD/AARS-BGHLV17-HepG2/SE.MATS.JC.txt'

original_df = pd.read_csv(random_file, sep="\t")

original_df.iloc[17:20, :]

,ID,GeneID,geneSymbol,chr,strand,exonStart_0base,exonEnd,upstreamES,upstreamEE,downstreamES,downstreamEE,ID.1,IJC_SAMPLE_1,SJC_SAMPLE_1,IJC_SAMPLE_2,SJC_SAMPLE_2,IncFormLen,SkipFormLen,PValue,FDR,IncLevel1,IncLevel2,IncLevelDifference
17,58,ENSG00000092377.13,TBL1Y,chrY,+,6995803,6995898,6978212,6978243,7021448,7021537,58,"2,1","0,0","0,2","0,1",194,99,1.0,1.0,"1.0,1.0","NA,0.505",0.495
18,59,ENSG00000092377.13,TBL1Y,chrY,+,7070195,7070328,7063896,7064149,7070719,7070861,59,"0,2","0,0","4,0","2,0",198,99,1.0,1.0,"NA,1.0","0.5,NA",0.500
19,62,ENSG00000067646.11,ZFY,chrY,+,2953908,2953997,2935476,2935769,2961073,2961286,62,"20,17","1,0","17,13","1,0",188,99,1.0,1.0,"0.913,1.0","0.9,1.0",0.007

In [9]:
matrixize_rmats_table(file = random_file, inclevel=True, get_total_counts=True).iloc[17:20,:]

,AARS-BGHLV17-HepG2-KO_Sample_1,AARS-BGHLV17-HepG2-KO_Sample_2,AARS-BGHLV17-HepG2-CTRL_Sample_1,AARS-BGHLV17-HepG2-CTRL_Sample_2
chrY_+_6995803_6995898_6978212_6978243_7021448_7021537,1.0,1.0,NaN,0.505
chrY_+_7070195_7070328_7063896_7064149_7070719_7070861,NaN,1.0,0.5,NaN
chrY_+_2953908_2953997_2935476_2935769_2961073_2961286,0.913,1.0,0.9,1.0

## Create All Matrices

In [10]:
all_matrices = {}

# for each cell line 
for cell_line in cell_lines: 
    
    all_matrices[cell_line] = {}
    
    # for each splice type 
    for splice_type in splice_types: 
        
        # dataframe for outer joining 
        join_df = pd.DataFrame()
        
        "{} {}".format(cell_line, splice_type)
        
        # for each rMATS table associated with this cell line and splice type
        for file in input_data_files[cell_line][splice_type]: 
            
            # convert rMATS table to matrix of counts 
            matrix = matrixize_rmats_table(
                file = file, 
                get_total_counts = get_total_counts, 
                inclevel=get_inclevel
            )
            
            if get_total_counts: 
                assert len(matrix.columns)==4
            elif not get_total_counts: 
                assert len(matrix.columns)==8
                
            join_df = join_df.join(matrix, how="outer")
        
        # check that number of samples is as expected
        if get_total_counts: 
            assert len(join_df.columns)==len(input_data_files[cell_line][splice_type])*4
        elif not get_total_counts: 
            assert len(join_df.columns)==len(input_data_files[cell_line][splice_type])*8
                    
        # save to dictionary 
        all_matrices[cell_line][splice_type] = join_df

'HepG2 A3SS'

'HepG2 A5SS'

'HepG2 SE'

'HepG2 MXE'

'HepG2 RI'

'K562 A3SS'

'K562 A5SS'

'K562 SE'

'K562 MXE'

'K562 RI'

In [11]:
for cell_line in cell_lines: 
    for splice_type in splice_types: 
        all_matrices[cell_line][splice_type].shape

(12843, 928)

(8250, 928)

(208179, 928)

(49156, 928)

(5866, 928)

(13349, 848)

(8866, 848)

(233755, 848)

(60555, 848)

(5848, 848)

## Find Duplicate Samples

### Get Duplicates from `shRNA` Metadata

#### hg19 Version

In [12]:
# import requests 
# import re

# def get(resource): # resource is the experiment accession number
#     base_url = 'https://www.encodeproject.org/{}?format=json'
#     headers = {'accept': 'application/json'}
#     response = requests.get(base_url.format(resource), headers=headers)
#     return response.json()

In [13]:
# # key is cell line and the value is another dictionary 
# # sub-dict key is control sample accession and value is RBPs involved 
# sample_controls = {}

# # for each cell line 
# for cell_line in cell_lines: 
        
#     # subset to cell line metadata 
#     tmp_shrna = knockdown_metadata[knockdown_metadata["Biosample term name"]==cell_line]
        
#     # list corresponding to new column for control 
#     # experiment accessions for each knockdown 
#     control_accessions_list = []
    
#     # iterate through each controlled by value 
#     for accession in tmp_shrna["Experiment accession"].to_list(): 
        
#         # use JSON response getter to retrieve the control accession ID and save it
#         control_accessions_list.append(
#             get(accession)["possible_controls"][0]["accession"]
#         )
    
#     # add new column to dataframe 
#     tmp_shrna["Control Accession"] = control_accessions_list
    
#     # save the results 
#     sample_controls[cell_line] = tmp_shrna.groupby("Control Accession")["Experiment target"].apply(set).to_dict()

#### hg38 Version

In [14]:
# key is cell line and the value is another dictionary 
# sub-dict key is control sample accession and value is RBPs involved 
sample_controls = {}

# for each cell line 
for cell_line in cell_lines: 
        
    # subset to cell line metadata 
    tmp_shrna = knockdown_metadata[knockdown_metadata["Biosample term name"]==cell_line]
    
    # get knockdown files 
    knockdown_only = tmp_shrna[tmp_shrna["Experiment target"].notna()]
    
    # list corresponding to new column for control 
    # experiment accessions for each knockdown 
    control_accessions_list = []
    
    # iterate through each controlled by value 
    for path_lists in knockdown_only["Controlled by"].to_list(): 
       
        # parse out the file identifiers using ENCFF key 
        file_ids = [part for part in path_lists.split("/") if "ENCFF" in part]
        
        # for each file identifier, subset to that file identifier,
        # take experiment accession, convert to list, and save first entry 
        accession_ids = list(set([tmp_shrna[tmp_shrna["File accession"]==file_id]["Experiment accession"].to_list()[0] for file_id in file_ids]))
        # make sure there's only one accession id 
        assert len(accession_ids)==1
        
        # add accession id to list of accession ids for each knockdown
        control_accessions_list.append(accession_ids[0])
      
    # add new column to dataframe 
    knockdown_only["Control Accession"] = control_accessions_list
    
    # save the results 
    sample_controls[cell_line] = knockdown_only.groupby("Control Accession")["Experiment target"].apply(set).to_dict()

/tmp/ipykernel_184330/2344471050.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knockdown_only["Control Accession"] = control_accessions_list
/tmp/ipykernel_184330/2344471050.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knockdown_only["Control Accession"] = control_accessions_list

### Remove duplicated samples and validate that we are removing only what's expected

Need to check that across the `rMATS` results, for the duplicates: 
* The "Sample 1" and "Sample 2" identifiers are duplicates of each other 
    * For example, you don't want Sample 1 to be a duplicate of Sample 2 in certain cases
        * That would mean that certain rMATS runs for certain RBPs had the wrong sample orderings inputted to them 
* For any group of RBP knockdowns that should share a duplicate, there should only be 2 samples left after removing duplicates

In [15]:
# dictionary organized first by cell line and then by splice type 
# then within that each key is the original sample name and then the value is the new sample name
deduped_renamed_samples = {}

for cell_line in cell_lines: 
    deduped_renamed_samples[cell_line] = {}
    
    for splice_type in splice_types:     
        deduped_renamed_samples[cell_line][splice_type] = {}
                
        # transpose so samples are rows and features are columns
        cell_line_splice_type_df = all_matrices[cell_line][splice_type].T
        
        # get the features that have no missing values and save as list 
        columns_to_keep = (cell_line_splice_type_df.notna().sum() / cell_line_splice_type_df.index.size)==1
        columns_to_keep = columns_to_keep[columns_to_keep==True].index.to_list()
        
        # subset to those features
        cell_line_splice_type_df = cell_line_splice_type_df[columns_to_keep]
        
        # temporary dictionary with all renamed sample names 
        tmp_renamed_strings = {}
        
        # for each control accession corresponding to several RBP knockdowns 
        for control_accession in sample_controls[cell_line]: 
            
            # get row names that correspond to the knockdown RBP and are control samples 
            rows_to_subset = [value for value in cell_line_splice_type_df.index.to_list() if value.split("-")[0] in sample_controls[cell_line][control_accession] and "-CTRL_" in value]
            
            # there should be 2 * the number of rbps shared for total control samples 
            assert len(rows_to_subset) == len(sample_controls[cell_line][control_accession]) * 2, "{} {}".format(
                sample_controls[cell_line][control_accession], 
                rows_to_subset
            )
            
            # subset rows to those control samples for these RBPs
            tmp_df = cell_line_splice_type_df[cell_line_splice_type_df.index.isin(rows_to_subset)]
            
            # group the samples across all columns to then be able to inspect what samples are duplicates of what 
            groupings = tmp_df.groupby(by=tmp_df.columns.to_list()).groups
            
            # for each group of samples that are duplicates according to the data
            for inclevel_combo in groupings: 
                # assert that all of them end in "_1" or "_2" 
                # this avoids situation where a "_1" is a duplicate of a "_2"
                assert len(
                    set(
                        groupings[inclevel_combo].str.split("_").str[-1].to_list()
                    )
                )==1
                
                # concat all RBPs together that share the same control 
                concat_rbps = "_".join(
                    [value.split("-")[0] for value in groupings[inclevel_combo].to_list()]
                )
                
                # replace RBP in sample with concat_rbps string
                replace_strings = [value.replace(value.split("-")[0], concat_rbps) for value in groupings[inclevel_combo].to_list()]
                
                # populate the sample renaming dict 
                for original_string, new_string in zip(groupings[inclevel_combo].to_list(), replace_strings): 
                    tmp_renamed_strings[original_string] = new_string

            # check that dropping duplicates only has two samples left 
            assert tmp_df.drop_duplicates().index.size==2            
        
        # save the renaming dictionary mapping 
        deduped_renamed_samples[cell_line][splice_type] = tmp_renamed_strings

## Validate that the sample string name remapping algorithm is valid

In [16]:
for cell_line in cell_lines: 

    reference_sample_renamings = deduped_renamed_samples[cell_line][splice_type]
    
    for splice_type in splice_types:
        
        assert deduped_renamed_samples[cell_line][splice_type] == reference_sample_renamings

## Rename samples and validate renaming works as expected

In [17]:
for cell_line in cell_lines: 
    for splice_type in splice_types: 
        
        # transpose so that features are column and samples are rows
        tmp_df = all_matrices[cell_line][splice_type].T
        
        # get the features that have no missing values and save as list 
        columns_to_keep = (tmp_df.notna().sum() / tmp_df.index.size)==1
        columns_to_keep = columns_to_keep[columns_to_keep==True].index.to_list()
                
        # subset to those features
        tmp_df = tmp_df[columns_to_keep]
        
        # rename the samples 
        tmp_df = tmp_df.rename(index = deduped_renamed_samples[cell_line][splice_type])
        # remove duplicates 
        tmp_df = tmp_df.drop_duplicates()
        
        # make sure that all sample names are unique 
        assert tmp_df.index.size == tmp_df.index.unique().size
        
        # save the updated matrices 
        all_matrices[cell_line][splice_type] = tmp_df

## Output FIles

In [18]:

# for each cell line and splice type 
for cell_line in cell_lines: 
    for splice_type in splice_types: 
        
        all_matrices[cell_line][splice_type].T.to_csv(
            "{}/{}_{}.tsv.gz".format(
                output_data_folder, 
                cell_line, 
                splice_type
            ), 
            compression="gzip", 
            sep="\t"
        )